### ISSUE TITLE
Need assistance with Post-Signed HmacSHA512 Value if example apiSecret = "ABCDEFGHIJ"

### ISSUE THREAD

**Issue by ElCasador** [Bittrex/bittrex.github.io#100]
When I use a contentHash with an empty string I receive the proper output as described in the documentation as shown:
cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e

Pre-Signed Value:
var presign = "1542323450016https://api.bittrex.com/v3/balancesGETcf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"

Can someone list the below value if:
apiSecret = "ABCDEFGHIJ"

var signature = CryptoJS.HmacSHA512(preSign, apiSecret).toString(CryptoJS.enc.Hex);  
^^^
I'm not working with this syntax and would like to know if I'm still using proper encoding. In v1.1, I am receiving proper values, and when I use my Key/Secret I can access the my data.  

Essentially what I'm wanting to verify is:
print(signature), with the above example information

**Comment by cyrus19909** [comment]
If you are asking for the value of signature with the above pre-signature and apiSecret, it will look something like
 `let testPresign ="1542323450016https://api.bittrex.com/v3/balancesGETcf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e";
console.log(CryptoJS.HmacSHA512(testPresign, 'ABCDEFGHIJ').toString(CryptoJS.enc.Hex));`

` 
9e6c54f689451ea937abad1b1fcdfaa5cf0a9d77c21df15d05878856c27919861f1080969f2bd29b81bd783c06723ce928fba11a61bb1ec1f3f24de386959578`

Hopefully the above is helpful . Let us know if you need any more help with the above.

**Comment by ElCasador** [comment]
Okay great that's what I have...just means I'm not calling information correctly somewhere. Unfortunately there's not much information regarding my language and I'm new at JSON and learning how to make calls. I think I need to figure out how to write the contentHash information. I see people are putting the application/json such as:

[
  {
    "currencySymbol": "string",
    "total": "number (double)",
    "available": "number (double)"
  }
]

and then "stringifing" it to do contentHash. Something I have to learn still.

Thanks for the help!!

**Comment by cyrus19909** [comment]
I am glad it worked. 
You can use something like the following 
`function requestContentHash(content) {
    if (content == null) {
        return ' The conetent cannot be null'
    }
    return CryptoJS.SHA512(content).toString(CryptoJS.enc.Hex)
}`
and then pass an empty sting as content where the body is not required . Let us know if that helps and if we can help you in any other way
