### ISSUE TITLE
get my trade fees

### ISSUE THREAD

**Issue by npomfret** [Bittrex/bittrex.github.io#101]
Is it possible to get my trade fees from either the old or new api?

@cyrus19909

**Comment by sp33dy** [comment]
I too would like to know this. Given the special rates right now and the future ones, I'd like to be able to pull the fee I'm now paying as a maker and taker; it's important to understand this as part of a placed order from my trading app.

**Comment by cyrus19909** [comment]
Hi @npomfret and @sp33dy , currently we don't provide maker/taker fee via API but you can get the transaction fee using https://api.bittrex.com/v3/currencies . the maker/taker fee for promotions are generally available over our zendesk platform and social media. 
[https://bittrex.zendesk.com/hc/en-us/articles/360040091892-Promotion-Bittrex-Birthday-Fee-Promotion] is where you can find our current promotions. I have added the above to our list of requested features . Please let us know if we can help in any other way .

**Comment by sp33dy** [comment]
Thanks Cyrus19909. So you do advise us to use the v3 API? Happy to do so. It's REALLY important for us to be able to get the 'charge' per order, given bots need to know this calculation. The alternative is to put the charge amount into the placed but not completed order (but I doubt that will happen). It's required for calculating profits....

**Comment by cyrus19909** [comment]
Yes using V3 api is recommended as you get more options of requests and other API endpoints. Documentation of which can be found here https://bittrex.github.io/api/v3 . I totally understand the necessity of getting the trade cost for automatic calculation . We are continuously adding new features to make the experience better for everyone hence are open to suggestions .

**Comment by kroitor** [comment]
@cyrus19909 would you please recommend it officially in the API docs?

**Comment by npomfret** [comment]
... and deprecate the old API

**Comment by cyrus19909** [comment]
We are continuously adding new features to our v3 api hence the beta tag to it. We will keep you posted on the release date .

**Comment by npomfret** [comment]
But you are recommending it for production use.  Either it's beta or it's production ready.  Just because you are still adding features, which is great to hear, it doesn't mean its not production ready.  Can you just remove the beta badge and deprecate the old one?  i need  some confidence that it's not going to get pulled like v2 before we i trade with you.
