### ISSUE TITLE
Please define 'Rate' and 'Quantity' in the OrderBooks

### ISSUE THREAD

**Issue by Almira1601** [Bittrex/bittrex.github.io#102]
Hi, I am extracting order books for token pairs. It seems that a 'MarketName' is formed as 'BasisCurrency'-'MarketCurrency'. In traditional currency pairs Basis currency is a transaction currency. So, in buy orders Rate would indicate how much of the market currency you need to get one unit of the Base currency. You are buying a basis currency and implicitly selling a market currency. In sell orders you are selling a Basis currency and buying a market currency. Rate would indicate how much of the market currency you want for selling one unit of the basis currency. 
In Bittrex orders it seems to be other way around (Rate is expressing units of basis currency for one unit of a market currency). Please can you clarify this? Also, what is bought and sold then in the buy and sell orders? Is that a market currency? Thank you in advance!

**Comment by laserlance** [comment]
You are correct that the way Bittrex handles this is opposite of how other exchanges deal with this. There are only a few base currencies on Bittrex, and the rate is how much the coin is worth in the base currency.

For example, say you want to buy on the BTC-VTC market, you need x-number of BTC to buy n-quantity of VTC. If you sell the VTC back to BTC, you're on the same market, BTC-VTC, and so, once sold, you have y-amount of BTC from your n-quantity of VTC. The rate is always in the base currency.

**Comment by Almira1601** [comment]
Thank you so much for your response! Just to be completely sure, would you please confirm whether the following is right. I have the following example: ETH - GNO.json file which has been extracted. I have the following here:
"sell": [{"order_id": 14182, "Rate": 0.0946, "Quantity": 0.81342633},...
"buy": [{"order_id": 14250, "Rate": 0.08637609, "Quantity": 39.36731633},...

Would the following interpretation be correct then? Please also confirm whether the volumes refer to the market currency in both cases as well. 
For the sell order we have: we would like to sell 0.81342633 amount of GNO and receive at least 0.0946 amount of ETH for it
For the buy order we have: we would like to buy 39.36731633 amount of GNO and pay at most 0.0946 amount of ETH for it.

**Comment by cyrus19909** [comment]
@Almira1601 

We are sorry that you are facing the above issue. Are you using our API or our websockets for querying the order book ? . If you are using the v3 api,  please find an example below for the explanation . 

The https://api.bittrex.com/v3/markets/nmr-usdt/orderbook returns the current orderbook like 
`{
    "bid": [
        {
            "quantity": "4.57204333",
            "rate": "16.98272723"
        },
        {
            "quantity": "5.99376385",
            "rate": "16.98224688"
        },
        {
            "quantity": "5.25818319",
            "rate": "16.98128618"
        },
        {
            "quantity": "0.39853011",
            "rate": "16.97936478"
        },
        {
            "quantity": "4.07349772",
            "rate": "16.97725102"
        },
        {
            "quantity": "0.55443010",
            "rate": "16.97526549"
        },
        {
            "quantity": "0.19661142",
            "rate": "16.81657819"
        },
        {
            "quantity": "5.88831352",
            "rate": "16.77546333"
        },
        {
            "quantity": "4.43364778",
            "rate": "16.77546331"
        },
        {
            "quantity": "4.55650551",
            "rate": "16.77450573"
        },
        {
            "quantity": "4.23860311",
            "rate": "16.77048401"
        },
        {
            "quantity": "5.14373219",
            "rate": "16.74636297"
        },
        {
            "quantity": "5.03039694",
            "rate": "16.74004405"
        },
        {
            "quantity": "0.66250000",
            "rate": "16.73561550"
        },
        {
            "quantity": "0.66250000",
            "rate": "16.73482618"
        },
        {
            "quantity": "5.24699868",
            "rate": "16.70253231"
        },
        {
            "quantity": "5.63341957",
            "rate": "16.69546331"
        },
        {
            "quantity": "4.97117272",
            "rate": "16.69450573"
        },
        {
            "quantity": "5.49575652",
            "rate": "16.69198999"
        },
        {
            "quantity": "5.54420348",
            "rate": "16.69048401"
        },
        {
            "quantity": "33.00948611",
            "rate": "16.66187708"
        },
        {
            "quantity": "15.34706739",
            "rate": "16.66187707"
        },
        {
            "quantity": "4.40247694",
            "rate": "16.63028004"
        },
        {
            "quantity": "4.73019326",
            "rate": "16.61450573"
        },
        {
            "quantity": "4.36294431",
            "rate": "16.61048401"
        }
    ],
    "ask": [
        {
            "quantity": "0.10599455",
            "rate": "16.98333582"
        },
        {
            "quantity": "5.93679625",
            "rate": "16.98333587"
        },
        {
            "quantity": "5.32928824",
            "rate": "16.98333595"
        },
        {
            "quantity": "4.97305521",
            "rate": "16.98374457"
        },
        {
            "quantity": "4.79317259",
            "rate": "16.98429252"
        },
        {
            "quantity": "5.99424707",
            "rate": "16.98455355"
        },
        {
            "quantity": "5.67164680",
            "rate": "16.98455366"
        },
        {
            "quantity": "5.67587400",
            "rate": "16.98470868"
        },
        {
            "quantity": "4.41807468",
            "rate": "16.98531810"
        },
        {
            "quantity": "4.97760528",
            "rate": "16.98571011"
        },
        {
            "quantity": "4.77373579",
            "rate": "16.98596222"
        },
        {
            "quantity": "5.69731683",
            "rate": "16.98640646"
        },
        {
            "quantity": "9.51268981",
            "rate": "16.98778292"
        },
        {
            "quantity": "4.04576848",
            "rate": "16.98806062"
        },
        {
            "quantity": "5.25964096",
            "rate": "16.98829517"
        },
        {
            "quantity": "5.58901083",
            "rate": "16.98829528"
        },
        {
            "quantity": "5.46716147",
            "rate": "16.98829542"
        },
        {
            "quantity": "5.87497255",
            "rate": "16.98829554"
        },
        {
            "quantity": "5.68569584",
            "rate": "16.98861664"
        },
        {
            "quantity": "5.08094790",
            "rate": "16.98939606"
        },
        {
            "quantity": "5.28924799",
            "rate": "16.98958436"
        },
        {
            "quantity": "4.56926257",
            "rate": "16.98973478"
        },
        {
            "quantity": "5.79526871",
            "rate": "16.98984472"
        },
        {
            "quantity": "4.08833550",
            "rate": "16.98987731"
        },
        {
            "quantity": "4.06689501",
            "rate": "16.98988057"
        }
    ]
}`
At the same time we can see the orderbook on the UI as 
![image](https://user-images.githubusercontent.com/48460232/78594517-4f5abf80-77fd-11ea-971a-c3d4c2d6abca.png)

As you cans that there is a co-relation between the buy/sell orders . Buy order for 4.57204333 at 16.98272723 per unit. Hence the total coming to 77.6458 . 
Please let us know if the above helps .

**Comment by Almira1601** [comment]
thank you! that helps a lot
