### ISSUE TITLE
Specific historical data?

### ISSUE THREAD

**Issue by dorev** [Bittrex/bittrex.github.io#104]
Hello Bittrex devs, greetings from Montreal

Is there an endpoint to gather historical candles within a specific time range? So far I've been using `markets/{symbol}/candles?candleInterval` but being able to have `startTime` and `endTime` parameters would be amazing.

Cheers,
Vincent

**Comment by laserlance** [comment]
There may be third party APIs that can do this. I ran one for a while, but there was little interest after the crash so I stopped. I don't know if others have done the same, but at one time there were quite a few third party APIs out there doing this.

**Comment by cyrus19909** [comment]
hi @dorev and @laserlance , we have implemented historical candle endpoint on our end which you can find https://bittrex.github.io/api/v3#operation--markets--marketSymbol--candles--candleInterval--recent-get . That should help with customizing your needs with the data . Please let us know if we can help in any other way ,
