### ISSUE TITLE
How can i get trade records by websocket.

### ISSUE THREAD

**Issue by ryuqing** [Bittrex/bittrex.github.io#106]

**Comment by laserlance** [comment]
Read the API documentation.

**Comment by cyrus19909** [comment]
hi @ryuqing , you can find more information about our websockets on our github page [here](https://bittrex.github.io/api/v1-1) . For keeping a track of your orders, you can use order delta mentioned  under https://bittrex.github.io/api/v1-1#definition-Order-Delta---uO
