### ISSUE TITLE
Protocol mismatch?

### ISSUE THREAD

**Issue by technicalviking** [Bittrex/bittrex.github.io#11]
When calling the /negotiate endpoint for the websocket api, the value for ProtocolVersion is 1.2....  unless I specify a different version in the query string of the URL in the same manner seen in the network tab of my browser.  

Given that my subsequent call to connect to the actual websocket using the connection token hardcoded the protocol version query param to 1.5, I'm not sure what, if any, effect this had on my connectivity...

**Comment by jayarjo** [comment]
Same thing here. Also I wonder what's the current version of the SignalR protocol - version 1.2 and even 1.5 feels a bit outdated. I think Microsoft moved it beyond version 2 already?
