### ISSUE TITLE
Distributions endpoint

### ISSUE THREAD

**Issue by lottaeouss** [Bittrex/bittrex.github.io#110]
Hi,
Could we get an endpoint that shows distribution history for a user?
That would return events included in the below article.  
https://bittrexglobal.zendesk.com/hc/en-us/articles/360009686859-Policy-on-Claims-Stakes-Promotions-Giveaways-Forks-and-Airdrops

**Comment by cyrus19909** [comment]
@lottaeouss thanks for the suggestion above, we will put that in our feature request.
