### ISSUE TITLE
Last orders' prices: there's no way to get them through WebSocket

### ISSUE THREAD

**Issue by egoipse** [Bittrex/bittrex.github.io#111]
Hi,

The poorly documented WebSocket API doesn't let to see before any development one important "bug" (let me call it that way) on suscriptions: there's no way to get last orders' prices through WebSocket.

When suscribing to QueryExchangeState, one gets the following JSON response for any token:

`{
                MarketName : string,
                Nonce      : int,
                Buys:
                [
                    {
                        Quantity : decimal,
                        Rate     : decimal
                    }
                ],
                Sells:
                [
                    {
                        Quantity : decimal,
                        Rate     : decimal
                    }
                ],
                Fills:
                [
                    {
                        Id        : int,
                        TimeStamp : date,
                        Quantity  : decimal,
                        Price     : decimal,
                        Total     : decimal,
                        FillType  : string,
                        OrderType : string
                    }
                ]
            }`

There, in "Fills" value, there is a "Price" key. But this method only streams the first 100 orders... in the API's history. So, if you request, for instance, the data for USD-BTC, the first entry is for 22 July 2017 7:32:54 (1500708774 UNIX time), and the last one, the 100th, is for 31 July 2017 23:31:24 (1501543884). **No trace from last filled orders; therefore, no last prices info.**

Theoretically, it would be possible to update that information wtih a suscription to SubscribeToExchangeDeltas. However, this is the JSON output one gets when suscribing:

`{
            MarketName: string,
            Nonce: int,
            Buys:
                [
                    {
                        Type: string - enum(ADD | REMOVE | UPDATE),
                        Rate: decimal,
                        Quantity: decimal
                    }
                ],
            Sells:
                [
                    {
                        Type: string - enum(ADD | REMOVE | UPDATE),
                        Rate: decimal,
                        Quantity: decimal
                    }
                ],
            Fills:
                [
                    {
                        OrderType: string,
                        Rate: decimal,
                        Quantity: decimal,
                        TimeStamp: date
                    }
                ]
        }`

There one gets the last orders information, but none of the JSON keys is even near to something that would seem like "Price". There are the rate and the quantity, but no the price. And this is not the case with the REST API, which indeed includes the price of last orders: https://api.bittrex.com/api/v1.1/public/getmarkethistory?market=USD-BTC 

So, the only two websocket methods that stream filled orders' information do not provide the most important piece of information: the prices for the last filled orders. The QueryExchangeState streams the price but for the first 100 orders, not for the last ones; and the SubscribeToExchangeDeltas method streams all the last orders information EXCEPT the most important one: the price.

Althougth through other Bittrex WebSocket methods it is possible to get the information for high, low and close values (for example, SubscribeToSummaryDeltas), the  time frame for those values is inconsistent: while the "Last" key is for the last transaction (with an undetermined ocurrence time), the high and low values correspond to the last 24 hours. So, it is not possible to make a technical analisys (for example, an ADX) for another time frame (for instance, 15 or 30 minutes), becausse WebSocket methods do not allow to establish the highs and lows for that time frame if they do not stream the information about price for orders filled in those time frames.

If there's a way to get the prices for last orders through WebSocket (the same way theres is one through REST API's getmarkethistory), the API documentation, which is very poor for WebSocket, does not inform about it.

It seems a bug to get the last orders prices through REST API and not through WebSocket methods. It would be great if you can solve it. It sounds reasonable to include this fundamental piece of information in SubscribeToExchangeDeltas method JSON playload. And it would be reasonable too to stream the info through QueryExchangeState method for the last 100 orders. The info for the first 100 orders is completly unuseful.

**Comment by laserlance** [comment]
Usually when I write such a long and drawn out message regarding something that's been in place for a while already, I end up shooting myself in the foot and shining a big spotlight on my ignorance. Indeed embarrassing.

The price of the trade is the rate multiplied by the quantity. Protip: to prevent rounding errors, use at least 16-decimal places for the price.

**Comment by egoipse** [comment]
Thank you very much for the information.

If this issue has "been in place for a while already", may be it is time for the guys at Bittrex to take the resposabality to documment the  WebSocket part of the API a little bit more seriously. 

Regards and thanks again.

(PS: I'd never feel embarrased for not knowing something. Indeed, I feel very proud for being able to deal with APIs, WebSockets, programming and all that stuff besides the things I do daily in my job. You know, as a hobby. 

What would make me feel embarrased is to code as main job and to be a jerk the rest of the time. As a hobby, you know)
