### ISSUE TITLE
whats the error response when excessed API rate limit

### ISSUE THREAD

**Issue by Ting-y** [Bittrex/bittrex.github.io#112]
What is the the HTTP response when excessed the rate limit? looking for HTTP status code and response body. couldn't found in the api document.

**Comment by laserlance** [comment]
As stated in this answer, it's 429.

https://github.com/Bittrex/bittrex.github.io/issues/65

**Comment by Ting-y** [comment]
#65 only tells the error response for api version 3. I'm currently use api v1.1, should i expecting the same http 429 error?

**Comment by cyrus19909** [comment]
yeah @Ting-y , that is correct . you will receive the 429 error response .
