### ISSUE TITLE
API not properly indicating a partial fill order

### ISSUE THREAD

**Issue by boldrack** [Bittrex/bittrex.github.io#113]
When a partial fill happen and the order info is queried from the server using the endpoint 
https://api.bittrex.com/api/v1.1/account/getorder

The "Quantity" is still the same as the "QuantityRemaining" from the data returned from the server. This way i can detect if my order has been partially fill through the API.

**Comment by cyrus19909** [comment]
Hi boldrack,

If the order has not been filled then the quantity and remaining quantity will be the same. Can you give us an example where you had a partial fill and then the api returned Quantity and QuantityRemaining the same. Also what kind of order was placed .

**Comment by cyrus19909** [comment]
Any update on the above query @boldrack ?
