### ISSUE TITLE
when will API 3 be released?

### ISSUE THREAD

**Issue by npomfret** [Bittrex/bittrex.github.io#114]
The new Bittrex (v3) API has been in beta for months.  Is this one going to be released?  I'm hesitant to even try it out after my experience with v2.

**Comment by cyrus19909** [comment]
Hi @npomfret ,

Yes we understand that the v3 is in beta mode still but we are continuously adding features to it. We will keep you posted regarding the release date . Thanks for your patience

**Comment by npomfret** [comment]
@cyrus19909 is the v3 api officially out of beta now?

**Comment by cyrus19909** [comment]
@npomfret yes v3 is officially out of beta now. You can check the documentation here https://bittrex.github.io/api/v3 and the migration from v1.1 to v3 guide here https://bittrex.github.io/guides/v3/upgrade.

**Comment by hroff-1902** [comment]
Please clarify the current status of v3 API, it's not clear from the comment above neither from the API doc page:

> yes v3 is officially out of beta now.

Does it mean v3 API was released as beta or it went out of beta state to the productions state on 17/06?

**Comment by cyrus19909** [comment]
@hroff-1902 yeah our v3 beta has moved out of beta and is officially available for production use . Please let me know if you have any more questions on that
