### ISSUE TITLE
Unable to pull data for more than 200 records 

### ISSUE THREAD

**Issue by mansipatni** [Bittrex/bittrex.github.io#115]
Hi Guys,
I have checked the API endpoints but there I could not find a way to extract more than 200 records. I am not able to decode the problem, my client is trading in more than 1000 trades a day. Please help me out here

**Comment by cyrus19909** [comment]
Hi @mansipatni ,

Did you get a chance to look at our API docs here https://bittrex.github.io/api/v3#operation--orders-closed-get . The pageSize can be a maximum of 200 . You can use nextPageToken and previousPageToken to iterate over order history getting 200 orders/page. Please let us know if that helps

**Comment by mansipatni** [comment]
Hi Cyrus, 
We are using https://api.bittrex.com/api/v1.1/account/getorderhistory to fetch the order history but we are restricted by the limit of 200 records at a time, is there a way to fetch historical data of last one year?

**Comment by cyrus19909** [comment]
Hi @mansipatni ,

We would recommend you using our v3 api as that is where we are continuously adding features and using https://bittrex.github.io/api/v3#operation--orders-closed-get  will help you get all orders by paginating them. 

Please let us know if we can help you with any api v3 related implementation .

**Comment by magzak** [comment]
I am currently using getorderhistory from v1.1 and get a short history for trades, some months old ones only. Is there a limit of how old trades I can get and are there other time period limits in v3?

**Comment by cyrus19909** [comment]
Hi @magzak ,

For v3 order history you can use https://bittrex.github.io/api/v3#operation--orders-closed-get . We have implemented support for pagination there (200 max) but you can specify dates `startDate` and `endDate` if you need to narrow down your search. Also if you want the complete history you can write a code snippet to paginate your orders using nextPageToken and previousPageToken. Please let us know if that helps

**Comment by magzak** [comment]
Thanks cyrus, so does this mean I can fetch all my trades I have made no matter of how old they are in v3?

What about v1.1 that I am currently using, as far as I can see I can not fetch trades older than some months, is that correct or is there a way to fetch older trades with v1.1?

**Comment by cyrus19909** [comment]
Yes that is correct. You should be able to get your all order history using v3. Regarding v1.1 we dont have options to narrow down the past orders using request parameters .

**Comment by magzak** [comment]
When I read about v3 I see that it's not ready for production use yet so I need to continue to use v1.1 for now:  _Warning: The v3-Beta or other pre-release API versions are not for production use._

So i still wonder if it's a bug in v1.1 since I don't get trades older than some months. With an account who only have older trades I get no trades at all, i.e. it's not the case that there are so many trades that I only get the first ones.

**Comment by cyrus19909** [comment]
We are working on our release process for v3 api by finalizing all the features. We will keep you posted when the official date is out. 
Regarding v1, thats how the current implementation is but you are free to migrate to v3 and get the full order history .
