### ISSUE TITLE
Time zone of the trade data

### ISSUE THREAD

**Issue by mansipatni** [Bittrex/bittrex.github.io#116]
Hi Guys,
Just wanted to know about the time zone of the data we fetch from API since I could not find any time stamp on it indicating UTC or GMT time, could you please help me out here?

**Comment by cyrus19909** [comment]
Hi @mansipatni , we are using UTC time for our v3 api endpoints . You can seen an example here at https://bittrex.github.io/api/v3#definition-Order
. 
Pleas let us know if we can help you in any other way
