### ISSUE TITLE
API v3 is not clear how to calculate Api-Content-Hash

### ISSUE THREAD

**Issue by andrewelkin** [Bittrex/bittrex.github.io#117]
API v3 states: 
Populate this header with a SHA512 hash of the request contents, Hex-encoded. If there are no request contents, populate this header with a SHA512 hash of an empty string.

Empty string works, but for a  request like this:
 ```https://api.bittrex.com/v3/deposits/closed?pageSize=10&previousPageToken=0d990dd2-4103-4d57-8e80-047e886537db```

  what exactly is "request contents"? It can be one of these:

* ?pageSize=10&previousPageToken=0d990dd2-4103-4d57-8e80-047e886537db
* pageSize=10&previousPageToken=0d990dd2-4103-4d57-8e80-047e886537db
* pageSize=10previousPageToken=0d990dd2-4103-4d57-8e80-047e886537db

or something else?

**Comment by cyrus19909** [comment]
hi @andrewelkin ,

For getting the closed deposits , your URL will look like https://api.bittrex.com/v3/deposits/closed?pageSize=10&previousPageToken=0d990dd2-4103-4d57-8e80-047e886537db where pageSize and previousPageToken will be the request parameters . in the Headers you will need to provide Api-key , Api-Signature , Api-Timestamp, and Api-Content-Hash .  This should give you list of all deposits before previousPageToken.  Please let us know if this helps and if not we can look into this further

**Comment by andrewelkin** [comment]
@cyrus19909 
Raj,   I know how my url should looks like of course :) . Just tell me what part of it is used for Api-Content-Hash calculation. What exactly you mean saying "request contents" ?  If you just  give an example it would help. thank you!

**Comment by cyrus19909** [comment]
Okay i see. Well in that case request-content would be your body parameters which you pass  for a request. If there are not body params you can pass the empty string as in the case of the above request . 
```var contentHash = CryptoJS.SHA512(content).toString(CryptoJS.enc.Hex);``` . Does that help ?
