### ISSUE TITLE
API v3 order description is a bit unclear/incomplete 

### ISSUE THREAD

**Issue by andrewelkin** [Bittrex/bittrex.github.io#118]
@cyrus19909  Raj,  can you please describe this order field 

```
---->   "proceeds": "number (double)",
```

In addition to fillQuantity I would like to know 
1) price of the order **OR**
2) total of the quote currency I payed  (I can calculate 2) from 1) and fillQuantity)
and finally
3) in what currency the commission is payed (I presume it is always quote currency, right?)

```
{
    "id": "string (uuid)",
    "marketSymbol": "string",
    "direction": "string",
    "type": "string",
    "quantity": "number (double)",
    "limit": "number (double)",
    "ceiling": "number (double)",
    "timeInForce": "string",
    "clientOrderId": "string (uuid)",
    "fillQuantity": "number (double)",
    "commission": "number (double)",
    "proceeds": "number (double)",
    "status": "string",
    "createdAt": "string (date-time)",
    "updatedAt": "string (date-time)",
    "closedAt": "string (date-time)"
  }
```

**Comment by bittrex-pete** [comment]
@andrewelkin The total quote currency paid for a buy order is proceeds + commission. For a sell order the quote currency received is proceeds – commission.  Commission is always represented in quote currency.

**Comment by cyrus19909** [comment]
@andrewelkin did that help answer your question ? If so can we close this issue ?

**Comment by andrewelkin** [comment]
Raj, thank you, and yes, please close the issue.

Regards,
Andy Elkin
