### ISSUE TITLE
API deposits sub-accounts

### ISSUE THREAD

**Issue by jarysardinha** [Bittrex/bittrex.github.io#119]
Is there a better way to track when a sub-account received an open deposit besides having to call the `deposits/{open/closed}` or `balances` endpoints for every single sub-account on a new request with their API header id? Currently, we have over 80K accounts and have to do *a lot* of requests to track that, could take hours since we have rate limit, therefore not scalable. It could be more simple to just have a single endpoint under the master account to see all the history from all subaccounts, work exactly like the `deposits` endpoints but with an extra query param or flag to also pull history from a certain sub-account or all of them. Could someone let me know if something similar is already ou there or if such a feature can be implemented in the future? Thanks.

**Comment by cyrus19909** [comment]
hi @jarysardinha ,

Are you a current partner with Bittrex ? If yes can you please tell us the name of the partner so that we can help you better. ?
