### ISSUE TITLE
Websocket uO `i` `IsOpen` is always null.

### ISSUE THREAD

**Issue by michaelwayman** [Bittrex/bittrex.github.io#12]
For the beta websocket after authenticating, and receiving an `uO` (AKA updateOrder) the value for `I` (AKA IsOpen) is always null.

Right now I can easily hack around by checking if there is a closed date, but it would be nice if the key IsOpen actually had the correct value.

**Comment by cyrus19909** [comment]
Closing the issue for now. Feel free to re open it if you are still facing the issue
