### ISSUE TITLE
API v3 Authentication in PHP

### ISSUE THREAD

**Issue by saikou999** [Bittrex/bittrex.github.io#124]
Hello,

I've tried to write code in php to be able to access v3 however I've failed. Do you have sample php codes that can help me through the Authentication?

* Mainly these bits
Api-Key
Api-Timestamp
Api-Content-Hash
Api-Signature

Thanks,

**Comment by cyrus19909** [comment]
hi @saikou999 ,

Sorry that you have been facing issues on that end. You can find below code snippets for the above parameters .

Content-hash
`    protected static function requestcontentHash($content)
    {
        if ($content === null) {
            return 'The content cannot be null';
        } else {
            return hash('sha512', $content);
        }
    }`
Timestamp 
`    protected static function requestTimestamp()
    {
        list($usec, $sec) = explode(' ', microtime());
        return (int) ((int) $sec * 1000 + (float) $usec * 1000);
    }`

Presignature 
`    protected static function requestPreSignature(
        $timeStamp,
        $uri,
        $method,
        $contentHash
    ) {
        return $timeStamp . $uri . strtoupper($method) . $contentHash;
    }`
Signature 
`    protected function requestSignature(string $preSignature)
    {
        if ($this->apiSecret === null) {
            return 'The api secret cannot be null';
        } else {
            return hash_hmac('sha512', $preSignature, $this->apiSecret);
        }
    }`

When making a request you can use the following to add headers in thew request
`            $options = [
                'Api-Timestamp' => $timeStamp,
                'Api-Key' => $this->apiKey,
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
                'Api-Signature' => $signature,
                'Api-Content-Hash' => $contentHash
            ];`

Hopefully the above helps. Please let us know if you run into any more issues

**Comment by cyrus19909** [comment]
@saikou999 did that help with your authentication issue

**Comment by bugsoff** [comment]
@saikou999, look at this:

```
<?php
/*	Make an order
**	>>array	
**		market		market pair 			ex.: 'ETH-BTC'
**		side		sell or buy order		ex.: 'BUY'
**		type		limit, market etc.		ex.: 'LIMIT'
**		quantity	quantity of accets		ex.: 100.12345678
**		price		deal price 			ex.: 0.00015698
**	
**	<< 	order_id 	if order is placed
**		(false)		if an error occurred
**	
*/

function apiv3_request_order($arg)
{
	const apikey='qwertyuiop123456789';
	const secretkey='qwertyuiop123456789';
	$logfilename ="bittrex-request-err".date("Ym").".log";

	$uri='https://api.bittrex.com/v3/orders';

/* Make new order parameters */
	$new_order = json_encode(
		[ 	"marketSymbol" => strtoupper($arg['market']),
		 	"direction" => strtoupper($arg['side']),
		 	"type" => strtoupper($arg['type']),
		 	"quantity" => (float)$arg['quantity'],
		 	"limit" => (float)$arg['price'],
		 	"timeInForce" => "GOOD_TIL_CANCELLED",
			"useAwards" => true
		]);

/* API authentication */
	$api_timestamp = time()*1000+rand(0,999);
	$api_content_hash = hash('sha512', $new_order);
	$api_signature = hash_hmac('sha512', $api_timestamp.$uri."POST".$api_content_hash, secretkey); 

	$header =[	"Api-Key: ".apikey, 
			"Api-Timestamp: $api_timestamp", 
			"Api-Content-Hash: $api_content_hash", 
			"Api-Signature: $api_signature", 
			"Accept: application/json",
			"Content-Type: application/json", 
			"Content-Length: ".strlen($new_order)],

/* Make request */	
	$ch =curl_init($uri);
	curl_setopt_array($ch, [CURLOPT_RETURNTRANSFER=>true, CURLOPT_HTTPHEADER=>$header, CURLOPT_POSTFIELDS=>$new_order]);
	$result = curl_exec($ch);	

/* Result */	
	if ($result!==false): 			// http request is successful 
		$result = json_decode($result,true);
		$http_code = curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
		if ($http_code!=201) file_put_contents($logfilename, date("Y-m-d H:i:s").PHP_EOL.">>>> $new_order".PHP_EOL."<<<< $result".PHP_EOL.PHP_EOL, FILE_APPEND);		
	else:					// connection error
		$error = curl_error($ch);
		file_put_contents($logfilename, date("Y-m-d H:i:s").PHP_EOL."Connection to URI: $uri".PHP_EOL."Error: $error".PHP_EOL.PHP_EOL, FILE_APPEND);				
	endif;
			
	curl_close($ch);
	return $result['id']??false;
}

?>
```
