### ISSUE TITLE
 {"code":"INVALID_TRAILING_STOP"}

### ISSUE THREAD

**Issue by Marcusbaker1** [Bittrex/bittrex.github.io#127]
Hi! 

I've been trying to set a trailing stop, and believe I have the minimal payload according to the API documentation. 

Seems that no matter how I try this, I keep getting INVALID_TRAILING_STOP when I attempt to place the order.

My payload is the following - what am I missing!???  
{
"marketSymbol":"BTC-USD",
"operand":"LTE",
"orderToCreate":{
	"marketSymbol":"BTC-USD",
	"direction":"SELL",
	"type":"MARKET",
	"quantity":x.xxxxxxxxxx,
	"timeInForce":"IMMEDIATE_OR_CANCEL",
	"useAwards":false
	},
"trailingStopPercent":3.0
}

**Comment by cyrus19909** [comment]
Hi @Marcusbaker1 ,

I see you are using 3.0 as `trailingStopPercent` . Can you try that with `0.03` instead ? 
Sorry that it was not clear in the documentation, we will add that for more user clarity ,

**Comment by Marcusbaker1** [comment]
Hey thank you so much for the reply, This drove me crazy for a couple of days, but that did it! 
It's working. Thank you again!!!
