### ISSUE TITLE
problem with Api-Content-Hash

### ISSUE THREAD

**Issue by antonioandara** [Bittrex/bittrex.github.io#130]
I'm having trouble passing the body parameters for the signed requests in python. I wrote a generic funtion to sign requests:

```
def signedRequest(method, path, params):

    if "key" not in APIid or "secret" not in APIid:
        raise ValueError("Api key and secret must be set")

    secret = bytes(APIid["secret"].encode("utf-8"))
    query = urlencode(sorted(params.items()))
    content_encoded = hashlib.sha512(query.encode())
    content_hash = content_encoded.hexdigest()
    fullpath = ENDPOINT + path
    timestamp = format(int(time.time() * 1000))
    presign = timestamp + fullpath + method + content_hash + ''
    apisignature = hmac.new(secret, presign.encode("utf-8"), hashlib.sha512).hexdigest()

    resp = requests.request(method, fullpath, headers={
                                "Api-Key": APIid['key'],
                                'Api-Timestamp': timestamp,
                                'Api-Content-Hash': content_hash,
                                'Api-Signature': apisignature,
                                    }
                            )
    data = resp.json()

    if "msg" in data:
        logging.error(data['msg'])
    return data
```

then if I make the following request without passing any body I get a proper response:

`data = signedRequest('GET', "/deposits/closed", {})`

but if I try to pass any parameters like {'currencySymbol':'BTC'} 

`data = signedRequest('GET', "/deposits/closed", {'currencySymbol':'BTC'})`

it gives an INVALID_CONTENT_HASH code. So there's an error in the way I'm encoding the content of the request. anyone can help me figure this out?

**Comment by cyrus19909** [comment]
Hi @antonioandara ,

Sorry to hear that you are facing the above issue. What i would recommend is something like following 

```  parsedContent = (
            (bytes(json.dumps(kwargs["body"]), "utf-8")) if kwargs else "".encode()
        )
```

then you can pass your body parameters as a json blob. If it doesnt have a body , it will encode an empty string as you can see above. 

Once you have the parse content , you can use the following ``` hashlib.sha512(content).hexdigest()
```
to get the content hash. Let me know if the above help you with your issue.

**Comment by antonioandara** [comment]
Hi Raj, thanks for the quick replly. I've been playing around with the lines you sent

`
(bytes(json.dumps(kwargs["body"]), "utf-8")) if kwargs else "".encode()
hashlib.sha512(content).hexdigest()
`

but I keep getting the same result, I'm passing the parameters as json and it works fine for the empty  string but if I make a request with a body e.g ({"currencySymbol":"BTC"} ) it still shows  INVALID_CONTENT_HASH.

**Comment by cyrus19909** [comment]
Sorry to hear that your problem still persists . If you can send me the fill request with the headers (without api key) that would help me look at where you can be running into the issue.

**Comment by antonioandara** [comment]
passing a dummy content like:
`content={"currencySymbol":"BTC"}`
returns this hash:
18aa13a42b5efe3c45b37050626f23fcc4f3b4acf5e479f2f50212722cdcd80baa0ba6ddf8dcbd0f1b88008aaf9ec33874e4be9ab6ec2dece611c2dbdca87560

the filled request command with a dummy timestamp looks like this:
`
    resp = requests.request('GET', 'https://api.bittrex.com/v3/deposits/closed', headers={
                                'Api-Key': '',
                                'Api-Timestamp': '1590516016180',
                                'Api-Content-Hash': '18aa13a42b5efe3c45b37050626f23fcc4f3b4acf5e479f2f50212722cdcd80baa0ba6ddf8dcbd0f1b88008aaf9ec33874e4be9ab6ec2dece611c2dbdca87560',
                                'Api-Signature': '',
                                    }
                            )
`

this last part has been working very well so far, I think the main issue might be the body content, maybe I'm using the wrong format?

**Comment by cyrus19909** [comment]
Okay i see your issue there. So for your  `deposits/closed` , `currencySymbol` is a request parameter and not a part of the body. So your request would be `deposits/closed?currencySymbol=BTC` with body as an empty string. and your content hash with an empty string should look like ```cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e```

For more information you can check https://bittrex.github.io/api/v3#operation--deposits-closed-get

Please let us know if that solved the above issue

**Comment by antonioandara** [comment]
That did it, I was confused about that (thought I had to populate the body too). thank you so much for your help I can continue my project!

**Comment by cyrus19909** [comment]
Great , glad it worked out
