### ISSUE TITLE
batch/bulk orders and cancels

### ISSUE THREAD

**Issue by codemonkeyno1** [Bittrex/bittrex.github.io#133]
Hi, I read that there is a new feature for batch/bulk orders in Bittrex v3.  How do I use this feature to send more than one order/cancel at a time (on different trading pairs)?

As a related issue, how is it possible to do market making on 100+ symbols with quote updates every second on each market when the rate limit is 60 calls/minute?

**Comment by cyrus19909** [comment]
Hi,

We don't have a publicly available batch feature at this time, but we plan to have one in the future. With respect to market making, most of the market makers who do business on our platform have corporate accounts with higher limits. 
That being said, if you're using the websocket, you would have no reason to poll for market data so the only API traffic you would be generating is order placement and cancellation. We don't typically throttle those activities unless we see a pattern that looks abusive. The call limit warning is mostly aimed at people hammer the REST API for order status and the like when they should really be using the websocket.

Please let us know if we can help you in any other way
