### ISSUE TITLE
QueryExchangeState fill Rate labeled Price

### ISSUE THREAD

**Issue by gliderman** [Bittrex/bittrex.github.io#14]
There is a mismatch with the naming convention used to report the state and deltas of an orderbook.  Elsewhere on Bittrex (I believe in the REST API), `Price` and `Total` mean the same thing, but when getting an exchange state `Price` is actually reporting the `Rate`.

A minor difference as well is `Id` vs. `FillId`.

This was tested using the beta websocket while we wait for updates to be pushed to the main websocket.

QueryExchangeState with actual values:
```
    Fills: 
    [
        {
            Id        : int,
            TimeStamp : date,
            Quantity  : decimal, (3.01949836)
            Price     : decimal, (0.08107000)
            Total     : decimal, (0.24479073)
            FillType  : string,
            OrderType : string
        }
    ]
```
And for comparison, the Market Delta (uE):
```
    Fills: 
    [
        {
            FillId    : int,
            OrderType : string,
            Rate      : decimal,
            Quantity  : decimal,
            TimeStamp : date
        }
    ]
```

**Comment by ayy1337** [comment]
FWIW I find the REST api's referring to the Total as 'Price' to be very confusing indeed.

**Comment by cyrus19909** [comment]
This issue has been fixed. Feel free to open the issue again if similar issue is observed .
