### ISSUE TITLE
I have issues with Bittrex API v3 in php

### ISSUE THREAD

**Issue by nikolasshev** [Bittrex/bittrex.github.io#147]
Hello! I have issues with Bittrex API v3 in php. When I use bittrex API v1.1 in php to get balances (and other authenticated requests) - all working fine. But I have problems with Bittrex API v3.

**For API v1.1 I use this code:**

```
$nonce = time()*1000;
$url='https://bittrex.com/api/v1.1/account/getbalances?apikey='.$apikey.'&nonce='.$nonce;
$sign=hash_hmac('sha512',$url,$apisecret);
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('apisign:'.$sign));
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt ($ch, CURLOPT_SSL_VERIFYPEER, true); 
$execResult = curl_exec($ch);
curl_close($ch);
echo $execResult;
```

**I use this code for API v3:**

```
$timestamp = time()*1000;
$url = "https://api.bittrex.com/v3/balances";
$method = "GET";
$content = "";
$subaccountId = "";
$contentHash = hash('sha512', $content);
$preSign = $timestamp . $url . $method . $contentHash . $subaccountId;
$signature = hash_hmac('sha512', $preSign, $apisecret);

$headers = array (
	'Api-Key' => $apikey,
	'Api-Timestamp' => $timestamp,
	'Api-Content-Hash' => $contentHash,
	'Api-Signature' => $signature,
	'Content-Type' => "application/json"
);

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);
$execResult = curl_exec($ch);
curl_close($ch);
echo $execResult;
```

I am getting this: {"code":"UNAUTHORIZED"}.

What I am doing wrong? How to make it work in php with a simple curl_setopt method?

**Comment by cyrus19909** [comment]
hi @nikolasshev ,

Sorry to hear that you are running into this issue. Can you please try encoding your content something like ```$contentHash = hash('sha512', json_encode($content));```

If that does not help can you send the value of the content hash you are getting so that we can verify if something else is missing .

thanks

**Comment by nikolasshev** [comment]
Unfortunately this did not help me.

When I use 
`$contentHash = hash('sha512', $content);`

content hash is: 

cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e

When I use 
`$contentHash = hash('sha512', json_encode($content));`

content hash is:

64d24560970ca14d349bea0e7d2526d4754bf3283568ab4dd602bd79eb454dc3657d5bb6f9a30c90ea98d9600ebd0fb45d582f4cae3f8e3c50b0e8fb18059892

When I need to get balances I must set $content as empty line ($content = "";), right?

**Comment by cyrus19909** [comment]
hi,

From the looks of it you are getting the correct content-hash after encoding the json which is ```cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e``` . 

Your pre-signature should look like ```{timestamp}https://api.bittrex.com/v3/balancesGETcf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
```
this can be referenced here https://bittrex.github.io/api/v3#topic-Authentication

Please let me know if this helps

**Comment by nikolasshev** [comment]
I have pre-signature:

1593034659000https://api.bittrex.com/v3/balancesGETcf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e

looks like correct pre-signature

but this did not help me.

**Comment by cyrus19909** [comment]
hmm can you try 
`
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.bittrex.com/v3/balances",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "Accept: application/json",
    "Api-Key: <key>",
    "Api-Signature: <sig>",
    "Api-Timestamp: <timestamp>",
    "Api-Content-Hash: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;

`

**Comment by nikolasshev** [comment]
Thank you!!! Your last code is working and now I can get my balances. But I can't to create a new order.

The problem was in this section of code:

**incorrect code:**

```
$headers = array (
	'Api-Key' => $apikey,
	'Api-Timestamp' => $timestamp,
	'Api-Content-Hash' => $contentHash,
	'Api-Signature' => $signature,
	'Content-Type' => "application/json"
);
```

**correct code:**

```
$headers = array(
"Accept: application/json",
"Content-Type: application/json",
"Api-Key: ".$apikey."",
"Api-Signature: ".$signature."",
"Api-Timestamp: ".$timestamp."",
"Api-Content-Hash: ".$contentHash.""
);
```

my fully working code is:

```
$timestamp = time()*1000;
$url = "https://api.bittrex.com/v3/balances";
$method = "GET";
$content = "";
$subaccountId = "";
$contentHash = hash('sha512', $content);
$preSign = $timestamp . $url . $method . $contentHash . $subaccountId;
$signature = hash_hmac('sha512', $preSign, $apisecret);

$headers = array(
"Accept: application/json",
"Content-Type: application/json",
"Api-Key: ".$apikey."",
"Api-Signature: ".$signature."",
"Api-Timestamp: ".$timestamp."",
"Api-Content-Hash: ".$contentHash.""
);

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);
$execResult = curl_exec($ch);
curl_close($ch);
echo $execResult;
```



**But I still have issues when I try to create a new order.**

For example I need to create an order with these properties:

marketSymbol: USDT-BTC
direction: BUY
type: LIMIT
quantity: 0.00276225
limit: 7226.00306482
timeInForce: GOOD_TIL_CANCELLED

**When I use this code:**

```
$timestamp = time()*1000;
$url = "https://api.bittrex.com/v3/orders";
$method = "POST";

$content = array(
"marketSymbol: USDT-BTC",
"direction: BUY",
"type: LIMIT",
"quantity: 0.00276225",
"limit: 7226.00306482",
"timeInForce: GOOD_TIL_CANCELLED"
);

$subaccountId = "";
$contentHash = hash('sha512', json_encode($content));
$preSign = $timestamp . $url . $method . $contentHash . $subaccountId;
$signature = hash_hmac('sha512', $preSign, $apisecret);

$headers = array(
"Accept: application/json",
"Content-Type: application/json",
"Api-Key: ".$apikey."",
"Api-Signature: ".$signature."",
"Api-Timestamp: ".$timestamp."",
"Api-Content-Hash: ".$contentHash.""
);

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
$execResult = curl_exec($ch);
curl_close($ch);

echo $execResult;
```

I am getting this:

{"code":"INVALID_CONTENT_HASH"}

**When I use this code:**

```
$timestamp = time()*1000;
$url = "https://api.bittrex.com/v3/orders";
$method = "POST";

$content = 'marketSymbol=USDT-BTC&direction=BUY&type=LIMIT&quantity=0.00276225&limit=7226.00306482&timeInForce=GOOD_TIL_CANCELLED';

$subaccountId = "";
$contentHash = hash('sha512', $content);
$preSign = $timestamp . $url . $method . $contentHash . $subaccountId;
$signature = hash_hmac('sha512', $preSign, $apisecret);

$headers = array(
"Accept: application/json",
"Content-Type: application/json",
"Api-Key: ".$apikey."",
"Api-Signature: ".$signature."",
"Api-Timestamp: ".$timestamp."",
"Api-Content-Hash: ".$contentHash.""
);

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
$execResult = curl_exec($ch);
curl_close($ch);

echo $execResult;
```

I am getting this:

{"code":"BAD_REQUEST","detail":"Refer to the data field for specific field validation failures or extra fields in the body that were rejected.","data":{"newOrder":["Unexpected character encountered while parsing value: m. Path '', line 0, position 0."]}}

What I am doing wrong? How to make it work to create a new order?

**Comment by cyrus19909** [comment]
Can you try something like

 `<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.bittrex.com/v3/orders",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS =>"{\r\n  \"marketSymbol\": \"XLM-BTC\",\r\n  \"direction\": \"BUY\",\r\n  \"type\": \"LIMIT\",\r\n  \"quantity\": \"50\",\r\n  \"limit\": \"0.03213592\",\r\n  \"timeInForce\": \"GOOD_TIL_CANCELLED\",\r\n  \"expiresAt\": \"\",\r\n  \"clientOrderId\": \"\"\r\n}",
  CURLOPT_HTTPHEADER => array(
    "Accept: application/json",
    "Api-Key: <api-key>",
    "Api-Signature: <sig>",
    "Api-Timestamp: 1593105160897",
    "Api-Content-Hash: <content-hash>",
    "Content-Type: application/json"
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
`
and please use `$contentHash = hash('sha512', json_encode($content));`

Let me know if that helps

**Comment by nikolasshev** [comment]
What should I indicate in the variable $content?

**Comment by cyrus19909** [comment]
the content will be the body of the request . in the above example its already encoded in the CURLOPT_POSTFIELDS  field .

**Comment by nikolasshev** [comment]
Finally I found the correct code to create a new order. It is:

```
$timestamp = time()*1000;
$url = "https://api.bittrex.com/v3/orders";
$method = "POST";

$content = '{
  "marketSymbol": "BTC-USDT",
  "direction": "BUY",
  "type": "LIMIT",
  "quantity": "0.00276225",
  "limit": "7226.00306482",
  "timeInForce": "GOOD_TIL_CANCELLED"
}';

$subaccountId = "";
$contentHash = hash('sha512', $content);
$preSign = $timestamp . $url . $method . $contentHash . $subaccountId;
$signature = hash_hmac('sha512', $preSign, $apisecret);

$headers = array(
"Accept: application/json",
"Content-Type: application/json",
"Api-Key: ".$apikey."",
"Api-Signature: ".$signature."",
"Api-Timestamp: ".$timestamp."",
"Api-Content-Hash: ".$contentHash.""
);

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
$execResult = curl_exec($ch);
curl_close($ch);

echo $execResult;
```

Thank you so much for your help!

**Comment by cyrus19909** [comment]
awesome! glad that worked . Let us know if you need any more help/guidance on that .
