### ISSUE TITLE
Any functioning code example for v3 websocket?

### ISSUE THREAD

**Issue by wdjpl** [Bittrex/bittrex.github.io#150]
I'm finding the docs for v3 websocket difficult to follow. Is there a basic, functioning code, in any programming language, that you can share for your v3 websocket? I'm hopeful that even a basic version can help.

The existing examples in this github repo are from 2 years ago and not for v3. Simple switching the endpoint and hub proxy name did not convert the existing examples into functioning ones for v3.

**Comment by cyrus19909** [comment]
hi @wdjpl there are some examples in the documentation https://bittrex.github.io/api/v3#topic-Websocket-Overview . Please let us know if that helps .

If not we can try providing you more examples.

**Comment by wdjpl** [comment]
Hi @cyrus19909,

By example, can it be a functioning (even if barebone) code rather than the snippets found throughout the documentation? Unfortunately, the snippets of code in the documentation are part of what I found difficult to follow.

For example, the subscribing section lists a function definition for subscription:
```cs
public async Task<List<SocketResponse>> Subscribe(string[] channels)
{
    return await _hubProxy.Invoke<List<SocketResponse>>("Subscribe", (object)channels);
}
```
I am unable to figure out what I should actually pass in for the parameter ```string[] channels``` for the function ```Subscribe```. Is it "ticker_ETH-BTC" (https://bittrex.github.io/api/v3#method-Ticker) or  '{"H":"c3","M":"Subscribe","A":[["heartbeat","ticker_BTC-USD"]],"I":1}' (https://bittrex.github.io/api/v3#method-Subscribe).

If at all possible, I'd really like even a barebone, functioning example. I'm hoping that seeing a concrete example will help me understand what the docs are trying to tell me.

**Comment by Tarmek15** [comment]
Hi @cyrus19909,

> If not we can try providing you more examples.

Yes, wee need an example, PLZ, like it was "bittrex.github.io-master\samples\WebsocketSample.cs".

I can't find SocketResponse type/class... Can't use :((((

**Comment by wdjpl** [comment]
Hi @cyrus19909 ,

I wanted to check in since it has been over a month and there's still no response from Bittrex.

Is the lack response because the Bittrex have forgotten about this thread? Or perhaps my request was too difficult or absurd? I had assumed that providing a functioning example would be a simple task, but maybe I was mistaken? If so, I apologize. Can you tell us what we can do to help the Bittrex team produce a functioning example? I would really like to be able to work with v3 before v1's EOL.

**Comment by bittrex-pete** [comment]
Hi @wdjpl sorry for the delay. You can find some simple examples here: https://bittrex.github.io/api/v3#topic-Example-Socket-Clients

**Comment by wdjpl** [comment]
@bittrex-pete This is incredible, thanks!
