### ISSUE TITLE
There was an error invoking Hub method 'c3.Subscribe'  in v3 Websocket

### ISSUE THREAD

**Issue by anzaiteacher** [Bittrex/bittrex.github.io#151]
Hello,
I am making an API to get an orderbook in Golang(ver go1.8 darwin/amd64).
However, I cannot subscribe.

I'm using https://github.com/darkdarkdragon/signalr package.

Error:
`
2020/07/13 15:45:43 { [] 0 1 There was an error invoking Hub method 'c3.Subscribe'. [] [] [] []}
`

Code:
```
import (
	"log"

	darkdarkdragon "github.com/darkdarkdragon/signalr"
	"github.com/darkdarkdragon/signalr/hubs"
)
func main() {
    // Prepare a SignalR client.
    c := darkdarkdragon.New(
	"socket-v3.bittrex.com",
	"1.5",
	"/signalr",
	`[{"name":"c3"}]`,
	nil,
    )

    // Define message and error handlers.
    msgHandler := func(msg darkdarkdragon.Message) {
	log.Println(msg)
    }
    panicIfErr := func(err error) {
	if err != nil {
		log.Panic(err)
	}
    }

    // Start the connection. 
    err := c.Run(msgHandler, panicIfErr)
    panicIfErr(err)

    // Subscribe to the USDT-BTC feed.
    err = c.Send(hubs.ClientMsg{
	H: "c3",
	M: "Subscribe",
	A: []interface{}{"orderbook_BTC-USD_25"},
	I: 1,
    })
    panicIfErr(err)

    // Wait indefinitely. 
    select {}
}
```

Can you please tell me how to fix the error?
Thanks,

**Comment by alexeykaravan** [comment]
I have the same problem with Subscribe method. (Golang, https://github.com/thebotguys/signalr)
Authenticate and IsAuthenticated - working fine.

`There was an error invoking Hub method 'c3.Subscribe'`

**Comment by alexeykaravan** [comment]
@anzaiteacher 
you passing A: []interface{}{"orderbook_BTC-USD_25"}

but they are waiting for A: [][]interface
example:
{"H":"c3","M":"Subscribe","A":[["ticker_BTC-USD"]],"I":1}

**Comment by anzaiteacher** [comment]
@alexeykaravan 
Thank you.

I made the following changes.
```
err = c.Send(hubs.ClientMsg{
	H: "c3",
	M: "Subscribe",
	A: [][]interface{}{{"orderbook_BTC-USD_25"}},
	I: 1,
})
```

Then I got an error.
`panic: json unmarshal failed: json: cannot unmarshal string into Go struct field ClientMsg.A of type []interface {}`

**Comment by alexeykaravan** [comment]
@anzaiteacher 

`err = c.Send(hubs.ClientMsg{
	H: "c3",
	M: "Subscribe",
	A: []interface{}{[]interface{}{"orderbook_BTC-USD_25"}},
	I: 1,
})`


try this

**Comment by anzaiteacher** [comment]
@alexeykaravan 
Thanks, alexeykaravan!!
I can passing `A: []interface{}{"orderbook_BTC-USD_25"}`

Response:
```
{d-4C9E619B-B,0|Bqr,0|Bqs,2|ZI,3E56 [{%!s(int=0) C3 orderBook [jY/NDoIwEAbfZc+12a22tByVN0BPhkORJhJ+FCgHQnh3qzFGEg9+t01mJtkZGttXzqdTk99qiGF/PGxOaQIMCnf3V4iFZDC4bnTtxYWLjDKCQV4Wiau9HSA+z9CNtvWln4KPnMxrKiR664MDRAIlx22Ez8HC1sY3SEZzJPUb5CQ1YkSrNGnNd0L/kY4E10K+wYyBHarPD9nyAA==] %!s(*json.RawMessage=<nil>)}] %!s(int=0)       }
```

Are the contents of the order book a token?
I expected it to be bit and ask.

**Comment by alexeykaravan** [comment]
Messages sent on the v3 socket are gzipped and must be decompressed prior to being used.
https://bittrex.github.io/api/v3#topic-Handling-Messages

**Comment by Tarmek15** [comment]
Can anyone tell me what is <SocketResponse> type/class?
I cann not find it!!!

**Comment by anzaiteacher** [comment]
@alexeykaravan 
Thank you!!
It was done after decompressing!

```
g := msg.M[0].A[0].(string)
dec, e := base64.StdEncoding.DecodeString(g)
if e != nil {
	log.Print(e)
	return
}
r := flate.NewReader(bytes.NewReader(dec))
result, e := ioutil.ReadAll(r)
if e != nil {
	log.Print(e)
	return
}
log.Printf("%v¥n", string(result))
```
