### ISSUE TITLE
v1.1 GET /account/getorderhistory returns no data

### ISSUE THREAD

**Issue by LefterisJP** [Bittrex/bittrex.github.io#154]
Our users [reported](https://github.com/rotki/rotki/issues/1234) that they can no longer see any of their historical trades in Bittrex.

We are using the v1.1. API and the `GET /account/getorderhistory` used to work fine, but it now returns no trades at all. I know you are deprecating the v1.1. API but returning no data before the given date to upgrade (30/09/2020) is not nice as you are breaking all the applications that rely on your API.

We are going to upgrade to v3 faster now. As it seems that the v3 equivalent call works fine and does return the trades.

Just letting you know with this issue that v1.1. `GET /account/getorderhistory` no longer works

**Comment by cyrus19909** [comment]
hi @LefterisJP 

Sorry that you are facing the issue. The probable reason you are seeing an empty list of orderhistory for `getorderhistory` is that we dont return any order on v1.1 past 30 days .

With v3, there is no restrictions like that. Please let us know if that helps with your question above and let us know if we can help you in any other way

**Comment by LefterisJP** [comment]
> With v3, there is no restrictions like that. Please let us know if that helps with your question above and let us know if we can help you in any other way

But that is a recent restriction on v1.1. Because I have been querying the endpoint for a long time and was always getting my bittrex trades from 2017 until a few months ago.

**Comment by cyrus19909** [comment]
@LefterisJP can you give us time when you started seeing this restriction?

**Comment by LefterisJP** [comment]
No sorry. Only that it was a few months ago.

We solved this in Rotki by simply switching to the v3 API. Now everything is fine. You can close the issue as far as I am concerned since v1.1 is going away very soon anyway.

**Comment by cyrus19909** [comment]
thank you
