### ISSUE TITLE
Where is SocketResponse type/class?

### ISSUE THREAD

**Issue by Tarmek15** [Bittrex/bittrex.github.io#155]
Can't find "<" SocketResponse ">"  class description in API docs.

**Comment by cyrus19909** [comment]
@Tarmek15 https://bittrex.github.io/api/v3#definition-SocketResponse

**Comment by cyrus19909** [comment]
The socket response here is ```    public class SocketResponse
    {
        public bool Success { get; set; }
        public string ErrorCode { get; set; }
    }```
