### ISSUE TITLE
API V3 Auth headers in GET requests

### ISSUE THREAD

**Issue by skyfall174** [Bittrex/bittrex.github.io#156]
Hi, I implement a JS client of your client. I do not understand wich content-hash header I should pass if I have GET request (with no body/content)

At Docs there are:

> Populate this header with a SHA512 hash of the request contents, Hex-encoded. If there are no request contents, populate this header with a SHA512 hash of an empty string.

Ok but a pre-sign example of GET contains nonempty content HASH. (but get request always have empty content)

How I should fill Headers when content is empty?

Thank you.

**Comment by LeeJaeWonLJW** [comment]
Just hashing empty string like "".

example)
`CryptoJS.SHA512("").toString(CryptoJS.enc.Hex);`

It worked for me.

**Comment by cyrus19909** [comment]
@skyfall174  yes you need to pass an empty string as above. Please let us know if that worked
