### ISSUE TITLE
Can't correctly subscribe to web socket

### ISSUE THREAD

**Issue by dmitrybakumenko** [Bittrex/bittrex.github.io#157]
Hello! I am investigated whole documentation of your API v3. My task is very simple, I have to receive trade events via using web socket. Please help me to understand what I do wrong. Best regards!

- After connection to web socket I try to subscribe to trade_BTC-USDT
`updates = proxy.invoke("Subscribe", "trade_BTC-USDT");`

- And after this I receive a message
`{"I":"0","E":"There was an error invoking Hub method 'c3.Subscribe'."}`

**Comment by cyrus19909** [comment]
@dmitrybakumenko can you try something like 
```_hubProxy.Invoke<List<SocketResponse>>("Subscribe", (object)channels);```


where the class for socketResponse is
 ```    public class SocketResponse
    {
        public bool Success { get; set; }
        public string ErrorCode { get; set; }
    }```

**Comment by sebbes** [comment]
I have the exact same issue. I tried @cyrus19909 proposed solution, still get ```{"I":"0","E":"There was an error invoking Hub method 'c3.Subscribe'."}```

**Comment by bittrex-pete** [comment]
Hi @dmitrybakumenko and @sebbes - There are many things that could possibly be wrong. We recently published some simple examples for how to do this in a few different languages. I'd suggest comparing what you're doing to one of these to look for the problem: https://bittrex.github.io/api/v3#topic-Example-Socket-Clients

**Comment by CryptoArbitrage9** [comment]
I have a similar problem! Connection and authorization are in progress, but when trying to subscribe I get the following errors: heartbeat: UNKNOWN_ERROR
trade_BTC-USD: UNKNOWN_ERROR
balance: UNAUTHORIZED_USER

{"R":[{"Success":false,"ErrorCode":"UNKNOWN_ERROR"},{"Success":false,"ErrorCode":"UNKNOWN_ERROR"},{"Success":false,"ErrorCode":"UNAUTHORIZED_USER"}],"I":"1"}

The code is completely identical to your example in c #

static async Task Subscribe(SocketClient client)
        {
            client.SetHeartbeatHandler(() => Console.WriteLine("<heartbeat>"));
            client.AddMessageHandler<object>("trade", msg => Console.WriteLine($"Trade: {msg}"));
            client.AddMessageHandler<object>("balance", msg => Console.WriteLine($"Balance: {msg}"));

            var channels = new string[] {
                "heartbeat",
                "trade_BTC-USD",
                "balance" };
           
            
            var response = await client.Subscribe(channels);
            for (int i = 0; i < channels.Length; i++)
            {
                Console.WriteLine(response[i].Success ? $"{channels[i]}: Success" : $"{channels[i]}: {response[i].ErrorCode}");
            }
        }

 public async Task<List<SocketResponse>> Subscribe(string[] channels)
        {
            return await _hubProxy.Invoke<List<SocketResponse>>("Subscribe", (object)channels);
        }

**Comment by CryptoArbitrage9** [comment]
`  public async Task<List<SocketResponse>> Subscribe(string[] channels)
        {
            return await _hubProxy.Invoke<List<SocketResponse>>("Subscribe", (object)channels);
        }`
