### ISSUE TITLE
Cancel Order Not working

### ISSUE THREAD

**Issue by stevenj1979** [Bittrex/bittrex.github.io#158]
I'm testing v3 of the API with my PHP code.   Buying and Selling seems to work fine,  but I'm having an issue with cancelling an order: 

    `$timestamp = time()*1000;
      $url = "https://api.bittrex.com/v3/orders/{".$uuid."}";
      echo "<BR>".$url;
      $method = "DELETE";
      echo "<BR>".$method;
      $content = '';
      $subaccountId = "";
      $contentHash = hash('sha512', $content);
      $preSign = $timestamp . $url . $method . $contentHash . $subaccountId;
      $signature = hash_hmac('sha512', $preSign, $apisecret);

      $headers = array(
      "Accept: application/json",
      "Content-Type: application/json",
      "Api-Key: ".$apikey."",
      "Api-Signature: ".$signature."",
      "Api-Timestamp: ".$timestamp."",
      "Api-Content-Hash: ".$contentHash.""
      );

      $ch = curl_init($url);
      curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
      curl_setopt($ch, CURLOPT_HEADER, FALSE);
      curl_setopt($ch, CURLOPT_POST, TRUE);
      curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
      $execResult = curl_exec($ch);`

Can you see any issue from the code?  Thanks Steven

**Comment by cyrus19909** [comment]
Can you please provide the error you are facing . Also can you try
 `<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.bittrex.com/v3/orders/{orderId}",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "DELETE",
  CURLOPT_HTTPHEADER => array(
    "Accept: application/json",
    "Api-Key: <val>",
    "Api-Signature: <val>",
    "Api-Timestamp: <val>",
    "Api-Content-Hash: <val>"
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
`

**Comment by stevenj1979** [comment]
I dont get any error,  just no response.  Everything looks fine to me.  I'm reusing the code from the buy function (which works perfectly). 

I will try your code and let you know if it works.

Thank you

**Comment by stevenj1979** [comment]
That worked, thank you so much.
