### ISSUE TITLE
Get Balances Ex

### ISSUE THREAD

**Issue by Goopher** [Bittrex/bittrex.github.io#159]
Hi dear devs!

First of all, great work on the V3 api. 

Does the V3 api also have an endpoint similar to:

https://global.bittrex.com/api/v2.0/auth/balance/GetBalancesEx ?

I like the endpoint since it returns all balances with their markets, and currency information. I would like to use this in my own project as well.

**Comment by cyrus19909** [comment]
@Goopher Glad you are linking the v3 api 

Unfortunately for the time being we dont have an endpoint which returns balances with their markets but we will add that as a feature request .

Thank you for the patience .
