### ISSUE TITLE
Why does it reponse INVALID_CONTENT_HASH?

### ISSUE THREAD

**Issue by arphone2017** [Bittrex/bittrex.github.io#160]
Dear all,

When I use the api such as 'v3/orders/open', it always response the code INVALID_CONTENT_HASH. 

The API document says following:
Populate this header with a SHA512 hash of the request contents, Hex-encoded. If there are no request contents, populate this header with a SHA512 hash of an empty string.

Could you tell me what is the request content for this api? Please give me some examples which in python3. Thanks.

Best regards,
Richey.

**Comment by Serpens66** [comment]
you have to send the payload as json.
And the "request content" is this json content. In case of orders/open it would be:
```
payload = {"marketSymbol":"BTC-USD"}
content = json.dumps(payload)
contenthash = hashlib.sha512(content.encode()).hexdigest()
```

if payload is empty (eg for all openorders) the content should be an empty string.

**Comment by arphone2017** [comment]
> content = json.dumps(payload)

I send the payload as json, and the code is same to you, but it also responds {"code":"INVALID_CONTENT_HASH"}. What's wrong?

Could you provide me a complete demo code in Python3 which can be run. Thank you very much!

Best regards,
Richey.

**Comment by Serpens66** [comment]
`import requests
    import time
    import hmac
    import hashlib
    import json
    url = "https://api.bittrex.com/v3/orders/open"
    method = "GET"
    nonce = int(time.time()*1000)
    payload = {"marketSymbol":"BTC-USD"}
    content = json.dumps(payload)
    contenthash = hashlib.sha512(content.encode()).hexdigest()
    message = str(nonce) + url + method + contenthash # + Api-Subaccount-Id
    signature = hmac.new(bit.secret.encode(),
                         message.encode(), hashlib.sha512).hexdigest()
    headers = {
                'Content-Type': 'application/json',
                "Api-Key": bit.key,
                "Api-Timestamp": str(nonce),
                "Api-Content-Hash": contenthash, 
                "Api-Signature": signature,
                # "Api-Subaccount-Id": None, # (optional)
            }
    resp = requests.request(method=method,url=url,json=payload, headers=headers)
    print(resp.json())`

**Comment by arphone2017** [comment]
I try to run your code. It does work. Thanks!
But the payload param seems no working. It returns all the orders. Why?

**Comment by Serpens66** [comment]
> 
> 
> I try to run your code. It does work. Thanks!
> But the payload param seems no working. It returns all the orders. Why?
> 
> oops, I find the reason. If the request method is GET, the url must include the query string. That's all.
> Thank you!

hmhm... but we still need json=payload right? At least if I leave it empty I get invalid contenthash... So my working code would look like this now (but I don't now if all of it is necessary):

`import requests
    import time
    import hmac
    import hashlib
    import json
    import urllib.parse as urlparse
    url = "https://api.bittrex.com/v3/orders/open"
    method = "GET"
    nonce = int(time.time()*1000)
    payload = {"marketSymbol":"BTC-EUR"} # params=payload in requests will create the string below url+payloadstring. so instead we can also leave params={} and do url=url+payloadstring
    content =  payload and json.dumps(payload) or ""
    contenthash = hashlib.sha512(content.encode()).hexdigest()
    payloadstring = payload and "?"+urlparse.urlencode(payload) or ""
    message = str(nonce) + url + payloadstring + method + contenthash
    signature = hmac.new(bit.secret.encode(),
                         message.encode(), hashlib.sha512).hexdigest()
    headers = {
                'Content-Type': 'application/json',
                "Api-Key": bit.key,
                "Api-Timestamp": str(nonce),
                "Api-Content-Hash": contenthash, 
                "Api-Signature": signature,
            }
    resp = requests.request(method=method,url=url, params=payload, json=payload, headers=headers)
    print(resp.json())`

**Comment by cyrus19909** [comment]
@Serpens66 

Are you still facing issues with passing the request params getting open orders ? 

If so can you try this 
`import requests

url = "https://api.bittrex.com/v3/orders/open?marketSymbol=BTC-EUR"

payload = {}
headers = {
  'Accept': 'application/json',
  'Api-Key': '<api-key>',
  'Api-Signature': '<api-sig>',
  'Api-Timestamp': '1599668747926',
  'Api-Content-Hash': '<content-hash>'
}

response = requests.request("GET", url, headers=headers, data = payload)

print(response.text.encode('utf8'))
`

Please let us know if that works and if not can you send us the value of your content hash and we can help you resolve this issue.

**Comment by Serpens66** [comment]
> 
> 
> @Serpens66
> 
> Are you still facing issues with passing the request params getting open orders ?
> 
> If so can you try this
> `import requests
> 
> url = "https://api.bittrex.com/v3/orders/open?marketSymbol=BTC-EUR"
> 
> payload = {}
> headers = {
> 'Accept': 'application/json',
> 'Api-Key': '',
> 'Api-Signature': '',
> 'Api-Timestamp': '1599668747926',
> 'Api-Content-Hash': ''
> }
> 
> response = requests.request("GET", url, headers=headers, data = payload)
> 
> print(response.text.encode('utf8'))
> `
> 
> Please let us know if that works and if not can you send us the value of your content hash and we can help you resolve this issue.

no, I do not have any issue, I helped solving the problem.
Unfortunately your code snippet (you also posted on the other similar issue) does not help at all, because it does not include the problematic part (which is creating the contenthash) See my latest code above, there you see how it works.

Therefore this issue is solved and I hope it helps other users.

**Comment by bittrex-pete** [comment]
Thanks for the feedback @Serpens66. I will update the documentation to make it more clear.
