### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by EvolverDE** [Bittrex/bittrex.github.io#164]
Hello,
if i try to make a API v3 REST GET request in VB.NET, i get '401 Unauthorized' permanently: 

 ```
If V3 = True Then
                   
                    request.ContentType = "application/json"

                    Dim ContentHash As String = CreateHash("")
                    APISign = nonce + URL + request.Method + ContentHash.ToLower
                    APISign = CreateSignature(Secret, APISign)

                    request.Headers.Add("Api-Key:" + Key + "")
                    request.Headers.Add("Api-Signature:" + APISign.ToLower + "")
                    request.Headers.Add("Api-Timestamp:" + nonce + "")
                    request.Headers.Add("Api-Content-Hash:" + ContentHash.ToLower + "")
                   
                Else
                    request.Headers.Add("apisign:" + APISign.ToLower)
                    request.Headers.Add("apikey:" + Key)
                End If
```
------------------------
```
https://api.bittrex.com/v3/balances

{Content-Type: application/json
Api-Key: abcd1234
Api-Signature: 38249630077264a2ee858acfb194fd1bf914f114e1bb13288a5a93834e34266504c6727c9392de82696e539f83ce9c7668a5f4c782fce5b02c739cd704254db2
Api-Timestamp: 1598992674000
Api-Content-Hash: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
Host: api.bittrex.com
Connection: Keep-Alive

}

```
What im doing wrong?

**Comment by cyrus19909** [comment]
Hi @EvolverDE ,

can you try something like 

`var client = new RestClient("https://api.bittrex.com/v3/balances");
var request = new RestRequest(Method.GET);
request.AddHeader("Accept", "application/json");
request.AddHeader("Api-Key", "<key>");
request.AddHeader("Api-Signature", "<sig>");
request.AddHeader("Api-Timestamp", "1599600550421");
request.AddHeader("Api-Content-Hash", "<content hash>");
IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);`

If not can you provide the CreateSignature function you are using ?

**Comment by EvolverDE** [comment]
hi,
thank you for responding. My Code works now, the error was a wrong Timestamp!

**Comment by cyrus19909** [comment]
@EvolverDE glad it worked.
