### ISSUE TITLE
How to get "Api-Content-Hash" by js?

### ISSUE THREAD

**Issue by yundanfeng** [Bittrex/bittrex.github.io#168]
Dear all,
    When i use the api by the "Sample JS Code" in api document, It does not work, and return INVALID_CONTENT_HASH.How to get "Api-Content-Hash" by js?
    `var CryptoJS = require("crypto-js");
var contentHash = CryptoJS.SHA512(JSON.stringify({"marketSymbol":"BTC-USD"})).toString(CryptoJS.enc.Hex);`

**Comment by bittrex-pete** [comment]
Hi @yundanfeng can you provide more details about the request you're trying to make? Based on the sample you provided above, it doesn't look like you're hashing the correct content. The content that needs to be hashed is just the request body. I don't think there is an operation with a body that looks like the one from your example, so I suspect you're hashing something different.

**Comment by yundanfeng** [comment]
> Hi @yundanfeng can you provide more details about the request you're trying to make? Based on the sample you provided above, it doesn't look like you're hashing the correct content. The content that needs to be hashed is just the request body. I don't think there is an operation with a body that looks like the one from your example, so I suspect you're hashing something different.

Hi @bittrex-pete The complete request parameters and test code are listed below:
`params = {"marketSymbol":"ETH-USD","direction":"sell","quantity":"0.001","limit":"500"}`
`request_method = "POST"`
`sign code :`
`    _get_rest_options_pro(api_endpoint, request_method, params, account_id) {
        const timestamp = new Date().getTime();
        let content = JSON.stringify(params);
        if(Object.keys(params).length <= 0) {
            content = ""
        }
        logger.info(content)
        const content_hash = CryptoJS.SHA512(content).toString(CryptoJS.enc.Hex);
        const url = `${this.api_config.restUrl}${api_endpoint}`;
        const pre_sign = [timestamp, url, request_method, content_hash].join('');
        const signature = CryptoJS.HmacSHA512(pre_sign, "test_api_secret_1234").toString(CryptoJS.enc.Hex);
        return {
            url: url,
            headers: {
                "Api-Key": "test_api_key_1234",
                "Api-Timestamp": timestamp,
                "Api-Content-Hash": content_hash,
                "Api-Signature": signature
            }
        }
    }`

`http request params: {"url":"https://api.bittrex.com/v3/orders","headers":{"Api-Key":"test_api_key_1234","Api-Timestamp":1600315228649,"Api-Content-Hash":"0f2c5cb56a0c12f94d5a2b23215dd75eaf38194a2117812a1a866253235d540467cefc053cda097401982055fe370426906534d45cae31deb5a18ada1d7cae1a","Api-Signature":"18479d1b23706d1d285f731a9fba81a2a4ce39abaf8fdb09051a4fab2ff511ed8a6d44121893ffb37d73191a95c675109044b97104ebd8f42a57e81662327558"}} `
