### ISSUE TITLE
Is it possible to get an Ask value smaller than the maximum value of Bid?

### ISSUE THREAD

**Issue by anzaiteacher** [Bittrex/bittrex.github.io#170]
Hello,
I get an Ask value that is less than the maximum bid.
Use: Bittrex API v3

Operating procedure
1. Get all data with REST API `https://api.bittrex.com/v3/markets/{marketSymbol}/orderbook`
2. Get difference data with websocket orderbook

REST get this.
Bid 
```
[..., {1.979}:{0.03346275}, {4.99999999}:{0.03346276}, {0.30160893}:{0.03347232}]
```

Ask
```
[{7.38895681}:{0.03348085}, {3.75}:{0.03348086}, {2.6668}:{0.03348902}, ...]
```

Websocket get this.
```
{ETH-BTC 500 4185118
[{6.30160892 0.03345090} {5.50700000 0.03344142} {0.25214321 0.03330000} {0 0.02313862}]
[{5.50700000 0.03346983} {2.69080000 0.03347585} {0 0.03348902} {0 0.03349984}]}
```

The maximum value of Bit is 0.03347232.
The acquired ASK value is 0.03346983.
Is this possible?

**Comment by bittrex-pete** [comment]
Minimum ask rate should always be greater than the maximum bid rate. If you see minimum ask <= maximum bid, my guess would be that the socket deltas weren't applied properly. Be sure to pay attention to the sequence numbers in the socket messages and in the header of the REST response.

**Comment by anzaiteacher** [comment]
Thanks, @bittrex-pete !

What is "socket deltas"?
I read the [Bittrex Developers](https://bittrex.github.io/api/v3#topic-Synchronizing), but didn't write any details.

**Comment by bittrex-pete** [comment]
Sorry for being unclear. I just meant the messages that come on the socket. They usually have the word "delta" somewhere in the schema so sometimes we just call them deltas.

**Comment by anzaiteacher** [comment]
Thank you for your kindness, @bittrex-pete !
I align the sequence numbers.
