### ISSUE TITLE
Is there any Go (golang) client for v3?

### ISSUE THREAD

**Issue by treeder** [Bittrex/bittrex.github.io#171]
🙏

**Comment by bittrex-pete** [comment]
Sorry @treeder there is not currently an official Go client for v3. We actually haven't published any official clients. I don't know if anyone in the community has developed one, but it seems like most of our users work in Node, Python, Java, or C#.  The REST portion of the API should be straight forward enough to develop against in any language. The websocket half is trickier though. We use asp.net signalR (not asp.net core) for the websocket portion of the api. Finding a Go client for that would be the biggest challenge. Unfortunately, we're not positioned to support development of 3rd party signalR clients.
