### ISSUE TITLE
upgrade to v3

### ISSUE THREAD

**Issue by Sillymee** [Bittrex/bittrex.github.io#172]
Hi, can anyone help because I cannot understand the instructions and steps to upgrade at all

**Comment by Sillymee** [comment]
[Bittrex Developers.pdf](https://github.com/Bittrex/bittrex.github.io/files/5273328/Bittrex.Developers.pdf)

**Comment by Sillymee** [comment]
pls help. Thanks

**Comment by bittrex-pete** [comment]
Hi @Sillymee happy to answer questions. Can you be more specific about what you are stuck on?

**Comment by Sillymee** [comment]
Hi,
The following are the instructions and the red text are my questions as I am totally non-tech and the terms sound very alien to me.
These steps outline the process to upgrade from v1 to v3:
Read through the New Features and General Information sections of this guide to gain a high level familiarity with what is new and different in v3.
 Take an inventory of your usage of the v1 API in your existing code base.How to do this and where to get inform about  ' API in your existing code base'
Identify operations and data used from v1.What does this mean? Were can we identify operations and data used from v1
Note easy opportunities for improvement based on the new features in v3.
Use the REST API and Websocket API reference portions of this guide to map your v1 API usage to v3 equivalents.Where can we find RST API ect
Plan your strategy for replacing v1 dependencies with their v3 equivalentsWhat does it mean and how?
Note: The same engine backs both versions of the API. It is possible to use a mix of v1 and v3 operations while transitioning. Due to the interconnected nature of the v3 REST API and websocket, if a phased transition is desirable, transitioning REST & socket object by object instead of all of REST followed by all of socket may be easier. However the right decision depends on the details of your implementation.Execute your plan. Be sure to test your v3 implementation with small-value transactions to validate it prior to full production usage.


Your assistance is appreciated. 
RegardsS




    On Thursday, September 24, 2020, 10:53:56 PM GMT+8, bittrex-pete <notifications@github.com> wrote:  
 
 


Hi @Sillymee happy to answer questions. Can you be more specific about what you are stuck on?

**Comment by bittrex-pete** [comment]
Hi @Sillymee how do you trade on Bittrex? The required API upgrade is only something that app developers and people who have coded custom trading programs should have to deal with. If you are totally non-technical I'm going to guess that you don't fall into either of those groups. It's possible you got the notification email by mistake or because you're trading via a 3rd party app that needs to be upgraded. It would be very difficult for someone who is non-technical to make the required changes.
