### ISSUE TITLE
can not update APIs 

### ISSUE THREAD

**Issue by khongdung2811** [Bittrex/bittrex.github.io#173]
Dear admin, 
i lost my phone & authenticator , i can not sign in my account to update APIs up to version 3.0
Pls help me  dissable 2FA 

account on Bittrex: nhi.dung@gmail.com

Thanh you
Kim Dung

**Comment by bittrex-pete** [comment]
Hi @khongdung2811 - we only do API support on this forum, not account support. Please file a ticket at https://bittrex.com/Home/Support
