### ISSUE TITLE
API v3 upgrade, Embarcadero Delphi

### ISSUE THREAD

**Issue by surinpeter** [Bittrex/bittrex.github.io#174]
Hi BITTREX.  I would like to ask You few questions. We use our own trading system developed by Embarcadero Delphi (Pascal). It is based on API v.1 interface. We got Your email, that You are finishing with API v1 and You upgrade to API v3. Date is 30. September 2020. The parts of code which doesn’t need authentication we changed to API v3. But in API v3 we have problem with authentication. 
Question # 1 : After 30. September 2020 will we able to use our trading system based on API v1 ???
Question # 2 : Could You help us with code for API v3? Here is part of correct code for authentication in API v1 for GETBALANCES function 

  aRESTClient.BaseURL := 'https://bittrex.com/api/v1.1/account/getbalances';

  aParam := aRESTRequest.Params.AddItem;
  aParam.Kind := pkGETorPOST;
  aParam.name := 'apikey';
  aParam.Value := APIKEY;

  aParam := aRESTRequest.Params.AddItem;
  aParam.Kind := pkGETorPOST;
  aParam.name := 'nonce';
  aParam.Value := '0';

  aParam := aRESTRequest.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'apisign';
  aParam.Value := SHA512DigestToHexW(CalcHMAC_SHA512(SECRET,
    format('%s?apikey=%s&nonce=0', [aRESTClient.BaseURL, APIKEY])));

 aRESTRequest.Execute;

For API v3 we also need :

      CONTENT := '???????';    - we don’t know

      CONTENT_HASH := SHA512DigestToHexW(CalcHMAC_SHA512(SECRET, CONTENT)); ????? is it OK ????

      TimeStamp := Form1.UNIXTimeInMilliseconds;
      METHOD := 'GET';
      URL := 'https://api.bittrex.com/v3/balances';

      PRE_SIGN := TimeStamp + URL + METHOD + CONTENT_HASH;

      SIGNATURE := SHA512DigestToHexW(CalcHMAC_SHA512(SECRET, PRE_SIGN));

      aParam := Form1.RESTRequest1.Params.AddItem;
        aParam.Kind := pkGETorPOST;
        aParam.name := 'Api-Key';
        aParam.Value := APIKEY;

        aParam := Form1.RESTRequest1.Params.AddItem;
        aParam.Kind := pkGETorPOST;
        aParam.name := 'Api-Timestamp';
        aParam.Value := TIMESTAMP;

        aParam := Form1.RESTRequest1.Params.AddItem;
        aParam.Kind := pkGETorPOST;
        aParam.name := 'Api-Content_Hash';
        aParam.Value := CONTENT_HASH;

        aParam := Form1.RESTRequest1.Params.AddItem;
        aParam.Kind := pkGETorPOST;
        aParam.name := 'nonce';
        aParam.Value := '0'; 

      aParam := Form1.RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Apisign';
      aParam.Value := SIGNATURE;

Form1.RESTRequest1.Execute;

With this code we always get message : 401 UNAUTHORIZED

Thank You for Your help. I hope upgrade for v3 will not limit our trading system.

**Comment by bittrex-pete** [comment]
Hi @surinpeter  We won't be fixing bugs, adding anything, or providing support with respect to v1 after this month. We'll also be decreasing infrastructure resources dedicated to it over the course of the next couple months. So it will continue working for a while, but you should get off of it as soon as you can. 

The v3 documentation is a bit unclear about what "content" really is. Apologies for that, I'll be making it more clear soon. The content referred to is just the request body. If there is no request body (like for a GET) then content should just be the empty string.

The content hash is just a hash, not a signature. It doesn't require the HMAC with your secret. That part is only needed for the signature step.

It also looks like the headers you're adding may not be quite right. The four we expect are:
- Api-Key (you have this one)
- Api-Timestamp (you have this one too)
- Api-Content-Hash (you have Api-Content_Hash instead)
- Api-Signature (you have Apisign instead)

Hope this helps!
