### ISSUE TITLE
ALTH field in v3

### ISSUE THREAD

**Issue by surinpeter** [Bittrex/bittrex.github.io#179]
Hi BITTREX, is it possible to implement ALTH field in MarketSummarries ? And also Date of delisting in Currencies, if coin will be delisted. Thanks

**Comment by bittrex-pete** [comment]
Hi @surinpeter - I'm not familiar with ALTH. Can you provide more information about what you're looking for?

**Comment by surinpeter** [comment]
ALTH for XRP-BTC means All Time High, the highest value XRP/BTC ever achieved

**Comment by bittrex-pete** [comment]
Thanks for clarifying. I will pass the feedback along to the team.

**Comment by surinpeter** [comment]
Thank You. And please, do not forget on Date of coin delisting

**Comment by surinpeter** [comment]
Hi Bittrex, I would like to ask You, how it is going with ALTH and Date of coin delisting implementation in v3 ? Thanks

**Comment by bittrex-pete** [comment]
Hi @surinpeter - it is not something we're actively working on. I have made a note of it for future consideration, but it's not something that we will be working on in the near future.
