### ISSUE TITLE
401 Unauthorized when calling DELETE v3

### ISSUE THREAD

**Issue by surinpeter** [Bittrex/bittrex.github.io#181]
Hi Bittrex, following code causes an error : 401 Unauthorized. 

  RESTClient1.BaseURL := 'https://api.bittrex.com/v3/orders/open';
  RESTRequest1.Params.Clear;

  aParam := RESTRequest1.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Key';
  aParam.Value := APIKEY;

  TimeStamp := UNIXTimeInMilliseconds;
  aParam := RESTRequest1.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Timestamp';
  aParam.Value := TimeStamp;

  aParam := RESTRequest1.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'orderId'; //or Id, id ??? I don't know....
  aParam.Value := '7';  //example

  CONTENT := ''; // it should be empty in DELETE or POST method ???
  CONTENT_HASH := SHA512DigestToHexW(CalcSHA512(CONTENT));
  aParam := RESTRequest1.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Content-Hash';
  aParam.Value := CONTENT_HASH;

  METHOD := 'DELETE';
  URL := RESTClient1.BaseURL;
  PRE_SIGN := TimeStamp + URL + METHOD + CONTENT_HASH;
  SIGNATURE := SHA512DigestToHexW(CalcHMAC_SHA512(SECRET, PRE_SIGN));
  aParam := RESTRequest1.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Signature';
  aParam.Value := SIGNATURE;

When I change URL, values in params and method is GET, for example GETBALANCES, code goeas fine. But in DELETE method causes error 401 Unauthorized

Thanks for Your advice

**Comment by bittrex-pete** [comment]
Hi @surinpeter I think your request is a bit off.  If you are trying to cancel a single order, the request should be something like:

DELETE https://api.bittrex.com/v3/orders/fc58954d-d7b3-4a6a-9e8a-f89c4995bc71

where fc58954d-d7b3-4a6a-9e8a-f89c4995bc71 is the id of the order you're looking to cancel. From your code above it looks like you're trying to put the id into a header instead.

To cancel all of your orders, the request should be something like:

DELETE https://api.bittrex.com/v3/orders/open

In both of these cases, there is no request body, so content should be the empty string (as you have it currently).

**Comment by surinpeter** [comment]
Hmm, sorry, still 401 Unauthorized whene METHOD := 'DELETE'. Whene GET, everything is going right.

  RESTClient1.BaseURL := 'https://api.bittrex.com/v3/orders/open';
  RESTRequest1.Params.Clear;

  aParam := RESTRequest1.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Key';
  aParam.Value := APIKEY;

  TimeStamp := UNIXTimeInMilliseconds;
  aParam := RESTRequest1.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Timestamp';
  aParam.Value := TimeStamp;

  CONTENT := '';
  CONTENT_HASH := SHA512DigestToHexW(CalcSHA512(CONTENT));
  aParam := RESTRequest1.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Content-Hash';
  aParam.Value := CONTENT_HASH;

  METHOD := 'DELETE';
  // if METHOD := 'GET' everything is going right, but when 'DELETE' then 401 Unauthorized ERROR
  URL := RESTClient1.BaseURL;
  PRE_SIGN := TimeStamp + URL + METHOD + CONTENT_HASH;
  SIGNATURE := SHA512DigestToHexW(CalcHMAC_SHA512(SECRET, PRE_SIGN));
  aParam := RESTRequest1.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Signature';
  aParam.Value := SIGNATURE;

 RESTRequest1.Execute;

**Comment by bittrex-pete** [comment]
Are you sure RESTRequest1.Execute is executing a DELETE and not a GET? I don't see anywhere in the above code where that is set. If the client is actually executing a GET that could cause the behavior you're describing.

**Comment by surinpeter** [comment]
Yes, You are right :-) 

RESTRequest1.Method:=rmDelete;

Initialy set to "rmGet".

Now is everything OK. Thank You very much
