### ISSUE TITLE
How should I get the same values ​​as "/v1.1/public/getmarketsummaries" with a single call in v3?

### ISSUE THREAD

**Issue by jral** [Bittrex/bittrex.github.io#182]
Hi, 
I need "Last" value by minute for all markets in a single call, as I get now using v1.1 (https://bittrex.com/api/v1.1/public/getmarketsummaries). With this data I create ohlc+v data line file locally for each market. 
Can I do it in V3 version in a single call ? (avoiding the repeated use of the api ',,, /{marketSymbol}/candles/...') 
how?  
Thank you

**Comment by bittrex-pete** [comment]
https://api.bittrex.com/v3/markets/tickers has the last trade rate for all markets

**Comment by jral** [comment]
Ok, will try 
https://api.bittrex.com/v3/markets/tickers
      + 
https://api.bittrex.com/v3/markets/summaries 
Thanks
