### ISSUE TITLE
trade history

### ISSUE THREAD

**Issue by npomfret** [Bittrex/bittrex.github.io#185]
@cyrus19909  The v3 endpoint seems to be missing a fairly crucial feature - a trade history query.  All I can see is `GET /orders/{orderId}/executions`, but I'd need to call this thousands of times to get a full history.  Having said that, I called it once and go *no* data back using a valid order that certainly was traded. Is this endpoint working? 

I can see the websocket feed has trade support, can you please add the same to the Rest API?

**Comment by bittrex-pete** [comment]
Hi @npomfret the ability to page through the history of your orders' fills independently of individual orders is pretty high on our list of things to do. I can't offer a timeline for it at this point, but it is something we're working on.

The `/orders/{orderId}/executions` as it exists does work. There is a few second delay between when a fill occurs and when the information is available in that endpoint. If you're seeing something different, can you share the uuid for the order so we can investigate?

**Comment by npomfret** [comment]
Here's an example: 4e9fa72b-1a48-411f-958b-9bb67ff6e6ec

**Comment by bittrex-pete** [comment]
Thanks @npomfret. We looked into that order and the reason you can't see the fills on it is because it's too old. As stated [in the docs](https://bittrex.github.io/api/v3#operation--orders--orderId--executions-get), fills are only available from mid-2019 onward. That order is from 2018.

**Comment by npomfret** [comment]
Ok, understood.  Is that a temporary thing, like you had with deposits and withdrawals?

**Comment by bittrex-pete** [comment]
I believe this limitation will be permanent

**Comment by npomfret** [comment]
ok.  I hope you reconsider this.  Some people will need access to historical data for tax purposes.  Not just the current year, but if they are investigated then possibly going back 5 years or more.

So how do I get real time updates for my trades?  The Rest API has a noticeable lag.  So when I get notified by the Websocket API of an order change, how do I get the new trade data if it's not available in the Rest API?

**Comment by bittrex-pete** [comment]
Unfortunately the only way to do it right now is wait a couple seconds and then hit the /orders/{orderId}/executions endpoint for the order you saw the update about.  We're working on a websocket feed for this stuff along with the user-level execution history REST call, but it's not available quite yet.

**Comment by npomfret** [comment]
Seriously!?

**Comment by npomfret** [comment]
@bittrex-pete @cyrus19909 when will the new API have real time trade updates?

**Comment by bittrex-pete** [comment]
@npomfret We don't offer public timelines for unreleased features. If you want we can leave this issue open and I can ping you here once this feature is available.

**Comment by npomfret** [comment]
ok thanks.  Can you give me a rough idea?  weeks? months?

**Comment by bittrex-pete** [comment]
Hi @npomfret this feature is live now. You can query for fill history using the [/executions](https://bittrex.github.io/api/v3#tag-Executions) endpoint and you can also subscribe to the [executions](https://bittrex.github.io/api/v3#tag-Executions) socket stream if you'd like to be pushed updates.

**Comment by npomfret** [comment]
Thanks I will try it out.

To reiterate previous requests.  I, and I'm sure all customers who have to pay tax (all customers), really need access to a full accounting history.  Not just "recent" stuff. Please can you add our full history or all transfers, trades, forks, airdrops etc to the API?

**Comment by bittrex-pete** [comment]
Full deposit and withdrawal history should be available already (outside of coins that have been archived off, you have to download your account history from the website to get that data currently). With respect to trading history, there's not much more we can do on this front. You can get your full order history, but details of individual fills are are only available from late May 2019 on. For trades prior to that, I think people have typically used the information available on the order for tax purposes.  That's about as far as I can take this from an API standpoint. If you'd like more help on the tax front, I'd suggest reaching out to our support team: https://bittrex.com/home/support
