### ISSUE TITLE
401 Unauthorized when BUY called

### ISSUE THREAD

**Issue by surinpeter** [Bittrex/bittrex.github.io#186]
Hi BITTREX, when aj call BUY function with following code, I get 401 Unauthorized message again :-(

      RESTClient1.BaseURL := 'https://api.bittrex.com/v3/orders';

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkREQUESTBODY;
      aParam.name := 'marketSymbol';
      aParam.Value := 'ABBC-BTC';

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkREQUESTBODY;
      aParam.name := 'quantity';
      aParam.Value := '21';

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkREQUESTBODY;
      aParam.name := 'direction';
      aParam.Value := 'BUY';

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkREQUESTBODY;
      aParam.name := 'type';
      aParam.Value := 'MARKET';

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkREQUESTBODY;
      aParam.name := 'timeInForce';
      aParam.Value := 'GOOD_TIL_CANCELLED';

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkREQUESTBODY;
      aParam.name := 'useAwards';
      aParam.Value := 'true';

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Key';
      aParam.Value := APIKEY;

      TimeStamp := Form1.UNIXTimeInMilliseconds;
      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Timestamp';
      aParam.Value := TimeStamp;

      CONTENT :=
        format('marketSymbol=%s&quantity=%s&direction=%s&type=%s&timeInForce=%s&useAwards=%s',
        ['ABBC-BTC', '22', 'BUY', 'MARKET', 'GOOD_TIL_CANCELLED', 'true']);
      CONTENT_HASH := SHA512DigestToHexW(CalcSHA512(CONTENT));
      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Content-Hash';
      aParam.Value := CONTENT_HASH;

      METHOD := 'POST';
      URL := RESTClient1.BaseURL;
      PRE_SIGN := TimeStamp + URL + METHOD + CONTENT_HASH;
      SIGNATURE := SHA512DigestToHexW(CalcHMAC_SHA512(SECRET, PRE_SIGN));
      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Signature';
      aParam.Value := SIGNATURE;

      RESTRequest1.METHOD := rmPost;
      RESTRequest1.Execute;

What is wrong ? Thanks

**Comment by bittrex-pete** [comment]
@surinpeter  I would guess that the request body your client is sending is different from the content coming out of that format command you're using. It needs to match exactly. Pretty sure that the content coming out of that format command isn't even valid json.

**Comment by surinpeter** [comment]
This is a new code :

 RESTClient1.BaseURL := 'https://api.bittrex.com/v3/orders';
      RESTRequest1.Params.Clear;

      jsRequest2 := TJSONObject.Create();
      RESTRequest1.METHOD := rmPost;
      aParam := RESTRequest1.Params.AddItem;
      aParam.ContentType := ctAPPLICATION_JSON;
      aParam.Kind := pkREQUESTBODY;
      aParam.Value := jsRequest2.ParseJSONValue
        ('{"marketSymbol":"ABBC-BTC","quantity":"21","direction":"BUY","type":"MARKET","timeInForce":"GOOD_TIL_CANCELLED","useAwards":"True"}')
        .ToJSON;
       jsRequest2.Free();
      // ------------------------------------------------------------------------

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Accept';
      aParam.Value := 'application/json';

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Key';
      aParam.Value := APIKEY;

      TimeStamp := Form1.UNIXTimeInMilliseconds;
      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Timestamp';
      aParam.Value := TimeStamp;

      jsRequest := TJSONObject.Create();
      jsRequest.AddPair('marketSymbol', 'ABBC-BTC');
      jsRequest.AddPair('quantity', '21');
      jsRequest.AddPair('direction', 'BUY');
      jsRequest.AddPair('type', 'MARKET');
      jsRequest.AddPair('timeInForce', 'GOOD_TIL_CANCELLED');
      jsRequest.AddPair('useAwards', 'True');

      CONTENT := jsRequest.ToJSON;
      Edit4.text := CONTENT;
      CONTENT_HASH := SHA512DigestToHexW(CalcSHA512(CONTENT));
      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Content-Hash';
      aParam.Value := CONTENT_HASH;

      METHOD := 'POST';
      URL := RESTClient1.BaseURL;
      PRE_SIGN := TimeStamp + URL + METHOD + CONTENT_HASH;
      SIGNATURE := SHA512DigestToHexW(CalcHMAC_SHA512(SECRET, PRE_SIGN));
      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Signature';
      aParam.Value := SIGNATURE;

      RESTRequest1.METHOD := rmPost;
      jsRequest.Free();

      RESTRequest1.Execute;

Error : 400 Bad Request. Why ? And it means, authorization is OK ?

**Comment by bittrex-pete** [comment]
Check the body of the response for more information about the error. What jumps out at me above is that you're trying to create a market order with a good_til_cancelled time in force. That's not a supported combination.  You're probably getting back INVALID_MARKET_ORDER in the reponse body.  See here for more information about valid orders: https://bittrex.github.io/api/v3#topic-Placing-Orders (specifically the "Order types and time in force" subsection).

On the plus side, yes, there's a good chance your authorization code is now working.

**Comment by surinpeter** [comment]
Thanks. After changes I get ERROR : 405 Method not allowed

      RESTClient1.BaseURL := 'https://api.bittrex.com/v3/orders';
      RESTRequest1.Params.Clear;

      jsRequest2 := TJSONObject.Create();
      RESTRequest1.METHOD := rmPost;
      aParam := RESTRequest1.Params.AddItem;
      aParam.ContentType := ctAPPLICATION_JSON;
      aParam.Kind := pkREQUESTBODY;
      aParam.Value := jsRequest2.ParseJSONValue
        ('{"marketSymbol":"ADA-BTC","quantity":"65","direction":"BUY","type":"MARKET","timeInForce":"IMMEDIATE_OR_CANCEL","useAwards":"True"}')
        .ToJSON;
      jsRequest2.Free();
      // ------------------------------------------------------------------------

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Accept';
      aParam.Value := 'application/json';

      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Key';
      aParam.Value := APIKEY;

      TimeStamp := Form1.UNIXTimeInMilliseconds;
      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Timestamp';
      aParam.Value := TimeStamp;

      jsRequest := TJSONObject.Create();
      jsRequest.AddPair('marketSymbol', 'ADA-BTC');
      jsRequest.AddPair('quantity', '65');
      jsRequest.AddPair('direction', 'BUY');
      jsRequest.AddPair('type', 'MARKET');
      jsRequest.AddPair('timeInForce', 'IMMEDIATE_OR_CANCEL');
      jsRequest.AddPair('useAwards', 'True');

      CONTENT := jsRequest.ToJSON;
      CONTENT_HASH := SHA512DigestToHexW(CalcSHA512(CONTENT));
      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Content-Hash';
      aParam.Value := CONTENT_HASH;

      METHOD := 'POST';
      URL := RESTClient1.BaseURL;
      PRE_SIGN := TimeStamp + URL + METHOD + CONTENT_HASH;
      SIGNATURE := SHA512DigestToHexW(CalcHMAC_SHA512(SECRET, PRE_SIGN));
      aParam := RESTRequest1.Params.AddItem;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'Api-Signature';
      aParam.Value := SIGNATURE;

      RESTRequest1.METHOD := rmPost;
      jsRequest.Free();

     RESTRequest1.Execute;

**Comment by surinpeter** [comment]
It works

aParam.Kind := pkREQUESTBODY changed := pkGETorPOST

Thank You for Your help
