### ISSUE TITLE
error: DUST_TRADE_DISALLOWED_MIN_VALUE

### ISSUE THREAD

**Issue by npomfret** [Bittrex/bittrex.github.io#188]
I'm getting an error 'DUST_TRADE_DISALLOWED_MIN_VALUE' which I assume means my order size is too small.  However, your api metadata at https://api.bittrex.com/v3/markets indicates that for LTC-BTC the min order size is 0.05 (I assume this value is expressed in the base symbol):

```
{
"symbol": "LTC-BTC",
"baseCurrencySymbol": "LTC",
"quoteCurrencySymbol": "BTC",
"minTradeSize": "0.05000000",
"precision": 8,
"status": "ONLINE",
"createdAt": "2014-02-13T00:00:00Z",
"notice": "",
"prohibitedIn": [],
"associatedTermsOfService": []
}
```

My order was a buy order for 0.06LTC which is above the minimum.  Why am I seeing this error?

**Comment by bittrex-pete** [comment]
DUST_TRADE_DISALLOWED_MIN_VALUE happens if the amount of quote currency involved in a transaction would be less than 50k satoshis. It's a separate check from minTradeSize which, granted, is confusing.

**Comment by npomfret** [comment]
Very. And undocumented?  And pointless?  Can you just make the min order equal to the min order amount specified in the metadata?

**Comment by bittrex-pete** [comment]
This is something that certainly could be improved, but it isn't something we see as a priority. I will make sure it gets documented though.

**Comment by bittrex-pete** [comment]
The documentation has been updated with this error code and some other common ones. You can find that documentation here: https://bittrex.github.io/api/v3#topic-Error-Codes (scroll down past the http status codes)

**Comment by npomfret** [comment]
Thanks, but it wasn't really documentation I wanted in this case. I wanted the metadata (https://api.bittrex.com/v3/markets i) that tells me what the minimum value is to be accurate.

**Comment by bittrex-pete** [comment]
Understood. I have a change request logged for it, but it's not something that going to happen in the near future. Appreciate the feedback though.
