### ISSUE TITLE
Swagger or Postman Collection

### ISSUE THREAD

**Issue by fgodoy** [Bittrex/bittrex.github.io#190]
Hi guys.

I tried to find any data sample in the API documentation, but found only only schemas (With types only). 

Is there any Postman collection or swagger that helps implementation tests?

Thanks in advance.

**Comment by bittrex-pete** [comment]
Hi @fgodoy - the docs are actually derived from a swagger. You can find it here: 

https://github.com/Bittrex/bittrex.github.io/blob/master/src/_data/api-spec-v3.json 

It doesn't have any more information in it than the docs themselves though. We haven't created any data samples. I think people usually just call the methods based on the spec and see what they get back.

**Comment by fgodoy** [comment]
Ok. This can helps for now. 

I think that's a good idea to have some samples of real data due to more efficient programming. Some other exchanges have this kind of information and I can say that's helps a lot. :)

Tks.

**Comment by bittrex-pete** [comment]
Thanks for the suggestion!
