### ISSUE TITLE
'percentChange' in 'MarketSummary' schema definition

### ISSUE THREAD

**Issue by sviriden** [Bittrex/bittrex.github.io#191]
Property "percentChange" is required (according to https://bittrex.github.io/api/v3#definition-MarketSummary)

But if market have no trades last day this property is omitted. Example right now — https://api.bittrex.com/v3/markets/ABYSS-BTC/summary

![Pasted_Image_06_10_2020__20_54](https://user-images.githubusercontent.com/152393/95220413-294ac200-0816-11eb-9171-bf758b9da998.jpg)

**Comment by bittrex-pete** [comment]
Hi @sviriden - Thanks for reporting this. You are correct that percentChange will not be present if there have been no trades. I will get the documentation updated to reflect this.

**Comment by bittrex-pete** [comment]
The docs have been updated to reflect this
