### ISSUE TITLE
Minimum increment for Amount and Price USING API

### ISSUE THREAD

**Issue by RicardoThess** [Bittrex/bittrex.github.io#192]
The API informs, using the endpoint "GET /markets", that there are a minimum amount to buy, "field minTradeSize", and a price precision, "field precision".
For example ADA-USD:
- minTradeSize: 21.00000000
- precision: 5 

To send a buy order (limited) I need to know the valid amount (trade size) and price required by Bittrex but I need to know also the minimum increment.

Question 1 -> Price: since that the precision is 5 can I increase the price on the order using the increment of 0.00001?  Example: 0.00001, 0.00002, 0.00003 .... 1.00001

Question 2 -> Amount Not informed by API: Can I send a increment of 0.000000000001 for ADA?  Example: 21.000000000001, 21.000000000002, 21.000000000003 ....
If not how can I know the valid increment? Ex: 0.1, 0.001, 0.0001 .... 0.0000000000000001

**Comment by fgodoy** [comment]
Nice catch, I have this same question here. Anyone can help?

Thanks a lot.

**Comment by bittrex-pete** [comment]
Hi @RicardoThess and @fgodoy - the precision refers to the price only, not the quantity. If you try to place a limit order with more digits of price precision than allowed you'll get back RATE_PRECISION_NOT_ALLOWED. The precision for quantity is always 10^-8. If you provide more precision in the quantity than allowed it will be truncated. So if precision is 3:

Allowed: Quantity: 10.00000001, Limit: 10.001
Prohibited: Quantity: 10.00000001, Limit: 10.0001   

minTradeSize is the minimum order quantity in the base currency (e.g. ADA).  We also require the value of orders be larger than 0.0005 units of the quote currency (e.g. USD).  The error codes for violating these two restrictions are MIN_TRADE_REQUIREMENT_NOT_MET and DUST_TRADE_DISALLOWED_MIN_VALUE, respectively.

**Comment by FradelDelgarde** [comment]
When using ApI why some of selected chekup boxes are missing and stoping you to trade

**Comment by FradelDelgarde** [comment]
Maybe is software issue

**Comment by FradelDelgarde** [comment]
Does anyone knows how to fix it in the trade web
