### ISSUE TITLE
Endpoint "orders" and "comission" field return values.

### ISSUE THREAD

**Issue by fgodoy** [Bittrex/bittrex.github.io#196]
Hi Guys.

I'm using the API endpoint "orders" and I have one question about the field "comission" that is returned. 

The question is what it returns:
1) Percentage? Eg: 0.2%
2) Amount in QUOTE currency based on the volume (amount*average_price)? Eg: (0.002 BTCs)
3) Amount in Base currency? Eg: 0.005 ADA

Thanks again.

**Comment by bittrex-pete** [comment]
It's the total commission paid on the order (so far) in quote currency (commission is always paid in quote currency in our system). It's calculated as the sum of commission rate * fill quantity * rate over all of the orders executions.
