### ISSUE TITLE
Endpoint "orders" not have last executed price

### ISSUE THREAD

**Issue by flong86** [Bittrex/bittrex.github.io#197]
Hi，
Endpoint "orders" does not have the last executed price or the average executed price, and the not accurate executed price can only be calculated by "proceeds".

**Comment by bittrex-pete** [comment]
Hi @flong86  - you can get the execution details from https://bittrex.github.io/api/v3#operation--orders--orderId--executions-get

**Comment by flong86** [comment]
Hi @bittrex-pete 
Yes, I know this, but “excecutions” won't get it until a few seconds after receiving the “CLOSEED” order on “orders” Endpoint

**Comment by bittrex-pete** [comment]
I see. If you need the execution data faster, our plan is to provide a websocket feed of order executions as they happen. That's not available yet, but it is something we're working on.

**Comment by flong86** [comment]
thank you for your reply
