### ISSUE TITLE
deposit sort order

### ISSUE THREAD

**Issue by npomfret** [Bittrex/bittrex.github.io#199]
@cyrus19909 @bittrex-pete   How do i get the deposit history from the new api starting with the most recent item?  I basically want the same functionality as your website has ( https://global.bittrex.com/api/v2.0/auth/balance/GetWithdrawalHistoryEx).  The docs say:

> Pagination and the sort order of the results are in inverse order of the CompletedAt field.

I've not idea what this sentence means, could someone please clarify?

Why doesn't the website use the new API?

**Comment by bittrex-pete** [comment]
GET /deposits/closed gives you completed deposits with the most recent item first. "Most recent" for this endpoint is defined based on when the deposit was completed.

The website was built before the new API was developed. You'll see more and more of it switch over to the new API as time goes on.

**Comment by npomfret** [comment]
When I call the api with a limit of say 5 items I seem to get the oldest items, not the most recent.

**Comment by bittrex-pete** [comment]
Seems to work as described for me. e.g. /deposits/closed?pageSize=1 gives me my most recently closed deposit.

Can you share the exact URL that you're using?

**Comment by npomfret** [comment]
Apologies. I was filtering some results out.
