### ISSUE TITLE
UNKNOWN_ERROR when connecting to socket

### ISSUE THREAD

**Issue by bittrex-pete** [Bittrex/bittrex.github.io#201]
Connection and authorization are in progress, but when trying to subscribe I get the following errors: heartbeat: UNKNOWN_ERROR
trade_BTC-USD: UNKNOWN_ERROR
balance: UNAUTHORIZED_USER

{"R":[{"Success":false,"ErrorCode":"UNKNOWN_ERROR"},{"Success":false,"ErrorCode":"UNKNOWN_ERROR"},{"Success":false,"ErrorCode":"UNAUTHORIZED_USER"}],"I":"1"}

The code is completely identical to your example in c #

static async Task Subscribe(SocketClient client)
        {
            client.SetHeartbeatHandler(() => Console.WriteLine("<heartbeat>"));
            client.AddMessageHandler<object>("trade", msg => Console.WriteLine($"Trade: {msg}"));
            client.AddMessageHandler<object>("balance", msg => Console.WriteLine($"Balance: {msg}"));

            var channels = new string[] {
                "heartbeat",
                "trade_BTC-USD",
                "balance" };
           
            
            var response = await client.Subscribe(channels);
            for (int i = 0; i < channels.Length; i++)
            {
                Console.WriteLine(response[i].Success ? $"{channels[i]}: Success" : $"{channels[i]}: {response[i].ErrorCode}");
            }
        }

 public async Task<List<SocketResponse>> Subscribe(string[] channels)
        {
            return await _hubProxy.Invoke<List<SocketResponse>>("Subscribe", (object)channels);
        }

_Originally posted by @CryptoArbitrage9 in https://github.com/Bittrex/bittrex.github.io/issues/157#issuecomment-721277203_

**Comment by bittrex-pete** [comment]
Hi @CryptoArbitrage9 that's interesting. Does this happen every time or just sometimes?

**Comment by CryptoArbitrage9** [comment]
Several times I managed to subscribe to "heartbeat" and "trade_BTC-USD", I always get an error on "Balance". Out of 100 launches, I manage to subscribe 1-2 times to "heartbeat" and "trade_BTC-USD"

**Comment by bittrex-pete** [comment]
And authenticating is working reliably? That is, if you provide an API key and secret it will print out "Authenticated" after printing "Connected" and before give you the subscription error?

**Comment by CryptoArbitrage9** [comment]
Yes exactly))

From debug:
Connected
Authenticated

**Comment by CryptoArbitrage9** [comment]
Now got messages like this: 
Exception thrown: 'System.PlatformNotSupportedException' in System.dll
Connected
Authenticated

**Comment by bittrex-pete** [comment]
Did something change with how you're running the code before you started getting that exception? 
What version of .net is your project targeting and what operating system is your machine running?

**Comment by CryptoArbitrage9** [comment]
no, nothing has changed.Target Farmework: 4.7.2, Windows 7x64

**Comment by CryptoArbitrage9** [comment]
I think this is due to Windows 7, most likely the hubconection state does not change

**Comment by CryptoArbitrage9** [comment]
Exception thrown: 'System.PlatformNotSupportedException' in System.dll
StateChanged Connecting -> Connected
serverSentEvents
Connected
Authenticated
heartbeat: Success
trade_BTC-USD: Success
balance: UNAUTHORIZED_USER
<heartbeat>
<heartbeat>

Changed this:
` public async Task<bool> Connect()
        {
            _hubConnection.StateChanged += change =>
            {
                Console.WriteLine("StateChanged {0} -> {1}", change.OldState, change.NewState);
            };
            await _hubConnection.Start();
            Console.WriteLine(_hubConnection.Transport.Name);
            return _hubConnection.State == ConnectionState.Connected;
        }`

**Comment by CryptoArbitrage9** [comment]
It didn't help, everything also doesn't work))

**Comment by bittrex-pete** [comment]
Yeah, looks like subscribe doesn't work with server sent events so it's not going to work on Win7. On my Win10 machine everything works fine normally, but if I change the connection code to force server sent events, e.g.

```
var transport = new ServerSentEventsTransport();
await _hubConnection.Start(transport);
```

Then I see the same behavior that you're seeing. Given that even Microsoft doesn't support Windows 7 anymore, I think you'll need to upgrade to a newer OS to get this to work.

**Comment by CryptoArbitrage9** [comment]
Ok, tomorrow I will install Windows 10, I will report the results)

**Comment by CryptoArbitrage9** [comment]
everything works with Window 10, so the problem is really in Windows 7. Thanks for your help
