### ISSUE TITLE
ERROR 400, Bad request in SELL ORDER command

### ISSUE THREAD

**Issue by surinpeter** [Bittrex/bittrex.github.io#202]
Hi Bittrex, 

 is there any change or trouble in API v3 ? Until yesterday, I had working program. Without any change in code. Now I have ERROR 400 Bad request when I want  to sell. Here is code, which was functional until yesterday. Thank You for Your help

  APIKEY := form1.APIKEY;
  SECRET := form1.SECRET;

  aMarketSymbol := aMarket;
  aQuantity := Form25.Label4.Caption;
  aDirection := 'SELL';
  aType := 'MARKET';
  aTimeInForce := 'IMMEDIATE_OR_CANCEL';
  aUseAwards := 'True';

  aRESTClient.BaseURL := 'https://api.bittrex.com/v3/orders';
  aRESTRequest.Params.Clear;

  jsRequest2 := TJSONObject.Create();
  aRESTRequest.METHOD := rmPost;
  aParam := aRESTRequest.Params.AddItem;
  aParam.ContentType := ctAPPLICATION_JSON;
  aParam.Kind := pkGETorPOST;
  aParam.Value := jsRequest2.ParseJSONValue('{"marketSymbol":"' + aMarketSymbol
    + '","quantity":"' + aQuantity + '","direction":"' + aDirection +
    '","type":"' + aType + '","timeInForce":"' + aTimeInForce +
    '","useAwards":"' + aUseAwards + '"}').ToJSON;
  jsRequest2.Free();
  // -----------------------------------------------------------------------
  aParam := aRESTRequest.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Accept';
  aParam.Value := 'application/json';

  aParam := aRESTRequest.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Key';
  aParam.Value := APIKEY;

  TimeStamp := form1.UNIXTimeInMilliseconds;
  aParam := aRESTRequest.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Timestamp';
  aParam.Value := TimeStamp;

  jsRequest := TJSONObject.Create();
  jsRequest.AddPair('marketSymbol', aMarketSymbol);
  jsRequest.AddPair('quantity', aQuantity);
  jsRequest.AddPair('direction', aDirection);
  jsRequest.AddPair('type', aType);
  jsRequest.AddPair('timeInForce', aTimeInForce);
  jsRequest.AddPair('useAwards', aUseAwards);

  CONTENT := jsRequest.ToJSON;
  CONTENT_HASH := SHA512DigestToHexW(CalcSHA512(CONTENT));
  aParam := aRESTRequest.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Content-Hash';
  aParam.Value := CONTENT_HASH;

  METHOD := 'POST';
  URL := aRESTClient.BaseURL;
  PRE_SIGN := TimeStamp + URL + METHOD + CONTENT_HASH;
  SIGNATURE := SHA512DigestToHexW(CalcHMAC_SHA512(SECRET, PRE_SIGN));
  aParam := aRESTRequest.Params.AddItem;
  aParam.Kind := pkHTTPHEADER;
  aParam.name := 'Api-Signature';
  aParam.Value := SIGNATURE;

  aRESTRequest.METHOD := rmPost;
  jsRequest.Free();

 aRESTRequest.Execute;

**Comment by bittrex-pete** [comment]
Hi @surinpeter - that's interesting.  Is there an error code included in the response body? There should be an error code in the response that would help determine the issue.  One guess without knowing the error code: I see that UseAwards is hardcoded to true in the above. It's possible you've used up all your credits. Does setting UseAwards to false help?

**Comment by surinpeter** [comment]
Thank You very much. After setting UseAwards to False, everything is going right. Thank You for Your help.

**Comment by passio777x** [comment]
> Thank You very much. After setting UseAwards to False, everything is going right. Thank You for Your help.
Thanks, you saved me.
