### ISSUE TITLE
Query-string REST API EXAMPLE

### ISSUE THREAD

**Issue by Tarmek15** [Bittrex/bittrex.github.io#203]
Can not get how to make GET request of order filtereted by market (https://bittrex.github.io/api/v3#operation--orders-open-get)
`   REQUEST PARAMETERS`
`    marketSymbol: filter by market (optional)`
`string`
`in query`

Query-string should be right after the url, like this, but there is no exact format of it:

"https://api.bittrex.com/v3/orders/open?marketSymbol=BTC-DOGE"

or 

"https://api.bittrex.com/v3/orders/open?marketSymbol:BTC-DOGE"

or

"https://api.bittrex.com/v3/orders/open?MarketName=BTC-DOGE"

or something else, because all i tried!!! Nothing works.

How it must be?

PLZ, help.

**Comment by bittrex-pete** [comment]
Hey @Tarmek15 try https://api.bittrex.com/v3/orders/open?marketSymbol=DOGE-BTC

The market symbols in v3 api align to the standard forex conventions which is the reverse of how they're displayed in the old API and on the website. We've tried our best to be helpful with error messaging in the API as much as possible. It's always worth taking a look at the response body for clues if the API is returning back an error. In this case the error you would have gotten back for your first example would be: 

```
{
    "code": "MARKET_NAME_REVERSED",
    "detail": "The provided market symbol appears to be reversed. Please retry with the market symbol provided in data.NewMarketSymbol.",
    "data": {
        "newMarketSymbol": "DOGE-BTC"
    }
}   
```

**Comment by Tarmek15** [comment]
Yeah! Great! Thanks!!!
