### ISSUE TITLE
unnecessary `async` in the v3 websocket example code

### ISSUE THREAD

**Issue by colourful-land** [Bittrex/bittrex.github.io#204]
In sample code:

https://github.com/Bittrex/bittrex.github.io/blob/3cbb36300c58a5f733bb28e855e5b917e9460d46/samples/V3WebsocketExample.js#L87

The keyword `async` is unnecessary there since the purpose of `invoke` function is to return a `Promise`. (`async` can convert a function to one that returns a promise that can be `await`ed but if it already returns a Promise then it can already be awaited), You can remove that keyword and the code will still run flawlessly.

**Comment by bittrex-pete** [comment]
Hi @colourful-land  - thanks for the feedback! Technically you're right, that async isn't needed there. Stylistically, I like having it there though as an indication to whoever is calling it that they're going to want to await the result.
