### ISSUE TITLE
GetMarkets error

### ISSUE THREAD

**Issue by surinpeter** [Bittrex/bittrex.github.io#205]
Hello Bittrex. I get BTC-XEL removal notice even BaseCurrency is XRP. I get it in all currencies started with X.  Similar on other cases. BTC-BLOC removal message for all B* coins

**Comment by surinpeter** [comment]
![Screenshot_20201119-181817_Video Player](https://user-images.githubusercontent.com/71847235/99700740-da8a7c00-2a93-11eb-8838-618aabfc5b39.jpg)

**Comment by bittrex-pete** [comment]
Hi @surinpeter - there must be a bug in your code somewhere.  If you go to https://api.bittrex.com/v3/markets and look through the results you'll see that the notices are only where they belong.

**Comment by surinpeter** [comment]
Thank You, I found the bug.  aMarket.Notice := '' before IF. Thanks.
