### ISSUE TITLE
API check up boxes are missing from bithumb global web and others trading web companies

### ISSUE THREAD

**Issue by FradelDelgarde** [Bittrex/bittrex.github.io#207]
Creating API, trading check-in up box and some other boxes are missing from bithumb global. All other trade webs have the same issues that needed to be fixed by these trading companies. Otherwise, people traders and investors will not be able to trade and complete their exchanging processes.

**Comment by bittrex-pete** [comment]
Hi @FradelDelgarde - this board is for supporting Bittrex's APIs, not Bithumb which is a completely different exchange. I'd suggest reaching out to their support for help.
