### ISSUE TITLE
Please provide a list of possible error codes

### ISSUE THREAD

**Issue by Nilotaviano** [Bittrex/bittrex.github.io#208]
Right now I'm having to manually test out the API to find the error codes (`INSUFFICIENT_FUNDS`, `DUST_TRADE_DISALLOWED`, etc.). This is really tiresome, why can't Bittrex provide us with documentation of possible `Error` responses?

**Comment by bittrex-pete** [comment]
Hi @Nilotaviano - We just pushed an update to the docs that includes a list of the top 25-30 error codes including the ones you mentioned. Start from here https://bittrex.github.io/api/v3#topic-Error-Codes and scroll down past the HTTP status codes to find the product error codes. There are other things that can happen in the system, but I think these are the most common. Let me know if anything is missing that you'd like to see there.

**Comment by Nilotaviano** [comment]
Thank you @bittrex-pete!
