### ISSUE TITLE
is there a way to get withdrawal fees?

### ISSUE THREAD

**Issue by npomfret** [Bittrex/bittrex.github.io#21]

**Comment by jayarjo** [comment]
I would also like to hear if there's an endpoint for this.

**Comment by bricky** [comment]
I think you're looking for `TxFee` in https://bittrex.com/api/v1.1/public/getcurrencies

e.g.

```javascript
{
   "success":true,
   "message":"",
   "result": [
      {
         "Currency":"BTC",
         "CurrencyLong":"Bitcoin",
         "MinConfirmation":2,
         "TxFee":0.00050000,
         "IsActive":true,
         "CoinType":"BITCOIN",
         "BaseAddress":"1N52wHoVR79PMDishab2XmRHsbekCdGquK",
         "Notice":null
      },
      ...
   ]
}
```

where 0.0005 is the withdrawal fee for bitcoin.

**Comment by jayarjo** [comment]
@bricky, do you know what is `BaseAddress` or `Notice` fields for?

**Comment by bricky** [comment]
- `BaseAddress` - for any cryptonote-derived currencies, this is the deposit address (for those currencies `getdepositaddress` gives you the paymentId).  For the other currencies, I've no idea.
 - `Notice` - I think it contains some kind of error message when the wallet is offline (I don't use it though, so can't say for sure)
