### ISSUE TITLE
CANNOT_ESTIMATE_COMMISSION

### ISSUE THREAD

**Issue by Nilotaviano** [Bittrex/bittrex.github.io#211]
Just got a `CANNOT_ESTIMATE_COMMISSION` on a bot while it tried to set a limit buy order. What does it mean?

**Comment by Nilotaviano** [comment]
It was on `COMP-ETH` if that's of any help

**Comment by bittrex-pete** [comment]
@Nilotaviano  I believe it's related to certain market conditions and trying to pay commission with credits (useAwards=true). I don't recall the exact conditions off-hand. But I'll figure it out and let you know. In the meantime, pretty sure you can get around it by not setting useAwards.

**Comment by Nilotaviano** [comment]
Not being able to use credits is a bummer 😢

**Comment by bittrex-pete** [comment]
Sometimes this error will happen due to markets being offline or otherwise unhealthy. Doesn't seem like that's the case here. Another reason it can happen is if amount (limit * quantity) * commissionRate truncated to 8 decimal places is zero. Or, if you can't reproduce the error by submitting the same request, it's possible there was some transient system issue.

**Comment by Nilotaviano** [comment]
I'm getting it pretty much all the time on ETH markets

**Comment by bittrex-pete** [comment]
That's interesting. Would you be willing to share an example order limit and quantity (and market if it's not from COMP-ETH)?

**Comment by Nilotaviano** [comment]
Sorry for the delay, I stopped running tests. I'll try again now and send you and example order

**Comment by Nilotaviano** [comment]
Pretty much instant:
```
4|SpreadBotEth  | BuyLimit: {"marketSymbol":"COMP-ETH","quantity":0.45363589,"limit":0.22000023,"direction":"BUY","type":"LIMIT","timeInForce":"POST_ONLY_GOOD_TIL_CANCELLED","useAwards":true}
4|SpreadBotEth  | Unexpected API error: {"code":"CANNOT_ESTIMATE_COMMISSION"}
```

**Comment by Nilotaviano** [comment]
>(limit * quantity) * commissionRate

My account volume is currently $282,876.75, so according to [this](https://bittrex.zendesk.com/hc/en-us/articles/115000199651-What-fees-does-Bittrex-charge-), I get a 0.12% maker fee.

(0.22000023 * 0.45363589) * 0.12% = 0.00011976, so it's not that.

**Comment by Nilotaviano** [comment]
Just a quick update: I've been testing my bot all morning and this hasn't happened since.

**Comment by bittrex-pete** [comment]
I guess we'll chalk it up to a transient system issue then. It's very strange that you were able to reproduce the behavior for so long though. If you see it again please let us know.

**Comment by bittrex-pete** [comment]
Hey @Nilotaviano  - If you do happen to see it again it would be great if you could hit this https://bittrex.com/api/v1.1/public/getmarketsummary?market=USD-ETH a few times and pass along the results to us. The reason is that awards are valued in USD so we use some price data from the quote currency's USD market to determine their value when an order using awards is placed. If there was a problem with the cache of that data on some machine it could cause that error.

**Comment by Nilotaviano** [comment]
Just got it again on COMP-ETH

Here's the market summary for USD-ETH:
`{"success":true,"message":"","result":[{"MarketName":"USD-ETH","High":601.40100000,"Low":585.01300000,"Volume":4596.15310586,"Last":589.81500000,"BaseVolume":2725669.37520154,"TimeStamp":"2020-12-08T00:22:09.63","Bid":589.44600000,"Ask":589.84200000,"OpenBuyOrders":1753,"OpenSellOrders":941,"PrevDay":599.45100000,"Created":"2018-06-20T18:16:05.573"}]}`

Here's the ETH-COMP market data at the time
`{"Symbol":"COMP-ETH","LastTradeRate":0.25932348,"BidRate":0.25896914,"AskRate":0.26349266,"High":0.25932348,"Low":0.22797488,"Volume":56.59644491,"QuoteVolume":13.68731948,"PercentChange":12.81,"UpdatedAt":"2020-12-08T00:22:14.663Z","MinTradeSize":0.01500000,"Precision":8,"CreatedAt":"2020-07-06T18:06:04.977Z","Notice":null,"BaseMarket":"ETH","SpreadPercentage":1.7167537038792655552530381700}`

**Comment by bittrex-pete** [comment]
Thanks. I let some people know. Do you happen to have the order request handy as well?

**Comment by bittrex-pete** [comment]
If you don't have it that's okay - we'll just assume it's similar to the one you posted before

**Comment by Nilotaviano** [comment]
I don't have it, but it was similar to the previous one.

**Comment by bittrex-pete** [comment]
I think we figured it out.  I'm guessing you're a Bittrex Global customer i.e. if you log into bittrex.com do you end up on global.bittrex.com.  BG is running a zero-trading-fee DeFi promo right now (https://global.bittrex.com/discover/defi) so you wouldn't pay commission on COMP-ETH anyway. The API is seeing this and interpreting the zero that comes back and interpreting that as an error condition where it can't estimate how many credits to charge you for the trade. We'll work on getting that fixed. In the meantime though, enjoy the free trading. :)

**Comment by Nilotaviano** [comment]
Yes, I'm a Bittrex Global customer. Glad you found the issue!
