### ISSUE TITLE
Using the API how identify the network for each currency

### ISSUE THREAD

**Issue by RicardoThess** [Bittrex/bittrex.github.io#212]
I need to avoid problem when I'm sending a deposit to Bittrex because it can be in a diferent network. For this reason I have some questions:

- How can I know the respective network (ERC20, NEO, BEP2, AION, etc) for a currency?

- Looking the documentation I found the endpoint: /currencies 
- It returns the coinType field. Is it the network or something like of protocol used?   
- Imagine a currency XXX that is a "copy"(software/technology) of a ETH, Is this XXX currency returns  ETH_CONTRACT or XXX_CONTRACT?

- Do you have a list with this relationship (currency X network)?

**Comment by bittrex-pete** [comment]
Hi @RicardoThess - the coinType on the currency is the best thing to look at to answer that question though sometimes there is some text in the notice that can help also. ETH_CONTRACT is typically an ERC20. Most BITTREXPINGPONGs are mainnets with the exception of the few KLV, CNS (tron assets). BITTREXPOOLED also typically mainnets. I don't have a full list of the relationships, but if there are specific coins that you're worried about I'd suggest reaching out to the support team:  https://bittrex.com/home/support

**Comment by bittrex-pete** [comment]
You could also check out the deposit instructions for the currency on the website as there may be more information available there that isn't surfaced in the API anywhere
