### ISSUE TITLE
POST "https://api.bittrex.com/v3/addresses" returns "INVALID_PERMISSION" with valid API key

### ISSUE THREAD

**Issue by joachimdb** [Bittrex/bittrex.github.io#213]
## Problem
Since we switched to the v3 API we're unable to generate new deposit addresses

## Request details:

- url: https://api.bittrex.com/v3/addresses
- request body: `"{\"currencySymbol\":\"ZRX\"}"`,
- request headers: 
```
       "Api-Key": "...",
       "Api-Timestamp": 1608211236124,
       "Api-Content-Hash": "0d0440c8df77a401f59fe14731c3cfcf95e4be679b703e051fcf8f1b54c8fc82476633482d34146f97cc5aea37cb4d139a1b94b89b01262b0d3e91c26490c41e",
       "Api-Signature": "551009114569EC43E0D50E8987ACF88174E068347128803FDA1D62B97D3266C1BC495B933B41961A7D5A3014DA56989D90F45A98DE9D2833E705FA5D44675EC5",
       "Content-Type": "application/json"
```
- request method: POST

## Response details: 

- response code: `401`
- response body: `"{\"code\":\"INVALID_PERMISSION\"}"`
- response headers: 
```
     {"Date", "Thu, 17 Dec 2020 13:20:36 GMT"},
     {"Content-Type", "application/json; charset=utf-8"},
     {"Content-Length", "29"},
     {"Connection", "keep-alive"},
     {"Set-Cookie",
      "__cfduid=d2ca0225b0b84d564c25a65d2757c094b1608211236; expires=Sat, 16-Jan-21 13:20:36 GMT; path=/; domain=.bittrex.com; HttpOnly; SameSite=Lax; Secure"},
     {"Request-Id", "3b1ef74b-4d87-4835-9f27-5bef04bc1493"},
     {"Strict-Transport-Security", "max-age=15768000"},
     {"X-XSS-Protection", "1; mode=block"},
     {"X-Content-Type-Options", "nosniff"},
     {"X-Download-Options", "noopen"},
     {"CF-Cache-Status", "DYNAMIC"},
     {"cf-request-id", "0712751d5f0000f2426131d000000001"},
     {"Expect-CT",
      "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""},
     {"Server", "cloudflare"},
     {"CF-RAY", "6030f1423e62f242-ORD"}
```

## notes:
- the API key that was used is valid as it allows access to other private endpoints
- the same API key can be used to generate deposit addresses successfully with the v1 API

**Comment by bittrex-pete** [comment]
Hi @joachimdb - It looks like there was a change between v1 and v3 with respect to the required permissions. On v1 you could create a deposit address with view permissions, but on v3 it's set to require withdrawal permissions. I can see how this would be problematic so I've asked for it to be changed back. In the meantime, you should be able to work around it by creating them from the UI or if you have a lot to create, by using a key with withdrawal permissions (no need to keep that key around after requesting the addresses).

**Comment by joachimdb** [comment]
Hm, OK, thanks for the reply and for asking to change that back, indeed it does not really make sense to require withdrawal permissions for acquiring deposit addresses.. 

Anyway, in the mean time we're working around this by using the v1 API (only for getting deposit addresses). Could you give an idea about how long we'll be able to do that now that the v1 API is deprecated?

Thanks again

**Comment by bittrex-pete** [comment]
Hi @joachimdb - this issue was resolved a while back. I'm also going to mention it in the change log the next time we update the documentation
