### ISSUE TITLE
Documentation that contains error messages and details

### ISSUE THREAD

**Issue by nuxy** [Bittrex/bittrex.github.io#214]
I'm currently in the process of upgrading a package I maintain to use the [Bittrex API v3](https://bittrex.github.io/api/v3) release.

When placing an order (buy/sell) I receive the error code: `INVALID_RESTRICTED_ACCOUNT`

Is there documentation related to these API errors? _I cannot find them anywhere on the site._

Thanks in advance.

**Comment by bittrex-pete** [comment]
Hi @nuxy it means that you're using a Bittrex US account to try to trade on a Bittrex Global-only market. Best way to avoid it is to check https://bittrex.github.io/api/v3#operation--account-permissions-markets-get and only trade on markets where you have buy/sell permission. 

There is a section in the documentation about error codes. You can find it here: https://bittrex.github.io/api/v3#topic-Error-Codes (scroll down a bit past the HTTP status stuff). Looks like this particular code got left out though. I will make sure it gets added to that section of the docs.
