### ISSUE TITLE
Create MARKET Order Fails because of optional parameters

### ISSUE THREAD

**Issue by PrettyBoyHelios** [Bittrex/bittrex.github.io#215]
Hello, I'm trying to create a trade order at market price.

The docs state that ceiling and limit fields are optional when handling market orders. I have tried a combination of parameters but none has worked, These are the params I have right now

{
    "marketSymbol":"CRW-BTC",
     "direction":"BUY",
    "type":"MARKET",
    "quantity":"150",
    "ceiling":"150",
    "limit":"150",
    "timeInForce":"GOOD_TIL_CANCELLED",
    "clientOrderId":"",
    "useAwards":""
}

But I get this message "{"code":"INVALID_ORDER_TYPE"}"
Without the ceiling and limit fields I got a message saying those fields can't be 0.

What would be the proper way of creating a  simple market price order?

**Comment by bittrex-pete** [comment]
Hi @PrettyBoyHelios - here's an example:

`
{
  "marketSymbol": "BTC-USD",
  "direction": "BUY",
  "type": "MARKET",
  "quantity": 0.1,
  "timeInForce": "FILL_OR_KILL"
}
`

You can find which fields are allowed for different order types in the docs here: https://bittrex.github.io/api/v3#topic-Placing-Orders (look in the sidebar on the right)

**Comment by PrettyBoyHelios** [comment]
Thanks, that reference worked!
