### ISSUE TITLE
I can't create an order.

### ISSUE THREAD

**Issue by AndrNic** [Bittrex/bittrex.github.io#217]
The request for balance and orders is successful. And you can't create a new order. Where is the error?

string content = "{\"marketSymbol\":\"USD-EUR\",\"direction\":\"BUY\",\"type\":\"LIMIT\",\"quantity\":\"30\",\"limit\":\"0.8117\",\"timeInForce\":\"GOOD_TIL_CANCELLED\"}";
public static async Task<string> GetOrder( string content)
    {      
      string url = "https://api.bittrex.com/v3/orders/";
      string message;
      try
      {
        var timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();        
        string contentHash;
        using (var sha = new System.Security.Cryptography.SHA512Managed())
        {
          byte[] textData = System.Text.Encoding.UTF8.GetBytes(content);
          byte[] hash = sha.ComputeHash(textData);
          contentHash = BitConverter.ToString(hash).Replace("-", String.Empty);
        }
        var preSign = timestamp + "https://api.bittrex.com/v3/orders/" + "POST" + contentHash;
        var hmac = new HMACSHA512(Encoding.UTF8.GetBytes(API_SECRET));
        var signature = BitConverter.ToString(hmac.ComputeHash(Encoding.UTF8.GetBytes(preSign))).ToLower().Replace("-", "");
        httpClient.DefaultRequestHeaders.Add("Accept", "application/json");
        httpClient.DefaultRequestHeaders.Add("Api-Key", API_KEY);
        httpClient.DefaultRequestHeaders.Add("Api-Signature", signature);
        httpClient.DefaultRequestHeaders.Add("Api-Timestamp", timestamp.ToString());
        httpClient.DefaultRequestHeaders.Add("Api-Content-Hash", contentHash);
        message=await httpClient.GetStringAsync(url).ConfigureAwait(false);//Exception!
      }
      catch { return null; }
      finally
      {
        httpClient.DefaultRequestHeaders.Remove("Accept");
        httpClient.DefaultRequestHeaders.Remove("Api-Key");
        httpClient.DefaultRequestHeaders.Remove("Api-Signature");
        httpClient.DefaultRequestHeaders.Remove("Api-Timestamp");
        httpClient.DefaultRequestHeaders.Remove("Api-Content-Hash");
      }
      return message;
    }

**Comment by bittrex-pete** [comment]
Hi @AndrNic - I'm guessing the problem is that you're trying to use httpClient.GetStringAsync. That's going to send an HTTP GET request. GETs just read things, they don't change the state of the system. You need to send a POST request to create an order.

**Comment by AndrNic** [comment]
Hi **bittrex-pete**
I tried it:
var values = new Dictionary<string, string>
{{"Accept", "application/json"},{"Api-Key", API_KEY},{"Api-Signature",signature },{"Api-Timestamp", timestamp.ToString() },
{"Api-Content-Hash", contentHash }};
        var c = new FormUrlEncodedContent(values);
        var response = await httpClient.PostAsync("https://api.bittrex.com/v3/orders", c);
returned 'Unauthorized'
I tried it:
using (var wb = new WebClient())
        {
          var data = new NameValueCollection();
          data["Accept"] = "application/json";
          data["Api-Key"] = API_KEY;
          data["Api-Signature"] = signature;
          data["Api-Timestamp"] = timestamp.ToString();
          data["Api-Content-Hash"] = contentHash;
          var response = wb.UploadValues(url, "POST", data);
          message = Encoding.UTF8.GetString(response);
        }
returned 'Unauthorized' too.
But authorization works well when requesting balance and existing orders. Maybe authorization is different for POST and GET?

**Comment by bittrex-pete** [comment]
It doesn't look like you're actually sending the request body in either of your new examples. I'd go back to your original and just replace

```
message=await httpClient.GetStringAsync(url).ConfigureAwait(false);//Exception!
```

with 

```
var response = await httpClient.PostAsync(url, new StringContent(content, Encoding.UTF8, "application/json"));
var responseBody = await response.Content.ReadAsStringAsync();
```

If something else is wrong you might get a helpful error message in the responseBody

**Comment by AndrNic** [comment]
**bittrex-pete**, thanks. The code works. A lot of fun in the New Year!
