### ISSUE TITLE
Please update the doc

### ISSUE THREAD

**Issue by BadgerTheAdger** [Bittrex/bittrex.github.io#218]
According to this: https://stackoverflow.com/a/65550927/13324352

**Comment by bittrex-pete** [comment]
Hi @BadgerTheAdger - It's already documented in this section https://bittrex.github.io/api/v3#topic-Placing-Orders 

Doesn't look like that error code is mentioned in the documentation though, so I'm going to add it to the list in the error codes section though with this as a possible cause.

**Comment by BadgerTheAdger** [comment]
Hey @bittrex-pete 

Objectively speaking, it's not documented. 
In the section you sent, it says that it's an example. It doesn't say that we can't try other values than those that are specified in the example.

It should be made clearer than it is now. 

in the NewOrder object, it says:

timeInForce: string  GOOD_TIL_CANCELLED, IMMEDIATE_OR_CANCEL, FILL_OR_KILL, POST_ONLY_GOOD_TIL_CANCELLED, BUY_NOW, INSTANT  
time in force

but should say: [IMMEDIATE_OR_CANCEL, FILL_OR_KILL,] for market order, .... for limit order, .... for ... order etc.

**Comment by bittrex-pete** [comment]
Please refer to the "Order types and time in force" subsection in the section that I linked.

![image](https://user-images.githubusercontent.com/50755685/103612403-350f5880-4ed9-11eb-830b-d733e60a443f.png)

**Comment by BadgerTheAdger** [comment]
Ok, I see, great stuff. However, from the UX perspective, one can observe the fact that 2 users in 2 days have had issues with the documentation. Perhaps add some point to your notes to revise the way this info is placed so it's more obvious to people? Perhaps add some warning like "please check this table" in the section that describes timeForce enum?

**Comment by BadgerTheAdger** [comment]
Thank you for your help, I'm just trying to make your doc even better with my suggestions. Please add these to notes so that no more people open issues like this ;)
