### ISSUE TITLE
Market Orders response does not return price data

### ISSUE THREAD

**Issue by BadgerTheAdger** [Bittrex/bittrex.github.io#219]
### REQUEST (POST orders)
___
{"marketSymbol":"BTC-USDT","direction":"BUY","type":"MARKET","timeInForce":"IMMEDIATE_OR_CANCEL","quantity":0.0015870980715080745061850110}
___
### RESPONSE
___
{"id":"21867112-6a9c-4e54-9d94-48327779dad5","marketSymbol":"BTC-USDT","direction":"BUY","type":"MARKET","quantity":"0.0015870980715080745061850110","timeInForce":"IMMEDIATE_OR_CANCEL","fillQuantity":"0.00158709","commission":"0.10564022","proceeds":"52.82011130","status":"CLOSED","createdAt":"2021-01-04T05:25:24.32Z","updatedAt":"2021-01-04T05:25:24.32Z","closedAt":"2021-01-04T05:25:24.32Z"}
___

How can I find out the price under which Bittrex executed my market order? 52.82 is clearly not the BTC-USDT price.

I need something like the average price of all fills. Then combined with the total filled quantity I can find out how much I spent on the order.

**Comment by bittrex-pete** [comment]
Hi @BadgerTheAdger -  commission + proceeds is the total amount you paid for a buy order.  Proceeds - commission is what you receive for a sell order. You could divide that by fillQuantity to get an average (including or not including commission depending on your requirements).  Or if you want the details of individual fills, you can get them here https://bittrex.github.io/api/v3#operation--orders--orderId--executions-get  though there is a slight delay before that information is available.

**Comment by BadgerTheAdger** [comment]
Hey @bittrex-pete 

Ok, that's great, thanks for the help.
Can you also include that info in the documentation? As it's not very obvious what proceeds etc. means.
The docs should be made more descriptive than they are now really. I understand that it may be obvious to you what 'proceeds' means but not to a regular user of your API. 

Can you please include the following info to avoid confusion:
- Proceeds: amount in the quote
- fillQuantity: amount in the base
- The average price of an order is calculated this way: Proceeds / fillQuantity

That will save people's time and yours correspondingly (you won't have to answer such a question sometime later again)

**Comment by bittrex-pete** [comment]
Yeah, I agree that the documentation on those fields is especially unhelpful. I'll make a note about getting it cleaned up the next time we update the docs.

**Comment by BadgerTheAdger** [comment]
Thanks for the help
