### ISSUE TITLE
after an order was closed, order data returned its state to be 'open'

### ISSUE THREAD

**Issue by BadgerTheAdger** [Bittrex/bittrex.github.io#223]
1. Posted limit order
2. Canceled limit order (successfuly)
3. called /orders/orderid info endpoint
4. it returned the order's state to be 'open'

### REQUEST /orders POST
{"marketSymbol":"BTC-USDT","direction":"BUY","type":"LIMIT","timeInForce":"GOOD_TIL_CANCELLED","limit":28341.54279,"quantity":0.00369423}
___### RESPONSE
{"id":"e950d5bc-ae51-4161-8158-04275cff1dea","marketSymbol":"BTC-USDT","direction":"BUY","type":"LIMIT","quantity":"0.00369423","limit":"28341.54279","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"0.00000000","commission":"0.00000000","proceeds":"0.00000000","status":"OPEN","createdAt":"2021-01-05T14:39:07.45Z","updatedAt":"2021-01-05T14:39:07.45Z"}
___
### REQUEST /market/cancel?uuid=e950d5bc-ae51-4161-8158-04275cff1dea GET
{"nonce":"1609857546.92414"}
___### RESPONSE
{"success":true,"message":"","result":null}
___
### REQUEST /orders/e950d5bc-ae51-4161-8158-04275cff1dea GET
null
___### RESPONSE
{"id":"e950d5bc-ae51-4161-8158-04275cff1dea","marketSymbol":"BTC-USDT","direction":"BUY","type":"LIMIT","quantity":"0.00369423","limit":"28341.54279000","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"0.00000000","commission":"0.00000000","proceeds":"0.00000000","status":"OPEN","createdAt":"2021-01-05T14:39:07.45Z","updatedAt":"2021-01-05T14:39:07.45Z"}

**Comment by bittrex-pete** [comment]
Similar issue here as with the others you've reported. However there's a much easier solution for this one.  I notice that you're using the v1 cancel API for some reason instead of the v3 one. If you switch to the v3 one, it will return the final state of the order in the response body so there won't be any need for the final GET request.

**Comment by BadgerTheAdger** [comment]
Ok since you have already added doco-fixes to your plans, I will mark this one as resolved - thanks for help
