### ISSUE TITLE
/v3/orders POST method in Python3 gives an INVALID_CONTENT_HASH error

### ISSUE THREAD

**Issue by prettyflyforabeeguy** [Bittrex/bittrex.github.io#224]
Hello,
I'm attempting a limit order in python3 and am getting a 401 Unauthorized with an invalid content hash error.  My code works great for any api with a _GET_ method, however it never works with a _POST_ method and content body that is not empty.   I've reviewed issues: [issue153](https://github.com/Bittrex/bittrex.github.io/issues/153) and [issue 160](https://github.com/Bittrex/bittrex.github.io/issues/160) which seem to be similar to my issue however none of the suggestions provided resolved this issue for me.

Can you tell me what I'm doing wrong when forming an api content hash that contains data?

`
import requests
import json
import hashlib
import hmac
import base64
import time

def new_Order():
    uri = 'https://api.bittrex.com/v3/orders'
    method = 'POST'
    apiKey = "some api key here"
    apiSecret = b'some api secret here'

    requestBody = {
        "marketSymbol": "DGB-USD",
        "direction": "SELL",
        "type":  "LIMIT",
        "quantity": "301.00",
        "limit": "0.03",
        "timeInForce": "GOOD_TIL_CANCELLED"
    }

    apiTimeStamp = str(int(time.time() * 1000))

    # create the content hash
    content = requestBody
        # Things I've tried that give the same error:
        # content = ''+json.dumps(requestBody, separators=(',',':'))
        # or 
        # content = str(requestBody)
        # contentHash = hashlib.sha512(content.encode()).hexdigest()  
    contentHash = hashlib.sha512(str(content).encode()).hexdigest()

    preSign = apiTimeStamp + uri + method + contentHash
    # create the signature
    signature = hmac.new(apiSecret, preSign.encode(), hashlib.sha512).hexdigest()

    headers = {
        'Accept' : 'application/json',
        'Api-Key' : apiKey,
        'Api-Timestamp' : apiTimeStamp,
        'Api-Content-Hash' : contentHash,
        'Api-Signature' : signature,
        'Content-Type' : 'application/json'
        }

    try:
        r = requests.post(uri, json=requestBody, headers=headers, timeout=11).json()
        return r
    except Exception as e:
        print(e)

response = new_Order()
print(response)
`
The output from response every time is:
{'code': 'INVALID_CONTENT_HASH'}

**Comment by prettyflyforabeeguy** [comment]
For what it's worth, I've also tried creating a long requestBody with escape characters but this just gives the same Invalid Content Hash error:
requestBody = "{\n \"marketSymbol\": \"DGB-USD\",\n \"direction\": \"SELL\",\n \"type\": \"LIMIT\", \n \"quantity\": \"301.00\",\n \"limit\": \"0.03\",\n \"timeInForce\": \"GOOD_TIL_CANCELLED\"\n}"

**Comment by bittrex-pete** [comment]
Hi @prettyflyforabeeguy, try this:

`contentHash = hashlib.sha512(bytes(json.dumps(requestBody), "utf-8")).hexdigest()`

**Comment by prettyflyforabeeguy** [comment]
@bittrex-pete  THANK YOU!!! That worked.
