### ISSUE TITLE
Help: DELETE /orders/{orderId} 

### ISSUE THREAD

**Issue by IHateNameStealers** [Bittrex/bittrex.github.io#226]
I've been at this for some time now, but can not get the DELETE /orders/open to work.
Basically I want to CANCEL an open order.

( see: https://bittrex.github.io/api/v3#operation--orders--orderId--delete )
According to this all that is needed to be posted is the _orderId_

I guess that the problems is the content as I get an error {"code":"INVALID_CONTENT_HASH"} 

Anyone here who can point me in the right direction (example is also welcome)

Thank you and please stay safe!

This is how my Curl part looks like

```
$apisecret ="is correct as it is working with other api calls";
$apikey ="is correct as it is working with other api calls";

$timestamp = time()*1000;
$url = "https://api.bittrex.com/v3/orders/cb2f249f-4a14-43a4-8076-gdjy45a27066";
$method = "DELETE";
$content = '{
     "id": "cb2f249f-4a14-43a4-8076-gdjy45a27066"
}';
$contentHash = hash('sha512', $content);
$subaccountId = "";
$preSign = $timestamp . $url . $method . $contentHash . $subaccountId;
$signature = hash_hmac('sha512', $preSign, $apisecret);

$headers = array(
"Accept: application/json",
"Content-Type: application/json",
"Api-Key: ".$apikey."",
"Api-Signature: ".$signature."",
"Api-Timestamp: ".$timestamp."",
"Api-Content-Hash: ".$contentHash.""
);

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);
$execResult = curl_exec($ch);
curl_close($ch);

```

**Comment by bittrex-pete** [comment]
Hi @IHateNameStealers - For DELETE orders/{orderId} the orderId is in the URL. There's no request body needed. You're probably getting INVALID_CONTENT_HASH because you're setting $content to something for the header/signature, but not actually sending it in the request.

**Comment by IHateNameStealers** [comment]
Thank you Pete,
When I set the $content to nothing (or remove) I still get the same error.

This problem is really driving me crazy.

**Comment by IHateNameStealers** [comment]
Hmmmm You got me here. 

How can I authenticate if I do not send a header/signature.

**Comment by IHateNameStealers** [comment]
I'm so new to this GitHub. Sorry. I closed it, but this is not what I wanted to do.
I still have this delete problem :-(

**Comment by IHateNameStealers** [comment]
I'm really having a hard time understanding this.'

This code works fine when using GET (ie: signature is okay), but when I use DELETE it gives me an invalid_signatue error.

```
<?php

include '_vars.php';

$timestamp = time()*1000;
$url = "https://api.bittrex.com/v3/orders/cb2f249f-4a14-43a4-8076-gdjy45a27066";

$method = "GET";
//$method = "DELETE";
$content = "";
$subaccountId = "";
$contentHash = hash('sha512', $content);
$preSign = $timestamp . $url . $method . $contentHash . $subaccountId;
$signature = hash_hmac('sha512', $preSign, $apisecret);

$headers = array(
"Accept: application/json",
"Content-Type: application/json",
"Api-Key: ".$apikey."",
"Api-Signature: ".$signature."",
"Api-Timestamp: ".$timestamp."",
"Api-Content-Hash: ".$contentHash.""
);

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);

$execResult = curl_exec($ch);
curl_close($ch);
echo $execResult;

?>
```

**Comment by IHateNameStealers** [comment]
Pfff. Got it working.
Needed to add: 
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");

**Comment by mudol22** [comment]
Hi, i have this problem too, new order working, balance working, but DELETE not working, have same error invalid signature, after add this line curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE"); i have error:
`array(1) {
  ["message"]=>
  string(61) "The requested resource does not support http method 'DELETE'."
}`

this is all my code:
`$url = "https://api.bittrex.com/v3/orders/?orderId=af5f8f7f-b53a-41e3-9295-e78XXXXXXX";
$method = "DELETE";
$content = "";
$subaccountId = "";
$contentHash = hash('sha512', $content);
$preSign = $timestamp . $url . $method . $contentHash . $subaccountId;
$signature = hash_hmac('sha512', $preSign, $apisecret);

$headers = array(
"Accept: application/json",
"Content-Type: application/json",
"Api-Key: ".$apikey."",
"Api-Signature: ".$signature."",
"Api-Timestamp: ".$timestamp."",
"Api-Content-Hash: ".$contentHash.""
);

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);
$execResult3 = curl_exec($ch);
curl_close($ch);`
