### ISSUE TITLE
invalid signatures based upon JS code 

### ISSUE THREAD

**Issue by JattJames** [Bittrex/bittrex.github.io#227]
Hi, i am using the website code and still getting invalid_signatures,  why so, any clue 

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/hmac-sha512.min.js"></script>
<script>
	var content = "";
	var contentHash = CryptoJS.SHA512(content).toString(CryptoJS.enc.Hex);
	document.getElementById('hash').value = contentHash;
	var method = 'GET';
	var timestamp = new Date().getTime();
	var uri = 'https://api.bittrex.com/v3/balances';
	var preSign = [timestamp, uri, method, contentHash].join('');
	var signature = CryptoJS.HmacSHA512(preSign, '...api_secret_hidden...').toString(CryptoJS.enc.Hex);
	document.getElementById('timestamp').value = timestamp;
	document.getElementById('signature').value = signature;
</script>	
```

error i get is 401 unauthorized in my http call and also in the response of http, it says invalid_signatures 

what is wrong i am doing

**Comment by bittrex-pete** [comment]
Hi @JattJames - nothing is jumping out at me as obviously wrong looking at the code you shared. How are you making the request? Are you sure that the required headers are being populated with the values you computed and sent?

**Comment by JattJames** [comment]
@bittrex-pete : Yes, I am passing all the headers to the server side to make the request, I am using JAVA in the backend, so before i convert the code to java, i tried to run with JS to make sure i have the valid headers and when passes it actually gives me result, but i am ending at this error. 

If you want I am not sure but can you show me a sample with demo key with the above code as working, because i had tried everything i could think of but nothing seems working.. 

and apart from that one doubt i have is am i suing correct cryptoJS file, how do i verify that what API is using is the same i have, probably that could be amisfit

**Comment by bittrex-pete** [comment]
The cryptoJs file that you're using looks fine to me. Here's a fancier version of your example that I've verified is giving me the correct values. I think its output is the same as your example, but it lets you play around with the values a bit more. 

```
<html>
  <head>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/hmac-sha512.min.js"></script>
  </head>
  <body>
    Content (request body):<br />
    <textarea id="contentInput" rows="6" cols="50" oninput="hash()" onpropertychange="hash()"></textarea><br />
    <br />
    Api-Content-Hash:<br />
    <span id="hashOutput"></span>
    <br />
    <br />
    Http Verb:<br />
    <input id="verbInput" type="text" value="GET" oninput="sign()" /><br />
    Uri:<br />
    <input id="uriInput" type="text" oninput="sign()" value="https://api.bittrex.com/v3/balances" /><br />
    Timestamp:<br />
    <input id="timeInput" type="text" oninput="sign()" /><br />
    Api Key Secret:<br />
    <input id="secretInput" type="text" oninput="sign()" value="" />
    <br />
    <br />
    Pre-signed value:<br />
    <span id="presignOutput"></span>
    <br />
    <br />
    Api-Signature:<br />
    <span id="signOutput"></span>
    <script type="text/javascript">
      function hash() {
        var content = document.getElementById("contentInput").value;
        var contentHash = CryptoJS.SHA512(content).toString(CryptoJS.enc.Hex);
        document.getElementById("hashOutput").innerText = contentHash;
        sign();
      }

      function sign() {
        var contentHash = document.getElementById("hashOutput").innerText;
        var timestamp = document.getElementById("timeInput").value;
        var uri = document.getElementById("uriInput").value;
        var method = document.getElementById("verbInput").value;
        var preSign = [timestamp, uri, method, contentHash].join("");
        document.getElementById("presignOutput").innerText = preSign;

        var apiSecret = document.getElementById("secretInput").value;
        var signature = CryptoJS.HmacSHA512(preSign, apiSecret).toString(CryptoJS.enc.Hex);
        document.getElementById("signOutput").innerText = signature;
      }

      document.getElementById("contentInput").value = "";
      document.getElementById("timeInput").value = new Date().getTime();
      hash();
    </script>
  </body>
</html>
```

**Comment by JattJames** [comment]
you mentioned you were able to verify it, i tried but for me if i pass empty content i get this error 

 {"code":"INVALID_CONTENT_HASH"}

**Comment by JattJames** [comment]
are there any dummy apikey and apisecret which i can play with

**Comment by bittrex-pete** [comment]
Unfortunately there aren't any dummy apikeys and secrets to play with. That's a good idea though. The correct hash for a request with no body is `cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e` which is what the example I gave above generates for the empty string. The INVALID_CONTENT_HASH error code is generated before the signature check by comparing the hash of the request body to the content of the Api-Content-Hash. So if you're getting INVALID_CONTENT_HASH when trying to send that value then either the header isn't being sent properly or there's something in the request body. Assuming you're doing a GET there shouldn't be a request body, so that would mean something is up with your Api-Content-Hash header.

When you get INVALID_SIGNATURE that means that the content hash is good but you either didn't send a signature or the signature you sent doesn't match what's expected based on the other headers and your api secret.

**Comment by JattJames** [comment]
I did as you mentioned and also added the keys but i am keep getting the INVALID_SIGNATURE , i literally tried everything i could but i am still getting invalid signature, i am not sure what wrong i am doing here 

i can put it online for you to cross check if you want,

**Comment by bittrex-pete** [comment]
If you share the part of your code that is building and sending the request I'm happy to take a look at it for you

**Comment by JattJames** [comment]
Can you give me you private message or email I will share the link as the keys will be there I do not want to expose publicly

**Comment by bittrex-pete** [comment]
I'd rather not have access to your keys. It would be better to just post a little snippet of your request sending code. Speaking of the keys, have you double-checked on the website that your API key is still valid? If you reset 2fa or something like that it will reset your keys. If you haven't already, maybe try generating a new key/secret?

**Comment by JattJames** [comment]
here is the link 

http://steadysoft.in/bittrex/bitrix.cfm

i am using ColdFusion at the server so the values are passed to the server, you will see how it is passed and the #form.timeinput# does actually inputs the time

**Comment by bittrex-pete** [comment]
Looks like this is basically what I had shared above, but wrapped up in a form that sends your results to your server. So you're doing this stuff client-side and then bouncing the results through your server and over to our API? Something is probably getting messed up with the headers on the request from your server to us.

**Comment by JattJames** [comment]
i tried the same thing on the postman api, it has issues, i was not able to do in postman api, is there any collection available for postman api to run and check 

i posted the same code as yours just to make sure you enter your own apikey/secret and see if it gives you the results or it does the same, because all i am doing is form data sending to server side and it will process the data

**Comment by JattJames** [comment]
i even tried this: Version 1.1 but same issue invalid signatures 
https://github.com/iamlouisdoyle/PHP-Bittrex-API-Wrapper

**Comment by bittrex-pete** [comment]
Sure - here's a simple postman collection and environment. If you import these into postman and provide your api key and secret in the environment config everything should work. There an example unauthenticated GET, and authenticated GET, and an authenticated POST. The authentication code is on the pre-request script associated with the collection. There's some postman-specific stuff in there to deal with the potential for variables in the request body, etc., but it follows the same pattern we've been talking about

[Bittrex V3 Example.postman_collection.json.txt](https://github.com/Bittrex/bittrex.github.io/files/5852754/Bittrex.V3.Example.postman_collection.json.txt)

[Bittrex Environment.postman_environment.json.txt](https://github.com/Bittrex/bittrex.github.io/files/5852753/Bittrex.Environment.postman_environment.json.txt)

**Comment by JattJames** [comment]
something is really wrong with the api, i even tried postman, issues with nonce sometimes invalid signatures, there seems to be not even single library for v3 which shows that it works. anything i can check

**Comment by bittrex-pete** [comment]
I'm not sure how I can help. Thousands of people successfully use the v3 api every day. If you can't get postman to work, most likely there's something wrong with your api key and I'd suggest creating a new one and trying that. I'm not sure what issues with nonces you're referring to, but I assume it's socket related. There are some simple socket examples here: https://bittrex.github.io/api/v3#topic-Example-Socket-Clients
