### ISSUE TITLE
Questions about partially filled orders

### ISSUE THREAD

**Issue by sunchaser68** [Bittrex/bittrex.github.io#228]
Hi, i have a bot that places, for example, a order for 100 VLX for 30 USD. Let's imagine that the order is **partially filled** with 30 VLX.
I can find the partially filled order with 30 VLX in my history, but what happens to the order with remaining 70 VLX?

Also, my bot requires that the orders would go in **Completed** status only when it's completely filled, how can i use the APIs to satisfy this requirement?

**Comment by bittrex-pete** [comment]
Hi @sunchaser68 - that's how the API works already. Assuming you're placing a good-til-cancelled order, the order will remain open and you'll be able to get it on the REST api from the /orders/open endpoint until it's completely filled or cancelled.

**Comment by sunchaser68** [comment]
Hi @bittrex-pete I analyzed further the case. 

If i put a order with id #1 of 100 VLT, good-til-canceled, and it's partially filled:

- the order id #1 is marked as CLOSED with fillQuantity = 30. I managed to fix my problem by checking the status of order #1 and updating the quantity of the BUY order with the fillQuantity in my local database.

**Comment by bittrex-pete** [comment]
Seems to be working as expected for me. Are you sure your code didn't cancel that order? Looks like it was closed exactly 30 minutes after creation. It would be a surprising coincidence if the timing just worked out that way. I'd suggest trying to reproduce the behavior with a new order.

**Comment by sunchaser68** [comment]
Hi @bittrex-pete everything seems ok. I made a mistake in mapping.

I was mapping a OPEN order with fillQuantity > 0 as "open" while for my logic should have been mapped into "Partially Filled".
Because of this, I was canceling the order while i shouldn't.
