### ISSUE TITLE
QueryBalanceState - what am I missing?

### ISSUE THREAD

**Issue by zeilja** [Bittrex/bittrex.github.io#23]
Has anyone figured out QueryBalanceState? (I also asked this in slack) I can't get it working.
The only difference is that signalR sends this message id as string, but browser as int

```
{"H":"c2","M":"QueryBalanceState","A":[],"I":2}        browser
{"H":"c2","M":"QueryBalanceState","A":[],"I":"2"}    me (aka .net signalR library)
```
I get response as {"I":"2"}
Browser gets response as {"R":"info about all balances","I":"2"}

I do authenticate procedures before call. Currently I have no issues with other calls.
I can confirm that it's the same on beta and production socket.

**Comment by zeilja** [comment]
but the website is using such a call over websocket!

**Comment by laserlance** [comment]
I have no clue then. I'm just going by what is in the documentation.

**Comment by zeilja** [comment]
OK, we'll see what officials are saying. I believe that current documentation is not in finished state. :) Website executes this call when You click on Wallets (on top) when logged in.
