### ISSUE TITLE
15 minute candle interval?

### ISSUE THREAD

**Issue by IHateNameStealers** [Bittrex/bittrex.github.io#231]
Anyone here who might know how to get a 15 minute candle interval?

Simply using every 15th minute value from a 1 hour (HOUR_1) candle interval does not return the same value as when using the Bittrex 15 minute setting on the website.

Same with MINUTE_5 or MINUTE_1. I do not get the same result as when using the Bittrex 15 minute setting on the website.

**Comment by bittrex-pete** [comment]
The way the website does it is upscaling from the smaller increments.  One 15 minute candle would be built out of three 5 minute candles:

15 minute Open = Open from first 5 minute candle
15 minute High = The max High across all three 5 minute candles
15 minute Low = The min Low across all three 5 minute candles
15 minute Close = Close from the third 5 minute candle
15 minute Volume and QuoteVolume = The sum across all three 5 minute candles of Volume and QuoteVolume, respectively

**Comment by IHateNameStealers** [comment]
Understood, and thank you for the info.
I'm back coding again.

**Comment by IHateNameStealers** [comment]
Peter. I'm at this moment not interested in the 15 minute volume and quoteVolume, but I am interested in the Open, High and low.

So. Just to make sure what you are saying.

Is this correct?

15 minute Open: 0.43170000 (open from in this case object [1])
15 minute High: 0.43306000 (max high from in this case object [2])
15 minute Low: 0.42832000 (max low from in this case object [1])

```
Array
(
    [0] => stdClass Object
        (
            [startsAt] => 2021-02-04T08:00:00Z
            [open] => 0.42941000
            [high] => 0.42941000
            [low] => 0.42941000
            [close] => 0.42941000
            [volume] => 0
            [quoteVolume] => 0
        )

    [1] => stdClass Object
        (
            [startsAt] => 2021-02-04T07:55:00Z
            [open] => 0.43170000
            [high] => 0.43181000
            [low] => 0.42832000
            [close] => 0.42941000
            [volume] => 16535.16539613
            [quoteVolume] => 7111.98267189
        )

    [2] => stdClass Object
        (
            [startsAt] => 2021-02-04T07:50:00Z
            [open] => 0.43194000
            [high] => 0.43306000
            [low] => 0.43194000
            [close] => 0.43288000
            [volume] => 20348.95747827
            [quoteVolume] => 8809.78367616
        )

    [3] => stdClass Object
        (
            [startsAt] => 2021-02-04T07:45:00Z
            [open] => 0.43200000
            [high] => 0.43200000
            [low] => 0.43166000
            [close] => 0.43166000
            [volume] => 6209.07926626
            [quoteVolume] => 2681.72850209
        )

```

**Comment by bittrex-pete** [comment]
Given that array as input, the output for 15 minute candles I would expect is:

```
Array
(
    [0] => stdClass Object  <just a copy of obj0 since there's only one input candle in that 15 minute range>
        (
            [startsAt] => 2021-02-04T08:00:00Z
            [open] => 0.42941000
            [high] => 0.42941000
            [low] => 0.42941000
            [close] => 0.42941000
            [volume] => 0
            [quoteVolume] => 0
        )

    [1] => stdClass Object
        (
            [startsAt] => 2021-02-04T07:45:00Z
            [open] => 0.43200000 <from obj3>
            [high] => 0.43306000 <max across objs 1-3>
            [low] => 0.42832000  <min across objs 1-3>
            [close] => 0.42941000 <from obj1>
            [volume] => <whatever the sum of objs 1-3 are>
            [quoteVolume] => <whatever the sum of objs 1-3 are>
        )
)
```

**Comment by IHateNameStealers** [comment]
Once again thank you Pete.
I think I understand now.

**Comment by IHateNameStealers** [comment]
Okay. Got it working and I am getting the same results as Bittrex is showing for the 15 minute line!
Only values wrong are for the last record when time is not ending at 00/15/30 or 45

Example:  Lets say the time is 09:55. 

What time frame is than used to calculate the result for 09:55?
Do you use 09:45, 0950, 09:55 ??
Or just 09:45 and 09;55?

**Comment by bittrex-pete** [comment]
It should still be using  09:45, 0950, and 09:55. However the completed 09:55 candle won't be available yet, so they'll be using the candles websocket stream to get the most recent values for the 09:55 candle.

**Comment by IHateNameStealers** [comment]
Aha... Now I get it.
I was missing the "09:55" candle for some seconds, and this was messing the calculations up :-/

Have to look into using the websocket stream now.

Thank you for your help, and have a nice weekend.

**Comment by bittrex-pete** [comment]
Good luck! Hope you have a nice weekend as well
