### ISSUE TITLE
lower the 50k sat limit

### ISSUE THREAD

**Issue by samthomson** [Bittrex/bittrex.github.io#232]
Have you thought to lower the 50k sat DUST_TRADE_DISALLOWED_MIN_VALUE error threshold since btc has increased a lot since that limit has been there?

**Comment by bittrex-pete** [comment]
It's not something we've discussed, but it is a good point. Especially if the BTC price continues to go up (🤞). Thanks for the feedback!

**Comment by PopeNobody** [comment]
This would be a huge help!

**Comment by bittrex-pete** [comment]
@samthomson @PopeNobody Good news! The limit has been reduced to 10k sats.

**Comment by samthomson** [comment]
@bittrex-pete thanks a lot, much appreciated :pray: :100:
