### ISSUE TITLE
TRAILINGORDER error 400

### ISSUE THREAD

**Issue by incobart** [Bittrex/bittrex.github.io#233]
Hi, anybody can help ?
I put following request but get error response ...

https://api.bittrex.com/v3/Orders         {"marketSymbol":"MANA-BTC","operand":"LTE","trailingStopPercent":-0.2,"quantity":100,"direction":"SELL","type":"MARKET","timeInForce":"GOOD_TIL_CANCELLED"}
{"error_nr":400,"error_txt":"HTTP-Bad Request","response_txt":{"code":"BAD_REQUEST","detail":"Refer to the data field for specific field validation failures or extra fields in the body that were rejected.","data":{"newOrder.operand":["Could not find member 'operand' on object of type 'NewOrder'. Path 'operand', line 1, position 37."],"newOrder.trailingStopPercent":["Could not find member 'trailingStopPercent' on object of type 'NewOrder'. Path 'trailingStopPercent', line 1, position 65."]}}}

**Comment by incobart** [comment]
I see a mistale with good till cancelled, but that is not the issue

**Comment by bittrex-pete** [comment]
Hi @incobart - regular orders (like market and limit) are handled separately in the API from stop orders (which we call conditional orders).  Looks like you're trying to create a trailing stop that triggers a market order when tripped. If so the request should be something like

`POST https://api.bittrex.com/v3/conditional-orders`

```
{
  "marketSymbol": "MANA-BTC",
  "operand": "LTE",
  "trailingStopPercent": 0.2,
  "orderToCreate": {
    "marketSymbol": "MANA-BTC",
    "direction": "SELL",
    "type": "MARKET",
    "quantity": 100,
    "timeInForce": "IMMEDIATE_OR_CANCEL"
  }
}
```

**Comment by incobart** [comment]
Hi Pete,

Thanks for your great help
I had to puzzel a bit but could finally make it work.
although, now I get this :-s
https://api.bittrex.com/v3/conditional-orders {"marketSymbol":"TRAC-BTC","operand":"LTE","trailingStopPercent":-0.15,"orderToCreate":{"marketSymbol":"TRAC-BTC","quantity":175.43859649,"direction":"SELL","type":"MARKET","timeInForce":"IMMEDIATE_OR_CANCEL"}}
{"error_nr":400,"error_txt":"HTTP-Bad Request","response_txt":{"code":"INVALID_TRAILING_STOP"}}

any suggestion ?
Thanks

**Comment by incobart** [comment]
quick update, it must have to do with the -0.15 because with the 0.15 it works fine, but I want my stoploss under the price, not above :-S

**Comment by bittrex-pete** [comment]
It's implied by the operand field. Operand = LTE will result in a trailing stop that triggers when the last price is down trailingStopPercent from the high. GTE will result in it triggering when it's up from the low.

See the Trigger Conditions subsection of this topic: https://bittrex.github.io/api/v3#topic-Placing-Conditional-Orders
