### ISSUE TITLE
How to know whether it is a buy or sell execution?

### ISSUE THREAD

**Issue by 1337sc** [Bittrex/bittrex.github.io#234]
There are only the fields on the screenshot come as responses for /executions request. How to know the side of the execution (buy or sell)?
![image](https://user-images.githubusercontent.com/46076326/107395313-5c26fe80-6b05-11eb-9af2-67a9518b7730.png)

**Comment by bittrex-pete** [comment]
You can tell if it's maker or taker using the isTaker field, but obviously that's different from buy/sell.  To get buy/sell you'd need to cross reference with the order based on the orderId.

**Comment by 1337sc** [comment]
Thank you for the answer. As far as I understand it causes a n+1 problem, so could you add the isBuy field if possible?

**Comment by bittrex-pete** [comment]
I'm happy to log it with the team as a feature request.

One other thing that might be helpful depending on what you're trying to do: there's another object called [Trade](https://bittrex.github.io/api/v3#/definitions/Trade) that is an unauthenticated/public view of the trades taking place on the market. Like executions you can get them from [REST](https://bittrex.github.io/api/v3#operation--markets--marketSymbol--trades-get) or the [socket](https://bittrex.github.io/api/v3#method-Trade). It doesn't have all the same information as Execution, but it does include a takerSide field which will be either BUY or SELL.
