### ISSUE TITLE
How to get ticker, trade, candle using Bittrex socket?

### ISSUE THREAD

**Issue by codelover1110** [Bittrex/bittrex.github.io#235]
Hi, Everyone.
I'd like to try to get ticker, trade, candle using python socket.
But I can't know how to do that.
Looking for you guy's help.
Regards

**Comment by bittrex-pete** [comment]
Hey @codelover1110 - take a look at this example. It doesn't do those channels specifically, but it should give you an idea of how to get started: https://bittrex.github.io/samples/V3WebsocketExample.py

**Comment by codelover1110** [comment]
Hi, @cyrus19909 
Appreciate to your reply. I've reviewed the code you sent and, it seems to be pretty good to get the trade data.
By the way, it doesn't work getting the orderbook.
What do you think of it?
do you have any idea?
Looking forward to hearing from you.
Thanks

**Comment by bittrex-pete** [comment]
It should be something like this. Try modifying the subscribe function as follows:

```
async def subscribe():
  HUB.client.on('heartbeat', on_heartbeat)
  HUB.client.on('trade', on_trade)
  HUB.client.on('balance', on_balance)
  **HUB.client.on('orderBook', on_orderBook)**
  channels = [
    'heartbeat',
    'trade_BTC-USD',
    'balance',
    **'orderbook_BTC-USD_25'**
  ]
```

And add an on_orderBook function like:

```
async def on_orderBook(msg):
  await print_message('Order Book', msg)
```

**Comment by codelover1110** [comment]
Hi, @cyrus19909 
Thank you so much for your reply.
I've tried to get the orderbook data as you mentioned.
![image](https://user-images.githubusercontent.com/59010875/109921511-023fd180-7c8a-11eb-842a-e0a03d0b95ea.png)
but couldn't get the data yet.
could you help me with this?
thanks again.

**Comment by codelover1110** [comment]
PS: I've tried to get the data such as trade, candle, ticker as you mentioned, and it seems to be worked properly some time.
But only couldn't get the orderbook data. it seems to be shown holding status.
How to handle this holding status?

**Comment by bittrex-pete** [comment]
Not sure what problem you're having. Only thing that comes to mind is that the message names are case sensitive in Python make sure the B is capital in this line:

HUB.client.on('order**B**ook', on_orderBook)

If that's not the issue, not sure. If you post your code I can see if anything jumps out at me.

**Comment by codelover1110** [comment]
Hi, @cyrus19909 . 
Thank you. Thank you so much. It works for me right now.
You are very cool. 
It was mistake `HUB.client.on('orderbook', on_orderBook)`
Thanks again.

**Comment by codelover1110** [comment]
By the way, Is it possible to handle the issues on the websocket?
I can't understand why it couldn't show me the error message.
How can handle it?
And I've tried to run the  code to get the trade data all the night. But after a few hours, it couldn't be got to any data from websocket. It seemed to be keeping the holding status also. So I've restarted the script again, and it started to work again.
Why does this trouble I can see?
Could you help me with this?
Thank you.
