### ISSUE TITLE
I can't create new order using V3 API

### ISSUE THREAD

**Issue by nareshsoni02** [Bittrex/bittrex.github.io#236]
Hi

Could you please help me create new order? All other API works fine except create order. I am using v3 API.
I am getting "400 Bad Request". Response doesn't give much details what parameter is missing or wrong.

Java Code:-
String url ="https://api.bittrex.com/v3/orders";
        String method ="POST";
        JsonObject jsonInput = new JsonObject();

        jsonInput.addProperty("marketSymbol", "EMC2-BTC");
        jsonInput.addProperty("direction", "SELL");
        jsonInput.addProperty("type", "LIMIT");
        jsonInput.addProperty("quantity", 100.0);
        jsonInput.addProperty("limit", 0.010000001);
        jsonInput.addProperty("timeInForce", "IMMEDIATE_OR_CANCEL");
            jsonInput.addProperty("clientOrderId", UUID.randomUUID().toString());
            jsonInput.addProperty("useAwards", false);
        String asString = jsonInput.toString();
        StringEntity entity = new StringEntity(asString, ContentType.APPLICATION_JSON);

        HttpClient httpClient = HttpClientBuilder.create().build();
        HttpPost request = new HttpPost(url);
        request.setEntity(entity);

        String timestamp =getTimestamp();
        String contentHash = getContentHash(asString);
        String apiSecret = “API_SECRET”;
        String preSignature = getPresignature(timestamp, url, method, contentHash);
        String signature = getSignature(preSignature,apiSecret);
        request.setHeader("Api-Key", "API_SECRET");
        request.setHeader("Api-Timestamp", timestamp);
        request.setHeader("Api-Content-Hash", contentHash);
        request.setHeader("Api-Signature", signature);
        request.setHeader("Accept", "application/json");
        request.setHeader("Content-Type", "application/json; utf-8");

        HttpResponse response = httpClient.execute(request);

        System.out.println(response.getStatusLine().getStatusCode());
        System.out.println(response.getStatusLine().getReasonPhrase());

**Comment by bittrex-pete** [comment]
What is in the response body? There should be an error code in there that says what's going wrong.

**Comment by nareshsoni02** [comment]
After printing response :-
System.out.println(response);


output:-
HttpResponseProxy{HTTP/1.1 400 Bad Request [Date: Sat, 13 Feb 2021 18:51:02 GMT, Content-Type: application/json; charset=utf-8, Content-Length: 37, Connection: keep-alive, Set-Cookie: __cfduid=de792e0a001f5de5fb5b135c4d0886a611613242262; expires=Mon, 15-Mar-21 18:51:02 GMT; path=/; domain=.bittrex.com; HttpOnly; SameSite=Lax; Secure, Request-Id: 078adf69-e46d-494a-b84d-e0c81a076513, Strict-Transport-Security: max-age=15768000, X-XSS-Protection: 1; mode=block, X-Content-Type-Options: nosniff, X-Download-Options: noopen, CF-Cache-Status: DYNAMIC, cf-request-id: 083e547a36000006a27733a000000001, Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct", Server: cloudflare, CF-RAY: 6210bd09e83606a2-LHR] ResponseEntityProxy{[Content-Type: application/json; charset=utf-8,Content-Length: 37,Chunked: false]}}

**Comment by nareshsoni02** [comment]
Thanks for looking into it. Appreciate your prompt response. Resolved it by adding EntityUtils.toString(response.getEntity()); It gives detailed error message.
