### ISSUE TITLE
Why I failed to get a new api keys

### ISSUE THREAD

**Issue by simouzhu** [Bittrex/bittrex.github.io#237]
![image](https://user-images.githubusercontent.com/9150353/108092829-0d0a3c00-70b8-11eb-8999-2d54d5051245.png)

In order to order better, we want to get a new api keys to start our trading, buy we failed.
Please give me some suggest. 
Thank you.

**Comment by bittrex-pete** [comment]
What was the failure?

**Comment by simouzhu** [comment]
In this page，I click three buttons and save it,but I failed get the api keys.

**Comment by bittrex-pete** [comment]
Changing the Read Info, Trade, and Withdraw toggles only changes the permissions on the existing API key. It does not create a new one.  To create a new one, click on Add new key... (lower left side, below Key in your screenshot), then set the permissions on it as desired and then click save.

**Comment by simouzhu** [comment]
Just as you say,I add a new api and save it,but I got nothing except this page. When I refresh this page, I  got the empty page.

**Comment by bittrex-pete** [comment]
Any errors in the browser developer console? What browser/version are you running?

**Comment by simouzhu** [comment]
![image](https://user-images.githubusercontent.com/9150353/108141656-1965b780-70ff-11eb-9e22-824e9cd1c47a.png)
Nothing.

**Comment by simouzhu** [comment]
https://global.bittrex.com/Manage?view=api 
I requested on this url.

**Comment by simouzhu** [comment]
I got it when I had succeed to verify.
