### ISSUE TITLE
Withdrawing USD via API returns INVALID_ADDRESS

### ISSUE THREAD

**Issue by lukechampine** [Bittrex/bittrex.github.io#241]
When I `GET /withdrawals/closed`, I can view USD withdrawals. They appear to use a special UUID for the `cryptoAddress` field. However, when I try to create a new USD withdrawal, using the same UUID as the `cryptoAddress`, the server returns `INVALID_ADDRESS`.

Is it currently possible to withdraw USD via the API? If not, is the functionality planned, or will wires always need to be initiated manually? Thanks.

**Comment by bittrex-pete** [comment]
Hi @lukechampine - it is a gap currently. It's on our list to resolve though.

**Comment by bittrex-pete** [comment]
Hi @lukechampine - this should be resolved now

**Comment by lukechampine** [comment]
Excellent, thanks!
