### ISSUE TITLE
Market Pair MAID-BTC Issue

### ISSUE THREAD

**Issue by mchalise** [Bittrex/bittrex.github.io#247]
endpoint:  GET orders/closed

This endpoint is not giving MAID-BTC data via API but CSV has those data. I don't think this pair is delisted as API is showing this pair as active. 

Can someone help me here.

**Comment by mchalise** [comment]
`{
"symbol": "MAID-BTC",
"baseCurrencySymbol": "MAID",
"quoteCurrencySymbol": "BTC",
"minTradeSize": "16.35055592",
"precision": 8,
"status": "ONLINE",
"createdAt": "2016-01-18T20:38:22.707Z",
"prohibitedIn": [
"US"
],
"associatedTermsOfService": [],
"tags": []
},`


looks like this PAIR is prohibited in the US. How to fetch those PAIR history?

**Comment by mchalise** [comment]
Could someone enable those prohibited pair in GET **orders/closed** . As it's only a GET request.  Or is there any other endpoint or way to fetch those txns. Thanks in Advance.

**Comment by bittrex-pete** [comment]
Hi @mchalise - I've been trying to reproduce this issue, but I haven't had any luck. The best next step would be for somebody on our support team to look at the specifics of your account to figure out what's going on. I'm not able to do account-specific support here unfortunately, so I'd suggest filing a support ticket at https://support.bittrex.com for help.  Sorry for the inconvenience.

**Comment by mchalise** [comment]
Ok submitted a support ticket. #2147449 @bittrex-pete. if you need API keys, lemme know there. It will help you replicate the issue.
