### ISSUE TITLE
v3 Summaries no Last Price

### ISSUE THREAD

**Issue by Drungle** [Bittrex/bittrex.github.io#248]
Just curious why there is no last price in the 24h preview when pretty much every other exchange has high, low, last included in theirs? Am I missing something? I hope this is fixed before 1.1 is removed
https://api.bittrex.com/v3/markets/summaries
 -Schema
[
  {
    "symbol": "string",
    "high": "number (double)",
    "low": "number (double)",
    "volume": "number (double)",
    "quoteVolume": "number (double)",
    "percentChange": "number (double)",
    "updatedAt": "string (date-time)"
  }
]

**Comment by bittrex-pete** [comment]
It got moved over to https://bittrex.github.io/api/v3#operation--markets-tickers-get in v3 with best bid and ask
