### ISSUE TITLE
4 hour timeline (candle interval)?

### ISSUE THREAD

**Issue by IHateNameStealers** [Bittrex/bittrex.github.io#249]
Someone here who can explain how the 4 hour candle is made?
Is it made from four 1 hour candles, and used the average of open, high, low, close, volume and quoteVolume?
Or is it the same principle as the 15 minute candle interval (explained by Pete some days ago.)

> The way the website does it is upscaling from the smaller increments. One 15 minute candle would be built out of three 5 minute candles:
> 15 minute Open = Open from first 5 minute candle
> 15 minute High = The max High across all three 5 minute candles
> 15 minute Low = The min Low across all three 5 minute candles
> 15 minute Close = Close from the third 5 minute candle
> 15 minute Volume and QuoteVolume = The sum across all three 5 minute candles of Volume and QuoteVolume, respectively

Thank you for any info on this, and have a nice weekend.

**Comment by bittrex-pete** [comment]
It's the same principles.  A 4-hour candle would be built out of four 1-hour candles using basically the same rules as you quoted.

**Comment by IHateNameStealers** [comment]
Thanks Pete.
Great! Will be testing it tomorrow.
Have a nice weekend!
