### ISSUE TITLE
Withdrawal precision

### ISSUE THREAD

**Issue by beardsleysmind** [Bittrex/bittrex.github.io#252]
Is there any way to know the required precision for the withdrawal amount via bittrex api?
And will I get an error if I try to withdraw 0.123456789...n EOS (or any other currency)?

**Comment by bittrex-pete** [comment]
@beardsleysmind  For all crypto withdrawals the precision is 1 satoshi (10^-8). Additional precision is truncated. Also note that the transaction fee comes out of what the amount that you withdrew. So for example if you tried to withdraw 0.123456789 of a crypto with a txFee of 0.00005 then you would pay 0.00005 and the amount sent would be 0.12340678.  Withdrawals need to be >3x the txFee or you'll get a WITHDRAWAL_TOO_SMALL error.

**Comment by beardsleysmind** [comment]
Thank you!
