### ISSUE TITLE
HTTP 403 error response

### ISSUE THREAD

**Issue by gdast** [Bittrex/bittrex.github.io#255]
I am unable to access the API endpoints using my API keys from my Java client to any of the GET API REST/JSON endpoints. Presently I'm trying to access the https://api.bittrex.com/api/v3/ping endpoint (worked ok with v1.1) but I keep getting the error response:

Server returned HTTP response code: 403 for URL: https://api.bittrex.com/api/v3/ping

Which according to the API documentation means "The provided api key is not authorized to perform the requested operation (example: attempting to trade with an api key not authorized to make trades)". So I changed to using the API/SECRET KEYs with full access and they still generate the same HTTP 403 error.

I double checked my SHA512 and HMACSHA512 were generated correctly based on my inputs using online generators and still get the HTTP 403 error.

I've tried different endpoints and alternate API and SECRET keys with full access (trades, withdrawals). I even deleted all my old keys and recreated new keys but still the same error.

Here is my section of java code that handles the Bittrex API call:

private static void sendRequestToBittrex(String url) {       
      try {
	String epoch = Long.toString(System.currentTimeMillis());
	String method = "GET";
	String subAccountId = "";
	
	String contentHash = getHashSHA512("","");

	String preSign = epoch + url + method + contentHash + subAccountId;
	String signature = Hex.encodeHexString(hmacSha512(preSign, SECRET_KEY));

	System.out.println("epoch "+epoch);
	System.out.println("content hash "+contentHash);
	System.out.println("preSign "+preSign);
	System.out.println("signature "+signature);

	HttpsURLConnection connection = (HttpsURLConnection) new URL(url).openConnection();
      connection.setSSLSocketFactory(sslContext.getSocketFactory());
      
      // Add headers
      connection.setRequestMethod(method);
      connection.addRequestProperty("Api-Key", API_KEY);
      connection.addRequestProperty("Api-Timestamp", epoch);
      connection.addRequestProperty("Api-Content-Hash", contentHash);
      connection.addRequestProperty("Api-Signature", signature);
      connection.addRequestProperty("Accept", "application/json");
      connection.addRequestProperty("Content-Type", "application/json");

      // Send data      
      InputStream is = connection.getInputStream();   <---- THIS LINE THROWS THE HTTP 403 EXCEPTION
      InputStreamReader isr = new InputStreamReader(is);
      BufferedReader br = new BufferedReader(isr);

      String response;

      System.out.println("Checking response...");
      while ((response = br.readLine()) != null) {
        System.out.println(response.toString());
      }

      br.close();
      } catch (FileNotFoundException fe) {
        fe.printStackTrace();
      } catch (IOException ioe) {
        ioe.printStackTrace();
      } catch (Exception e) {
        e.printStackTrace();
      }  
    }

public static String getHashSHA512(String StringToHash, String salt){
        String generatedPassword = null;
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-512");
            md.update(salt.getBytes(StandardCharsets.UTF_8));
            byte[] bytes = md.digest(StringToHash.getBytes(StandardCharsets.UTF_8));
            generatedPassword = Hex.encodeHexString(bytes);
        }
        catch (NoSuchAlgorithmException e){
            e.printStackTrace();
        }
        return generatedPassword;
    }

    public static byte[] hmacSha512(String value, String key){
    try {
        SecretKeySpec keySpec = new SecretKeySpec(
                key.getBytes(DEFAULT_ENCODING),
                HMAC_SHA512);
 
        Mac mac = Mac.getInstance(HMAC_SHA512);
        mac.init(keySpec);
        return mac.doFinal(value.getBytes(DEFAULT_ENCODING));
 
    } catch (NoSuchAlgorithmException e) {
        throw new RuntimeException(e);
    } catch (InvalidKeyException e) {
        throw new RuntimeException(e);
    } catch (UnsupportedEncodingException e) {
        throw new RuntimeException(e);
    }

**Comment by bittrex-pete** [comment]
Not sure if this is the only issue, but one thing that jumps out at me is that the URL you're using is incorrect.  Should be

https://api.bittrex.com/v3/ping

Ping is actually an unauthenticated endpoint so you can even get to it by just clicking that link in your browser.

**Comment by gdast** [comment]
Thanks for that. I must have missed it when I was copy and pasting my old v1.1 code to v3.

However calling https://api.bittrex.com/v3/ping is now giving a HTTP 401 error response instead (which I guess is a small improvement ;):

java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.bittrex.com/v3/ping

The interesting thing is that if I call another unauthenticated endpoint like /currencies (with the same API/SECRET key) that works ok.

But trying other authenticated endpoints (like GET /account) also yields a 401 HTTP response code, which according to Bittrex API docs means:

"The request failed to authenticate (example: a valid api key was not included in your request header)"

I'm pretty confident my keys are correct and I've tried new keys without success. So not sure why the API isn't happy with the way I'm authenticating my request via the headers.

The Api-Key header is simply a copy and paste of my API_KEY, so that's unlikely to be the cause (?). I suspect it might be the Api-Signature as that requires more work to create by signing the pre-sign string with the  HmacSHA512 using my secret key. 

However, I checked that my pre-sign string is being correctly signed by my secret key via HmacSH512 by using online HmacSH512 generator at: 

https://www.freeformatter.com/hmac-generator.html#ad-output

The signature this website independently generated matched that of my Java client for the same pre-sign string and secret key inputs.

**Comment by bittrex-pete** [comment]
There's probably an error code in the response body you're getting back with the 401. That would be a good clue to track down the problem. I'm going to guess it's a problem with how you're hashing. If so the error code will be INVALID_CONTENT_HASH.  What's the hash you get for the empty string?  Should be  

`cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e`

That's the correct value for all GET requests.

**Comment by gdast** [comment]
Yeah since my request body is empty the content hash I generate using my getHashSHA512() method generates the same content hash. Here's the content hash and pre-sign string I generate:

content hash f90ddd77e400dfe6a3fcf479b00b1ee29e7015c5bb8cd70f5f15b4886cc339275ff553fc8a053f8ddc7324f45168cffaf81f8c3ac93996f6536eef38e5e40768

preSign 1618412983696https://api.bittrex.com/v3/account/volumeGETf90ddd77e400dfe6a3fcf479b00b1ee29e7015c5bb8cd70f5f15b4886cc339275ff553fc8a053f8ddc7324f45168cffaf81f8c3ac93996f6536eef38e5e40768

Oddly today without me making any further changes to my Java client code it has started working by itself. I've tested it on the various GET endpoint and seems to be all working correctly now. So many thanks for your help!

I've also added error checking to my java client to print error codes and this now correctly prints the errors codes if I deliberately send the wrong content hash, api key or signature. Here's the working Java client code for the benefit of others:

####### START ##########

private static void sendRequestToBittrex(String url) {       
      try {
	String epoch = Long.toString(System.currentTimeMillis());
	String method = "GET";
	String subAccountId = "";

	String contentHash = getHashSHA512("","");
	String preSign = epoch + url + method + contentHash + subAccountId;
	String signature = Hex.encodeHexString(hmacSha512(preSign, SECRET_KEY));

	HttpsURLConnection connection = (HttpsURLConnection) new URL(url).openConnection();
        connection.setSSLSocketFactory(sslContext.getSocketFactory());
      
        //Add headers
        connection.setRequestMethod(method);
        connection.addRequestProperty("Api-Key", API_KEY);
        connection.addRequestProperty("Api-Timestamp", epoch);
        connection.addRequestProperty("Api-Content-Hash", contentHash);
        connection.addRequestProperty("Api-Signature", signature);
        connection.addRequestProperty("Accept", "application/json");
        connection.addRequestProperty("Content-Type", "application/json");

        if(connection.getResponseCode() != 200) {
      	  InputStream es = connection.getErrorStream();
          String jsonOutputString = IOUtils.toString(es, "utf-8");
          JSONObject jsonErrObj = new JSONObject(jsonOutputString);
	  System.err.println("ERROR response form Bittrex "+jsonOutputString);
        } else { 
	    try(BufferedReader br = new BufferedReader(
      	    new InputStreamReader(connection.getInputStream(), "utf-8"))) {
      	    StringBuilder response = new StringBuilder();
      	    String responseLine = null;
      	    while ((responseLine = br.readLine()) != null) 
      	      response.append(responseLine.trim());

 	    System.out.println(response.toString());
	  }
        }
      } catch (FileNotFoundException fe) {
        fe.printStackTrace();
      } catch (IOException ioe) {
        ioe.printStackTrace();
      } catch (Exception e) {
        e.printStackTrace();
      } 
    }

####### END ##########

**Comment by bittrex-pete** [comment]
Glad it's working. One other thing to watch out for is that there are some requests that return a 201 Created instead of a 200 Ok on success. You can find them by searching for "201 Created" in the doc if you're curious which ones.

**Comment by gdast** [comment]
Thanks for that tip. I've changed my Java logic that checks the HTTP response code from:

if(connection.getResponseCode() != 200) 
// Do blah blah

to:

if(connection.getResponseCode() < 200 || connection.getResponseCode() > 299)
// Do blah blah

**Comment by gdast** [comment]
Issue resolved
