### ISSUE TITLE
Why is a deserialization error returned?

### ISSUE THREAD

**Issue by AndrNic** [Bittrex/bittrex.github.io#256]
Hello!
Why does the string deserialization error return?
string example = "[{\"resource\":\"order\",\"operation\":\"post\",\"payload\":{\"marketSymbol\":\"USD-EUR\",\"direction\":\"BUY\",\"type\":\"LIMIT\",\"quantity\":\"0.8386\",\"limit\":\"0.836\",\"timeInForce\":\"FILL_OR_KILL\"}},{\"resource\":\"order\",\"operation\":\"post\",\"payload\":{\"marketSymbol\":\"USD-EUR\",\"direction\":\"SELL\",\"type\":\"MARKET\",\"quantity\":\"4\",\"timeInForce\":\"IMMEDIATE_OR_CANCEL\"}}]";
On my PC, this line is deserialized:
var r = JsonConvert.DeserializeObject<List<Root>>(example);

public class Payload
  {
    public string marketSymbol { get; set; }
    public string direction { get; set; }
    public string type { get; set; }
    public string quantity { get; set; }
    public string limit { get; set; }
    public string timeInForce { get; set; }
    public string id { get; set; }
  }

  public class Root
  {
    public string resource { get; set; }
    public string operation { get; set; }
    public Payload payload { get; set; }
  }
However, your server returns an error:
{"code":"BAD_REQUEST","detail":"Refer to the data field for specific field validation failures or extra fields in the body that were rejected.","data":{"newOrder":["Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Bittrex.Platform.Models.NewOrder' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\r\nPath '', line 1, position 1."]}}

**Comment by bittrex-pete** [comment]
It works fine for me if I post to `v3/batch`.  I'm guessing you're posting to `v3/orders` by instead which will only accept a single order and results in that error message if you try to send a batch.

**Comment by AndrNic** [comment]
You're right. Thanks.
offtopic:
If you choose a pair on your site, for example, https://global.bittrex.com/Market/Index?MarketName=EUR-USD, actively Buy. If you click on any ask price, this price will be displayed in Price. If you then switch to Sell, the price in Price will disappear and you can not enter it again by clicking on the previous price. You can only first click on some other ask price, and then on the previous one. Buy works the same way.

**Comment by bittrex-pete** [comment]
Thanks. I'll pass that along to the team that works on the website.
