### ISSUE TITLE
Candle intervals

### ISSUE THREAD

**Issue by skepok** [Bittrex/bittrex.github.io#260]
hello,

Currently 4 hours isnt supported for the candle interval. Is it possible to add a value for this such as HOUR_4? 

Thanks

**Comment by bittrex-pete** [comment]
Hi @skepok - we might add more candle intervals in the future, but it's not high on our priority list as it's pretty straight forward to construct new intervals out of the existing ones e.g. constructing a 4 hour candle out of four 1 hour candles.

**Comment by skepok** [comment]
Hi Pete,

Ofcourse! Thanks for getting back to me, I'll use that as a solution, thanks

Scott
