### ISSUE TITLE
CONDITIONAL_ORDERS response INVALID_CONTENT_HASH

### ISSUE THREAD

**Issue by fangchenxuan** [Bittrex/bittrex.github.io#261]
hi, when i used conditional_orders api to order, it does not work, reseponse to INVALID_CONTENT_HASH, the parameters are 
as follow:
{"orderToCreate":{"quantity":1.0,"marketSymbol":"USDT-EOS","type":"limit","timeInForce":"IMMEDIATE_OR_CANCEL","direction":"buy"},"triggerPrice":6.7,"marketSymbol":"USDT-EOS","orderToCancel":{"type":"CONDITIONAL_ORDER"}}

**Comment by bittrex-pete** [comment]
Hi @fangchenxuan - INVALID_CONTENT_HASH means that the value you're sending for the Api-Content-Hash header doesn't match the hash we're computing on your request body when we receive the request.  Could be the thing you're computing the hash on is not identical to what's being sent. For example if some characters are escaped or there's a difference in whitespace or something like that. For the body you posted above, I'd expect the hash to be 

`43b8291dd87285e0556de6ef52ba3bdaef192fa136fbce753ccf0fb2c3a91f0175d8b14f867c558bde3ca15cd9c1c38cbb61dc91f263d20f09ac2ac5d0c19696`

Another thing that I noticed, there's something wrong with that request body. The orderToCancel object doesn't actually specify the order that you're trying to cancel - that field is missing in your example. That wouldn't directly cause the INVALID_CONTENT_HASH error but I thought I would point it out.
