### ISSUE TITLE
Bittrex API - Destop application 

### ISSUE THREAD

**Issue by HabybaWN** [Bittrex/bittrex.github.io#265]
Dear Team

If we have a verified business account CRYPTO-AFRIQUE and a verified Bank Account to funds the business with EURO. and intend on trading using the API. We will have one pool of funds but plan on creating an API key for each trader (8) to track P&L”. 

**Can we link our business account associated to Significant Control Person, to our local desk application?**  wee have one application for registred ours cotumers générated factures.  

 Or 

 **Link only one button from the business account : Total plus fee ( attached picture) to one button of our application.** 

Best regards,

**Comment by HabybaWN** [comment]
![Capture d’écran 2021-06-08 à 17 10 23](https://user-images.githubusercontent.com/85570358/121212316-83a49280-c87d-11eb-9282-8ff2f0f152fe.png)

**Comment by bittrex-pete** [comment]
Hi @HabybaWN - I'm not entirely sure I understand the question. API keys aren't used to access our website. You could certainly issue different API keys to each trader for use in your application and not share the real account credentials with anyone. I'd suggest reaching out to our corporate care team for further help with this issue.

**Comment by HabybaWN** [comment]
I explain to you :

I have a website  https://www.crypto-afrique.com
and a business account at Bittrex Global.
We put funds in EURO into our account at Bittrex Global. Then, we buy BTC
and others altcoins and distribute them to our local customers.

Our website registers all costumers for KYC and prepare bills for each
client, locally. There existe also a desktop application to register
costumers and generate bills.

My question is how to link *a button from our business account * to one
button our local app? the  button
*Total plus fee.  *



*Let me know if you don't understand. *

Le mar. 8 juin 2021 à 18:55, bittrex-pete ***@***.***> a
écrit :

**Comment by HabybaWN** [comment]
No. It is not yet the question.
*I know the fees at Bittrex Global. *

I plan my owner business
* :  *
I have a website  https://www.crypto-afrique.com  very known in west
africa.
I have opened a business account at Bittrex Global.
I put  funds in EURO into my business account at Bittrex Global, much
money.  So, with 8 supports, we buy BTC and others altcoins and distribute
these cryptocurrencies
to our local customers and GET commission in local currency (XOF).
CRYPTO-AFRIQUE is a broker.

Our website https://www.crypto-afrique.com allows us to register all  our
customers, for KYC and prepare bills for each customer, locally.
There exist also a desktop application to register customers and generate
bills.

In the business model, really we need only on button from Bittrex "
*Total plus fee". *

*WITHOUT COPYING The value from the button *"
*Total plus fee" of Bittrex (cf attached picture),  WE WANT TO LINK IT TO
OUR  PLATEFORM. *


My question is how to link *a button from our business account * to one
button of our local app? the  button
*"Total plus fee".  *

Do you understand me ?
*else i will plan  another meeting with my technical team *

Le mar. 8 juin 2021 à 22:31, bittrex-pete ***@***.***> a
écrit :

**Comment by bittrex-pete** [comment]
Sorry, no, I do not understand the question

**Comment by HabybaWN** [comment]
OK.  So tell me if you understand this :
My owner business
* is : *
I have a website  https://www.crypto-afrique.com  very known in west
africa.
I have opened a business account at Bittrex Global.
I put  funds in EURO into my business account at Bittrex Global, much
money.  So, with 8 supports, we buy BTC and others altcoins and distribute
these cryptocurrencies
to our local customers and by consequence we take *commission in local
currency (XOF).*  We are an "exchange" or a broker if you want. We are
between Bittrex and the local customers.

Our website https://www.crypto-afrique.com allows us *to register all  our
customers for KYC* and *prepare bills for each customer*, locally.
We have also a desktop application to register customers and generate bills.

Le mer. 9 juin 2021 à 01:46, bittrex-pete ***@***.***> a
écrit :

**Comment by HabybaWN** [comment]
As Europe's leading cryptocurrency exchange, Bittrex offers all professional clients an API for trading on the exchange, which allows us to interact directly with the Bittrex trading system. OKAY. 

I will certainly issue different API keys to each trader for use in our application.
not share the real account credentials with anyone.  AS YOU SAID ABOVE. 

So, since i have not integrated this API, not yet, i want to know what is happened with www.crypto-afrique.com for example.
Can i have demo (video or pictures, etc..) of one webside integrated the Bittrex API ?

best regards

**Comment by bittrex-pete** [comment]
Unfortunately we don't maintain any materials like what you have requested.

**Comment by HabybaWN** [comment]
Thank you. So if you have understand my request, can me give me some explanations, link to read etc..? 
**My main problem actual is : i don't know how API Bittrex for Business account work.**

**Comment by bittrex-pete** [comment]
All of our documentation is posted here: https://bittrex.github.io/api/v3   

There aren't any differences from an API standpoint between a personal account and a business account

**Comment by HabybaWN** [comment]
Can link my business acount to my webpage www.crypto-afrique.com ? to trade automatically (buy and sell) ?

**Comment by bittrex-pete** [comment]
There isn't any further help I can provide on this issue. Please reach out to customer support for any further assistance: https://bittrexglobal.zendesk.com/

**Comment by HabybaWN** [comment]
Our business is : 
we have a website  https://www.crypto-afrique.com  very known in west
africa and have opened a business account at the exchange Bittrex Global. www.crypto-afrique.com is then a Broker. 
we put  funds (FIAT) in EURO into our business account at Bittrex Global, trade from a **single fund pool**  .   with 8 supports, we buy/sell BTC and others altcoins. 

Our website https://www.crypto-afrique.com  is complete. My question : 

CAN WE ACCESS TO OUR BUSINESS ACCOUNT IN BITTREX GLOBAL,  via our website ?
