### ISSUE TITLE
Bittrex API's -> Desktop or web application

### ISSUE THREAD

**Issue by HabybaWN** [Bittrex/bittrex.github.io#268]
Dear Team, 

Our business is :
we have a website https://www.crypto-afrique.com very known in west
africa and have opened a business account at the exchange Bittrex Global. www.crypto-afrique.com is then a Broker.
we put funds (FIAT) in EURO into our business account at Bittrex Global, trade from a single fund pool with 8 legal Business Trader , we buy/sell BTC and others altcoins.

Our website https://www.crypto-afrique.com is complete. My question is :

With Bittrex API, Can our Business Traders access to our Business account IN BITTREX GLOBAL, via our website ?

Best regards

**Comment by HabybaWN** [comment]
Hello Team,

Can you answer me please ?

**Comment by bittrex-pete** [comment]
Hi @HabybaWN - questions like that are beyond the scope of this forum, which is limited to specific API questions. As I suggested previously, please reach out to customer support or corporate care for further assistance.

**Comment by HabybaWN** [comment]
Hi Team Support,

Ok thank you for the feedback.

The last question may be : I have API key's now for my Business account. 
i want to Know how to allow my team supports to trade on the same account ?  What is the process ? 

Best regards
