### ISSUE TITLE
Install Github / Slack app?

### ISSUE THREAD

**Issue by mellertson** [Bittrex/bittrex.github.io#27]
Is there any chance you could install the Slack app for Github, so I can receive notifications using Slack at work?  

If so, here's the link to install it.

https://slack.github.com/github/install/37643419/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlnZ2VyX2lkIjoiNDI5ODEwNTYyNDAzLjE3OTM3MzM5NjI4OS5lOTk2NjgyYzRhMDQ5OGFkODY4ZjZhYWVlYTA1Y2JjZiIsImlhdCI6MTUzNjE4MTA1MSwiZXhwIjoxNTM2MTg0NjUxfQ.op8A3_MFJB2FtAAmTP7rTsnWOB4so7rUUSSlVzHeSew

**Comment by pdotmidge** [comment]
Sure, I'd be happy to. Have your IT person give me administrative permissions to your Slack instance and I'll get that set right up. ;)
