### ISSUE TITLE
Last Execution ID Request Parameters

### ISSUE THREAD

**Issue by gliderman** [Bittrex/bittrex.github.io#270]
The documentation for the [GET /executions/last-id](https://bittrex.github.io/api/v3#operation--executions-last-id-get) endpoint on v3 seems a bit unclear where there is a listed marketSymbol parameter, but when testing both with and without it I get the same result (requested on a market that was not the last I traded on).  Is there supposed to be a difference and/or can it be confirmed this is an optional parameter?  As far as I can tell, the primary use is for syncing with the websocket stream, which is what I'm working on and just want to make sure I understand it.  Thanks!

**Comment by bittrex-pete** [comment]
Hi @gliderman  - You're correct on all counts. The only purpose for that API is syncing the executions websocket stream (which is not market specific). There's no reason to provide a marketSymbol and it doesn't do anything if provided. I've logged a bug to get it removed from the documentation.

**Comment by gliderman** [comment]
Alright, thanks for clarifying!
