### ISSUE TITLE
Ask and Bid price in limit orders

### ISSUE THREAD

**Issue by surinpeter** [Bittrex/bittrex.github.io#272]
Hello

 where should I specify ask or bid price in REST API v3 limit post/orders ?

On https://bittrex.github.io/api/v3#/definitions/NewOrder a can see only 

{
  "marketSymbol": "string",
  "direction": "string",
  "type": "string",
  "quantity": "number (double)",
  "ceiling": "number (double)",
  "limit": "number (double)",
  "timeInForce": "string",
  "clientOrderId": "string (uuid)",
  "useAwards": "boolean"
}

Should I specify ask/bid in "limit" item or somewhere else ?

Thank You

Peter

**Comment by bittrex-pete** [comment]
Hi @surinpeter - yes - the limit field is where you should put the price you're willing to accept

**Comment by surinpeter** [comment]
Thank You :-)
