### ISSUE TITLE
Buy 100% at market price

### ISSUE THREAD

**Issue by Martibis** [Bittrex/bittrex.github.io#273]
I want to set up an order which buys at market price for the maximum I can buy. What would be the best way to do this using the API?

I assume I have to set the quantity, but if I understand correctly that's the amount I want to buy, so I don't understand how to set the right quantity (considering fees and moving prices).

**Comment by bittrex-pete** [comment]
Hi @Martibis - I'd suggest using a CEILING_MARKET order if you know how much you want to spend but don't know what that equates to in terms of quantity. This order type will let you, for example, buy as much BTC as you can for 1000USD as opposed to need to specify that you want to buy  0.0025BTC and hoping that's about 1000USD.  Example request/response below. In this example I spent 1000USD and got 0.00251041BTC.

POST /orders
{
  "marketSymbol": "BTC-USD",
  "direction": "BUY",
  "type": "CEILING_MARKET",
  "ceiling": 1000,
  "timeInForce": "FILL_OR_KILL"
}

Example response
{
    "id": "cadd990c-8f88-481a-b19b-447a78e51774",
    "marketSymbol": "BTC-USD",
    "direction": "BUY",
    "type": "CEILING_MARKET",
    "ceiling": "1000",
    "timeInForce": "FILL_OR_KILL",
    "fillQuantity": "0.00251041",
    "commission": "0.30343276",
    "proceeds": "999.69656724",
    "status": "CLOSED",
    "createdAt": "2021-08-17T16:56:43.97Z",
    "updatedAt": "2021-08-17T16:56:43.97Z",
    "closedAt": "2021-08-17T16:56:43.97Z"
}
