### ISSUE TITLE
Minimums seem different on different cryptos

### ISSUE THREAD

**Issue by Neobii** [Bittrex/bittrex.github.io#274]
I have worked with the buy order limit in the past and it would let me do something as small as 
`2021/08/07 03:02:23
2021/08/07 03:02:23
USD-ZRX
BUY
Limit
$0.91482000
1.86324277
$0.91398999
100.00%
$1.70894569`

However, when I'm trying to do a ceiling market for `sushi-usd` buy... I had to spend at least $6 USD.  When I looked at the minimum, it's 10000 satoshi per trade... but right now that is around 4.8 dollars.  Is there something else determining minimums that might be specific on specific cryptos?

*edit*
I see now sushi requires $5.06961689 for a buy limit order...

**Comment by bittrex-pete** [comment]
Hi @Neobii - There are two minimum constraints on order size: the amount of base currency must be greater than the minTradeSize of the market and the value of the trade in quote currency must be at least 10k satoshi.

**Comment by Neobii** [comment]
Aha, I just found the `minTradeSize`, thanks for the super quick response!

**Comment by Neobii** [comment]
Okay, this is a different issue...

Sometimes with the same math, I see that some sell orders go through and some don't.  This is above the minimums defined and when I use my numbers to make a limit sell on the website it goes through.

failed sell order "OMG-USD", quantity: 1.4 @ 6.106573539167
Error: Error: Request failed with status code 400

![d3914d47-1d11-47e9-9718-2d17b65eff3c](https://user-images.githubusercontent.com/1931021/130308976-4d00c98d-3667-4045-993b-15bb444411f8.jpg)

**Comment by Neobii** [comment]
Works now.
