### ISSUE TITLE
USD percent change

### ISSUE THREAD

**Issue by Neobii** [Bittrex/bittrex.github.io#275]
How is USD 24hr percent change calculated?

And is there some way to retrieve the number ya'll are using through the API?

**Comment by bittrex-pete** [comment]
You can get 24hr percent change from the REST api here: https://bittrex.github.io/api/v3#operation--markets-summaries-get or from the equivalent websocket stream https://bittrex.github.io/api/v3#method-Market-Summaries

With respect to how we calculate it, I believe it's the percent change between the open value of the minute candle from 24hrs ago and the most recent trade when it's updated.
