### ISSUE TITLE
Bittrex EUR, USD account balance

### ISSUE THREAD

**Issue by surinpeter** [Bittrex/bittrex.github.io#278]
Hello Bittrex, 

 is there any way in API v3 how to get balance of all holded coins calculated to EUR or USD ?

Thank You

Peter

**Comment by bittrex-pete** [comment]
Hi @surinpeter - unfortunately no, we don't provide any functionality that will do this for you. The closest thing you could do would be to get the user's account balances from /balances and then the currently prices from /markets/tickers and do that math.

**Comment by surinpeter** [comment]
OK, Thank You
