### ISSUE TITLE
NewWithdrawal in Bittrex API v3

### ISSUE THREAD

**Issue by surinpeter** [Bittrex/bittrex.github.io#279]
Hello Bittrex, 

 NewWithdrawal structure in API v3 is : 

{
  "currencySymbol": "string",
  "quantity": "number (double)",
  "cryptoAddress": "string",
  "cryptoAddressTag": "string",
  "fundsTransferMethodId": "string (uuid)",
  "clientWithdrawalId": "string (uuid)"
}

What is "fundsTransferMethodId"?   Should I use it if I transfer for example XRP from one exchange to another ? It is optional ?

Thank You

Peter

**Comment by bittrex-pete** [comment]
fundsTransferMethodId is optional. It isn't used for much currently, but the plan is that you'll be able to use that instead of cryptoAddress for fiat banking operations like initiating wire transfers. We don't support that quite yet, but that's what it will be used for.

**Comment by surinpeter** [comment]
Ok, thank You
