### ISSUE TITLE
hub.server.invoke('GetAuthContext', API_KEY)  gets me none. I cannot authenticate.

### ISSUE THREAD

**Issue by ShailjaGitHub** [Bittrex/bittrex.github.io#28]
challenge = hub.server.invoke('GetAuthContext', API_KEY) 
print("Challenge :",challenge)
signature =  create_signature(API_SECRET, challenge)
auth = hub.server.invoke('Authenticate', API_KEY, signature)
print("Auth:",auth)

Output:
Challenge : None
Auth: None

**Comment by laserlance** [comment]
Without seeing any other code, it appears that something is wrong with the API_KEY.

**Comment by pdotmidge** [comment]
Hi again, try the Python sample in the [samples directory](https://github.com/Bittrex/bittrex.github.io/blob/master/samples/WebsocketSample.py).
