### ISSUE TITLE
Sending two POST requests with payload data using the same timestamp returns a misleading error.

### ISSUE THREAD

**Issue by teodor-ivanovv** [Bittrex/bittrex.github.io#280]
Sending two POST requests with payload data using the same timestamp returns an INVALID_CONTENT_HASH instead of some timestamp error which is really misleading.

**Comment by bittrex-pete** [comment]
Hi @teodor-ivanovv - I'm not able to reproduce the behavior you're describing. Are you sure you updating the content hash you're using between requests to reflect the differences in the payload data?

**Comment by teodor-ivanovv** [comment]
Try to send two HTTP POST requests simultaneously without validating a thread-safe timestamp (exactly for creating orders). You will receive INVALID_CONTENT_HASH but actually, the problem is in the timestamp, not in the content hash. Content hash is based only on the request payload data.

**Comment by bittrex-pete** [comment]
Still no luck reproducing. Do you have a small code sample you could share?
