### ISSUE TITLE
Bittrex API v3: Error 'invalidRequestParameter': 'marketSymbol'

### ISSUE THREAD

**Issue by jtpank** [Bittrex/bittrex.github.io#284]
I am trying to use Bittrex V3 API: https://bittrex.github.io/api/v3

Running the following code produces the following error: {'code': 'BAD_REQUEST', 'detail': 'Refer to the data field for specific field validation failures.', 'data': {'invalidRequestParameter': 'marketSymbol'}

Note I have removed my API_SECRET and API_KEY definitions for privacy, but can assure that they are valid and correct.

```
import time
import hashlib
import json
import requests
import hmac
import urllib.parse

def postMarketOrderSell(quantity):
    URI = 'https://api.bittrex.com/v3/orders'
    payload = {
        'marketSymbol': 'BTC-USD',
        'direction': 'SELL',
        'type': 'MARKET',
        'quantity': quantity,
        'timeInForce': 'GOOD_TIL_CANCELLED'
    }
    timestamp = str(int(time.time()*1000))
    content = json.dumps(payload)
    print("content: " + content)
    contentHash = hashlib.sha512(content.encode()).hexdigest()
    Method = "POST"
    URL = URI + '?' + '&'.join(['{}={}'.format(k, v) for (k, v) in payload.items()])
    presign = timestamp + URL + Method + contentHash
    print(presign)
    SIGNATURE = hmac.new(bytes(API_SECRET.encode()), presign.encode(), hashlib.sha512).hexdigest()

    headers = {
        'Api-Key' : API_KEY,
        'Api-Timestamp' : timestamp,
        'Api-Content-Hash': contentHash,
        'Api-Signature' : SIGNATURE
    }
    r = requests.post(URL, json=payload, headers=headers, timeout=5)
    print(r.json())

def main():
    postMarketOrderSell(1.0)
if __name__ == "__main__":
    main()
```

Am I incorrectly setting up my POST request? I have other GET requests using a similar format and they are working fine. My GET request requiring authentication to 'https://api.bittrex.com/v3/balances' works like a charm.

Furthermore, after some messing around, if I swap the positions of some of the payload entries, then the error corresponds to the FIRST entry. For example, setting the payload as

```
 payload = {
        'direction': 'SELL',
        'marketSymbol': 'BTC-USD',
        'type': 'MARKET',
        'quantity': quantity,
        'timeInForce': 'GOOD_TIL_CANCELLED'
    }
```
results in an error: {'code': 'BAD_REQUEST', 'detail': 'Refer to the data field for specific field validation failures.', 'data': {'invalidRequestParameter': 'direction'}

**Comment by bittrex-pete** [comment]
Hi @jtpank - looks like you're sending the payload in request parameters. They need to be sent in the body of the POST request instead. It looks like you actually are sending them in the body already, but you're sending them in the URL too. Give it a try with URL set to what you have URI set to.

**Comment by jtpank** [comment]
Excellent, that worked, thanks bittrex-pete!

**Comment by BryceWayne** [comment]
FWIW, this **edit** fixed it for me...

`
def postMarketOrderSell(quantity):
    URI = 'https://api.bittrex.com/v3/orders'
    payload = {
        'marketSymbol': 'BTC-USD',
        'direction': 'SELL',
        'type': 'MARKET',
        'quantity': quantity,
        'timeInForce': 'GOOD_TIL_CANCELLED'
    }
    timestamp = str(int(time.time()*1000))
    content = json.dumps(payload)
    print("content: " + content)
    contentHash = hashlib.sha512(content.encode()).hexdigest()
    Method = "POST"
     # ~~URL = URI + '?' + '&'.join(['{}={}'.format(k, v) for (k, v) in payload.items()])~~
    presign = timestamp + URI + Method + contentHash
    print(presign)
    SIGNATURE = hmac.new(bytes(API_SECRET.encode()), presign.encode(), hashlib.sha512).hexdigest()

    headers = {
        'Api-Key' : API_KEY,
        'Api-Timestamp' : timestamp,
        'Api-Content-Hash': contentHash,
        'Api-Signature' : SIGNATURE
    }
    r = requests.post(URI, json=payload, headers=headers, timeout=5)
    print(r.json())

def main():
    postMarketOrderSell(1.0)
if __name__ == "__main__":
    main()
`
