### ISSUE TITLE
Can't understand what order durations match for different order types.

### ISSUE THREAD

**Issue by DenysFedorovych** [Bittrex/bittrex.github.io#288]
Hi!
I'm working with your API and I can't get fully what order durations can I set for different order types. For example:
For market order I can set only FOK (fill-or-kill) or IOC (immediate-or-cancel) durations, but I can't set GTC (good-till-cancelled) or GTC_PO (post-only-GTC).
For the limit orders, I don't know what order durations are supported. Where can I find such information?
Also, I tried to get this from your web version, but I faced such a behavior of uploading order (it's cancelled and then submitted). How should I understand that - is such duration supported, or not?
![image](https://user-images.githubusercontent.com/63046982/144233434-1158f5bb-8368-4734-815f-40a8032a3a45.png)

**Comment by bittrex-pete** [comment]
Hi @DenysFedorovych - there's a table containing supported order type/time in force options in this section of the documentation: https://bittrex.github.io/api/v3#topic-Placing-Orders 

I've copy/pasted a screenshot of it here for your convenience: 
![image](https://user-images.githubusercontent.com/50755685/144281116-618d1b19-78d9-469a-a161-030e51d0431a.png)

**Comment by DenysFedorovych** [comment]
Thanks a lot! It's just what I was looking for)
