### ISSUE TITLE
How can I subscribe for my own trade book in python through signalR .

### ISSUE THREAD

**Issue by ShailjaGitHub** [Bittrex/bittrex.github.io#29]
hub.server.invoke('queryExchangeState', 'BTC-RDD') returns nothing.

I want to use a private subscription for getting my own trades.
How can I know my order is now been traded in the market.
I am coding in python.
Please help.

**Comment by pdotmidge** [comment]
Well, there's a Python sample in the [samples directory](https://github.com/Bittrex/bittrex.github.io/blob/master/samples/WebsocketSample.py).
