### ISSUE TITLE
How do you write a signed request function in python

### ISSUE THREAD

**Issue by KNelly** [Bittrex/bittrex.github.io#292]
I had it working on v1 but cant figure out how to do it in v3.
This is my v1 function that doesn't work anymore
def signed_request(url):
    now = time.time()
    url += '&nonce=' + str(now)
    signed = hmac.new(API_SECRET_KEY, url.encode('utf-8'), hashlib.sha512).hexdigest()
    headers = {'apisign': signed}
    r = requests.get(url, headers=headers)
    return r.json()

**Comment by bittrex-pete** [comment]
Hi @KNelly - there is some documentation of the process here: https://bittrex.github.io/api/v3#topic-Authentication 

Let me know if there are parts that are confusing and you need some more help with

**Comment by KNelly** [comment]
Figured out my problem with the v1 api. Are you guys ever going to stop the v1 api or are you just not updating it now?

**Comment by bittrex-pete** [comment]
It's been in end of life/no updates mode for over a year now. We're planning on taking the next step and actually shutting it down a month from now on 3/3.

**Comment by KNelly** [comment]
yikes well i better figure out the v3 then, thanks
