### ISSUE TITLE
SubscribeToExchangeDeltas returns no FillId(FI) for fills

### ISSUE THREAD

**Issue by dmitrig89** [Bittrex/bittrex.github.io#3]
Subscribing to SubscribeToExchangeDeltas seems to return no FillId for order fills.

According to wiki:
Fills: 
```
    [
        {
            FillId    : int,
            OrderType : string,
            Rate      : decimal,
            Quantity  : decimal,
            TimeStamp : date
        }
    ]
```

This works properly and returns a valid FillId from: 
https://beta.bittrex.com/signalr
But not from 
https://socket.bittrex.com/signalr

**Comment by rtomayko** [comment]
@pwnzya Oh nice, thanks for that. Much appreciated.

**Comment by pwnzya** [comment]
**UPDATE** -  Bittrex gave us the heads up in their Slack channel:

> bittrex-pmidge
> *Heads Up: Websocket Server Status*
> As promised, this is official notice that `beta.bittrex.com` is going be sunset, and you should move all WS API connections to `socket.bittrex.com` as soon as you can. The domain will remain available, so you may continue using it, but between now and Friday the resources serving it will be scaled down and I won't guarantee any kind of stability for folks continuing to connect to that resource. This change is necessary to clear the path for some other API-based work we need to do to address reported issues regarding WS stability and REST timeouts.
> 
> A note about Cloudflare: many of you have noticed Cloudflare DDOS protection has been disabled for some time, and as a general rule we will keep it off unless there is very good reason to re-enable it. As is the case in such circumstances, there will be no advance warning, and we will disable it only when we are certain it is safe to do so.

**Comment by laserlance** [comment]
@pwnzya Thanks for the update. It's unfortunate that this particular issue--the fillid not existing on the "socket" url--hasn't been fixed yet as far as I can tell. My application depends on this heavily. I guess it's back to spamming the REST API.

**Comment by pwnzya** [comment]
**UPDATE 2** - They just posted this message:
> **bittrex-ben**
> Please hold off moving to socket.bittrex.com - the code there is outdated and will be updated soon.

> **bittrex-pmidge**
> We're going to update socket.bittrex.com as soon as we can, possibly tonight or tomorrow night. That will make sure the two bugfixes reported during beta are deployed there, somehow we missed that during post-beta wrap-up. Our end of week deadline hasn't moved, so getting changes staged on your end is still wise.
> 
> I realize for some folks this is a one-liner, but for others it is updating deployed code, pushing code to customers, etc. so I can't in good faith advise standing down.

So, we should keep using beta.bittrex.com for a few more days.

Sorry for the confusion.

**Comment by jayarjo** [comment]
As far as I can see still no trade id on `socket.bittrex.com/signalr` endpoint. Are you guys still using beta one?

**Comment by jayarjo** [comment]
@pwnzya how did you manage to get invitation to the dev slack channel?

**Comment by pwnzya** [comment]
@jayarjo Hello.  I managed to get an invite to their slack when I was actively participating in one of the issue threads in beta.
As for the "Intermittent connectivity issue", I believe most of us solved the issue either by using a library that auto-reconnect and resubscribe when the connection stops sending data for a while, or implemented the reconnect logic in their own code.

**Comment by laserlance** [comment]
@jayarjo I'm still using the beta version and it has become more stable--fewer loss of connection. I haven't checked the 'socket' connection recently, but I do have a backup that uses the REST API if/when the websocket connection goes down.

**Comment by jayarjo** [comment]
In theory SignalR protocol does support fallback connection itself, via long-polling. Unfortunately that library that I'm using currently doesn't support it.

**Comment by davidsulock** [comment]
Recently Bittrex changed this API response for me and started sending the FillIds. Rejoice!
