### ISSUE TITLE
Need Historical access for REST Account APIs

### ISSUE THREAD

**Issue by evanjbowling** [Bittrex/bittrex.github.io#30]
Hi,

I need to request historical data for some of the account apis:

* https://bittrex.com/api/v1.1/account/getorderhistory
* https://bittrex.com/api/v1.1/account/getwithdrawalhistory?currency=BTC
* https://bittrex.com/api/v1.1/account/getdeposithistory?currency=BTC

Currently, these APIs only let me retrieve a certain number of previous records. While the WebSocket API would provide a way to get all of this information going forward, this does not account for the following:

* a dropped WebSocket connection
* the data can't be re-fetched later because there is no REST endpoint pagination

Is there some means to retrieve historical account information that I'm overlooking?

Thanks

**Comment by pdotmidge** [comment]
Your understanding is correct, there's no way to get at this through the v1.1 API. The v3 API, releasing early 2019, will allow you to do this. Documentation preview is [here](https://bittrex.github.io/api/v3).
