### ISSUE TITLE
Does Bittrex Global's API work the same as Bittrex US?

### ISSUE THREAD

**Issue by JoeyAlvizo** [Bittrex/bittrex.github.io#314]
We been working on a trading bot for about 2 years now and was probably going to be ready by this Summer then we got the news about Bittrex US shutting down. Wanted to know if it was worth setting up a company outside the US or if the API is not the same then just giving up.

**Comment by bittrex-jen** [comment]
Yes - Bittrex Global uses the same trading engine and REST API as Bittrex US.  The API URL is even the same.  You would need to complete the Bittrex Global corporate onboarding process.

**Comment by JoeyAlvizo** [comment]
Thank you @bittrex-jen
