### ISSUE TITLE
I have got gaps in sequence numbers

### ISSUE THREAD

**Issue by litwr2** [Bittrex/bittrex.github.io#33]
Hi!
Sometimes when I subscribed to **several** markets I got gaps in sequence numbers.  They can have length up to 5 consecutive numbers in my tests.  What does it mean?  Has the update sequence broken if we got such a gap?  Should I reconnect?  Let's look at a sample of data - it has the gap.

> {"M":"BTC-ETH","N":481844,"Z":[],"S":[{"TY":0,"R":0.03435500,"Q":55.26750000},{"TY":1,"R":0.03436500,"Q":0.0}],"f":[]}
{"M":"BTC-ETH","N":481845,"Z":[{"TY":0,"R":0.03405441,"Q":1.77315561},{"TY":1,"R":0.02840000,"Q":0.0}],"S":[{"TY":1,"R":0.03439913,"Q":0.0},{"TY":0,"R":0.03770000,"Q":11.41733763}],"f":[]}
{"M":"BTC-ETH","N":481846,"Z":[],"S":[{"TY":0,"R":0.03434878,"Q":5.19247372},{"TY":1,"R":0.03436499,"Q":0.0},{"TY":0,"R":0.03440487,"Q":0.11817000},{"TY":1,"R":0.03770000,"Q":0.0}],"f":[]}
{"M":"BTC-ETH","N":481848,"Z":[],"S":[{"TY":0,"R":0.03434500,"Q":51.55000000},{"TY":1,"R":0.03435500,"Q":0.0}],"f":[]}

We missed 481847. :(

**Comment by jayarjo** [comment]
Clarification on this definitely won't harm. Are we supposed to request full orderbook, if such gap is detected?

@litwr2 I guess you could request full orderbook in the case of gap and do a diff against your local one. See if you get any mismatches.

**Comment by litwr2** [comment]
My question is definitely for the server software developers.  Is it normal to miss the sequence numbers?  Indeed we can try to find out more details about this problem requesting a full orderbook but it is not that easy because this request can come to the server **after** an update message or even several messages are sent to my client and this makes the diff senseless.  Anyway thank you very much for your suggestion.

**Comment by xinan** [comment]
It is happening quite frequently to me when I subscribe to all exchange deltas.

**Comment by pdotmidge** [comment]
Dropped nonces is not uncommon. Some folks have it happen frequently, others say it's never happened to them. The procedure we recommend when this occurs is formally documented with our [recent API doc update](https://bittrex.github.io/api/v1-1#topic-Best-Practices).

We anticipate this will happen less often in the v3 WS API as, among other things, nonces will be shared across servers. This would enable you to maintain redundant subscriptions for the same markets, throwing away duplicate data.

**Comment by jayarjo** [comment]
@pdotmidge might not be relevant but is there a place where we can submit issues with REST API?

`/v1.1/account/getorderhistory` is always returning empty array :/
