### ISSUE TITLE
How to build a live candle from websocket?

### ISSUE THREAD

**Issue by slidenerd** [Bittrex/bittrex.github.io#34]
Since there is no mention of this anywhere in the docs, or past issues, I had to ask it. Some exchanges update tickers very rapidly and therefore tickers can be used as the source of the candle (example Poloniex), here on Bittrex it seems the ticker data gets updated once a second or so, should I use the trade channel  for building candles or is there some non documented klines endpoint (ex Cryptopia has undocumented ws endpoint), my primary concern is to get the same candles as Bittrex's website. if you can share any sample of how you guys are doing it, it would be super appreciated.
Thanks

**Comment by laserlance** [comment]
As you've deduced, using the Bittrex ticker as a method for generating candle data is not reliable, nor will the candle data be accurate. If you're using the "Ask" or "Bid" price as a gauge, this does not accurately represent the market price. If you're using the "Last" price, the data could be stale. The only thing that represents the market price on any market, on any exchange--whether cryptocurrency or stock market, etc.--is to see the actual trade price as the trade occurs, or at least in the sequence of the trade occurring i.e. having a timestamp to go with the trade values.

The undocumented ws endpoint Cryptopia is using may be the "V2 getTick" endpoint. At best, these data are ~2-minutes late; at worst, ~4-minutes late--assuming we're looking at 1-minute periods. ClueDex is a service that provides updated 1-minute candle data via a websocket where the data are generated approximately 20-seconds after the minute closes calculated using the actual trade data. They then store the values and offer historical candle data based on the trade data.

So, I think if you're wanting to calculate accurate candle data, you will want to use the actual trade data.

**Comment by slidenerd** [comment]
thank you so much for the detailed response, i ll check out what this cluedex is all about, in the meantime, if it isnt too much to ask,is there any sample code for building candles from ticks

**Comment by laserlance** [comment]
I don't have sample code for you, but it isn't as difficult as it may seem to you to generate the candle data. The data are timestamped so this is a big help. 

1. You grab the first trade that occurs during the period you're interested in, and that price is the Open. 
2. Find the maximum price in the set of trades over the period and that's the High.
3. Find the minimum price of that period, and that's the Low. 
4. Get the last trade of the period and that price is the Close. 
5. Add up all of the trade quantity in that period and that's the Volume. 

You can compare your results with the Bittrex charts to see if you're right. The key indicator is usually the volume; if you have the correct volume then everything else is probably correct. While the candle data on the Bittrex charts are delayed, they have been consistently accurate when I have checked. Just make sure that you zoom in as far as you can as the chart does tend to group candle data together sometimes.

**Comment by pdotmidge** [comment]
Method @laserlance describes is currently the only option in v1.1. However, this is changing with v3.0. We release the alpha-level docs [here](https://bittrex.github.io/api/v3) on Friday to get feedback.
