### ISSUE TITLE
error json data

### ISSUE THREAD

**Issue by tungnd90** [Bittrex/bittrex.github.io#36]
Hi team!

I use PHP curl with any API, and data response see same json data but I can't decode or read it!

Example: https://bittrex.com/api/v1.1/public/getticker
`{"success":true,"message":"","result":{"Bid":0.03364000,"Ask":0.03366630,"Last":0.03364000}}1`

why have '1' in the last of string?
Response data always as '1' when I want debug!

**Comment by pdotmidge** [comment]
This isn't an API issue, it's a how-you're-using-curl issue.

Try this: https://stackoverflow.com/questions/19756343/extra-value-1-is-appending-with-curl-response
