### ISSUE TITLE
Why do I need this?

### ISSUE THREAD

**Issue by hrbcksq** [Bittrex/bittrex.github.io#39]
"For websocket implementations, refer to our documentation and code samples on github: https://github.com/Bittrex/bittrex.github.io"
Maybe this is a stupid question, but I just want to read the websocket documentation.
Please explain why do I need to install ruby, jekyll, nodejs and build the docs if I only want to have a look at ws api?

**Comment by ddrenz** [comment]
If you are looking for the documentation site itself, go to [https://bittrex.github.io](https://bittrex.github.io) instead.

**Comment by lezsakdomi** [comment]
I think that the websocket documentation is rather here:
https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md

Additional info which it's only found in the samples: The returned data is base64 encoded and zip-inflated

**Comment by lezsakdomi** [comment]
I suggest reopening the issue, because a sample is not a documentation...
