### ISSUE TITLE
Enhancement - Recv window on orders

### ISSUE THREAD

**Issue by ayy1337** [Bittrex/bittrex.github.io#4]
For making orders, there should be available a method of specifying a window after it's sent for which it's valid; if received/processed by Bittrex after this time it should be automatically cancelled/ignored.

**Comment by bittrex-porter** [comment]
We have on our product roadmap GOOD_TIL_DATE orders in which you can specify a expiration timestamp for the order.  We don't have an ETA, but the v3 api will support it at some point.
