### ISSUE TITLE
Nonce is not sequential

### ISSUE THREAD

**Issue by AlexanderSubota** [Bittrex/bittrex.github.io#46]
Hello! I have a problem with maintaining my local book. I noticed that sometimes snapshot and update messages have absolutely different nonces. It looks like Bittrex refreshes all sequences. For example, snapshot messages have nonces 4563, 5654,23423 and etc. for different markets, but nonces from update messages are equal to 1 at the start, then 2, 3 and so on..
I don't understand how to handle this situation. When does Bittrex create the nonce sequence? Can it refresh the sequence during one ws session?

**Comment by bezratigreeninvestment** [comment]
Every since the mid-February update, my local order books are often outdated for several minutes despite no disconnection with the SignalR server.

**Comment by cyrus19909** [comment]
This issue has been fixed . Let us know if similar problems are being encountered  .

**Comment by AlexanderSubota** [comment]
Ok, thank you!
