### ISSUE TITLE
how to track the possibility of deposit / withdraw of currency?

### ISSUE THREAD

**Issue by mrHelg** [Bittrex/bittrex.github.io#48]
Hello!

How could I track the possibility of deposit / withdraw of anyone currency? I mean, Is it enable or disable ? See screenshot!
Thanks in advance.
![bittrex_status](https://user-images.githubusercontent.com/31572845/55220257-87edb380-520f-11e9-82f9-98987cc78e2f.png)

**Comment by cyrus19909** [comment]
That is correct. When you see the Gray color on them, it means that they are temporarily offline or are under maintenance . Also you can check https://bittrex.com/Status for wallet status

**Comment by mrHelg** [comment]
Thanks. Yes, it is clear....
But my question was about API!
How to check the wallet status by API request?

**Comment by cyrus19909** [comment]
Okay, yes you can check the status of the wallet by calling 
https://bittrex.com/api/v1.1/public/getcurrencies. Under that it should give you 'IsActive' parameter which should tell you the state of the wallet. For related info you can always look at the docs  at https://bittrex.github.io/api/v1-1. Hope that helps

**Comment by mrHelg** [comment]
So, there is a BUG!
For example, currency 'OMNI' has deposit status "FALSE" (in grey), but taking info by api "https://bittrex.com/api/v1.1/public/getcurrencies" I recieve: {'Currency': 'OMNI', 'CurrencyLong': 'OmniCoin', 'MinConfirmation': 2, 'TxFee': 0.1, **'IsActive': True, 'IsRestricted': False,** 'CoinType': 'OMNI', 'BaseAddress': '1DUb2YYbQA1jjaNYzVXLZ7ZioEhLXtbUru', 'Notice': ''}.

**Comment by cyrus19909** [comment]
Yes . There is no market associated with it so there is no deposit but just withdrawal.

**Comment by mrHelg** [comment]
And about BTT. Why "IsRestricted" is TRUE???? The trade, deposit and withdraw are permited!

{'Currency': 'BTT', 'CurrencyLong': 'BitTorrent', 'MinConfirmation': 20, 'TxFee': 1.0, 'IsActive': True, **'IsRestricted': True**, 'CoinType': 'TRON', 'BaseAddress': 'TAahLbGTZk6YuCycii72datPQEtyC5x231', 'Notice': None}

**Comment by cyrus19909** [comment]
Well BTT is on the international market so that tag says IsRestricted =TRUE. One wont be able to find that in the wallet section in USA.

**Comment by mrHelg** [comment]
As for me, it is very confusing.....
I hope in api v3 it will be fix....
Thanks for your help and explanations

**Comment by cyrus19909** [comment]
Yes v3 will be more clearer in that aspect. You can have a look at its documentation online and hope that helps. :)

**Comment by beardsleysmind** [comment]
Still in v3 in it's not clear how to get info about withdrawals and deposits status for a currency.
https://bittrex.github.io/api/v3#/definitions/Currency tells there is `status` property. But what does it mean? Doesn it mean that withdrawals AND deposits enabeld? Or does it mean something else?
I will appreciate any help on this.
