### ISSUE TITLE
GetTicks and GetLatestTick are behind and therefore create incorrect charts

### ISSUE THREAD

**Issue by petren** [Bittrex/bittrex.github.io#5]
**Issue:**
These two endpoints generally show information that is behind, most noticeable on the 1 minute timeframe:
https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=BTC-ETH&tickInterval=oneMin
https://bittrex.com/Api/v2.0/pub/market/GetLatestTick?marketName=BTC-ETH&tickInterval=oneMin

Whats more problematic is that GetLatestTick shows older data, and **sometimes skips minutes even if there are trades at that minute**.

**Here is how you can reproduce it on Bittrex.com:**
1. Open a popular market that is likely to get trades every minute (such as BTC-ETH) 
2. Set the chart to 1 minute timeframe 
3. Most of the time, you can see that the chart is already behind the computers clock by minutes 
3. Wait until new candles come in on the one minute timeframe. Often, you will see that there is a gap in time between the most recent candle, and most recent -1. (API v2.0 GetLatestTicks) 
4. Go down to the fill book. You can see that there were trades in the same minute that doesn't exist on the chart (minute 5 in my example)

Here is a (large, sorry) gif showing the issue: 
https://imgur.com/a/srCgmj0

**What it illustrates is the following:**
1. The chart is behind by minutes 
2. There is a gap between the two last candles, 1 minute is missing. Both candles are far behind the actual time 
3. There are fills in the minute that is missing, and in the minutes after it that are also missing. So there should be candles (perhaps it should produce same value candles for empty minutes too but that's a separate problem)

**Suggested solution:**
Provide a socket endpoint for chart data so that it can update real time. While fixing the delay and missing candles would be great, having real time chart data would be the ideal solution.

**Comment by technicalviking** [comment]
This does kinda suck, but there IS a current workaround using the exchange delta that might help you.  Here's an example I got working:
on app startup, I query against a market I'm interested in for the 5 min candles.  Check the age of the most recent one, if it's more than 5 minutes old, retry in 60 seconds. Eventually I get a set of candles that's less than 5 minutes old (usually when the minutes on a clock end in 3 or 8 is when I get fresh data).  Once I've got that, I subscribe to that market's exchange deltas using the socket API and check each event for the content of the 'Fills' array.  Truncate the timestamp in each 'fill' to determine which candle it applies to.  So far as I've seen, all fills are provided in chronological order, so it's easy to use the value in the Fill struct's "Rate" field as the "Close" value, as well as using it to determine "High" and "Low" values for the candle.  

Manually reassembling candles like this is is a pain in the butt, but it DOES solve the issue you're seeing.

**Comment by laserlance** [comment]
I'm presently offering a websocket connection that updates all one-minute ticks around 12-seconds after the minute closes. I've found that this is between two and four minutes faster than the Bittrex API, which is what you are seeing. While it would be nice for Bittrex to update faster, it may or may not happen. If you're interested in my alternative then check it out here: [Cluedex.com](https://www.cluedex.com/api/documentation)
