### ISSUE TITLE
An error invoking Hub method 'c2.queryExchangeState'

### ISSUE THREAD

**Issue by AlexanderSubota** [Bittrex/bittrex.github.io#50]
Hello! Sometimes an error occurred during invoking Hub method 'c2.queryExchangeState'. 
After connection to the Hub my server subscribes to exchange deltas without any errors and starts to receive update messages. Then it sends 'queryExchangeState' request to get book snapshots. Usually, it works good, but sometimes an error occurred. I don't understand what is the reason and how to handle this case? Should I resend the request (queryExchangeState) or it's better to skip all updates and try to reconnect to the Hub?

**Comment by cyrus19909** [comment]
Hi Alexander,
That is a known issue with our current implementation of sockets over signalR where in sometimes the connection drops and the subscription stops. I would recommend having a retry logic where in if the error occurs, you can drop the connection all together and reconnect to the hub. We are working on modifying our sockets to get rid of those issues. Another suggestion would be to have multiple connection to the hub where in if one gets dropped or is out of sync , you can update the orderbook from the most consistent connection. Let me know if this helps

**Comment by AlexanderSubota** [comment]
Ok, I will try. Trank you!

**Comment by cyrus19909** [comment]
Glad to be of help.
