### ISSUE TITLE
Market price overview

### ISSUE THREAD

**Issue by incobart** [Bittrex/bittrex.github.io#55]
Hi start to test V3

But Where can I get the table with all the coin pairs and there last price, low, high,  volume, bid ask, timestamp ?
I think this is the basic of your api ?
I see only a split of it in (low high volume) in summaries and the rest not available except ask per coin ???
Am I right or hopefully terrible wrong ?
Chris

**Comment by cyrus19909** [comment]
Hi Chris, 
That is correct **markets/summaries** will give you high, low, volume and timestamp(updatedAt) but to get the bids,asks and last trade you will need to call the **markets/<market>/ticker**.

**Comment by incobart** [comment]
(and why is that ? is that improvement ? )  Can I get the full list of all coin pairs with bid ask last price ? not ask per coin pair ..

Suggestion  when calling for open or closed orders could there be an option to choose limit_buy or limit_sell
thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
