### ISSUE TITLE
Api-Content-Hash

### ISSUE THREAD

**Issue by robinsingh-bw** [Bittrex/bittrex.github.io#56]
Hi,

What should we populate this header with in the new api? Documentation says: 
var contentHash = CryptoJS.SHA512(content).toString(CryptoJS.enc.Hex);

but this just gives back INVALID_CONTENT_HASH. 

What should content be for a get request to the /deposits endpoint if I have the following params: { pageSize: 200 } ?

Thanks

**Comment by robinsingh-bw** [comment]
content is just the request body json stringified apparantly.

**Comment by cyrus19909** [comment]
glad you figure that out. Let us know if you encounter any more hurdles
