### ISSUE TITLE
Nonce not available on rest API for orderbook

### ISSUE THREAD

**Issue by SkyTradeInc** [Bittrex/bittrex.github.io#57]
Can we get a nonce on the orderbook rest API, to periodically update the books as local books? The issue at the moment with the snapshot and signlr socket is it seems to go out of  sync after a while despite updates being sequential

**Comment by cyrus19909** [comment]
Unfortunately nonces are specific to websockets currently and are used to sequence the data stream. We are aware of the connection drop on the websockets and are recommending everyone to have a **drop & reconnect** logic in place (on nonce drop) along with having multiple simultaneous connections and populate order book from the most stable connection. Using multiple connections allows you to decrease the chance that a network disruption on a single connection will result in the need to re synchronize. Please let us know if any more further help is required on that front.

**Comment by SkyTradeInc** [comment]
Thanks @cyrus19909, will try that out
