### ISSUE TITLE
Invalid Api-Content-Hash

### ISSUE THREAD

**Issue by JKorf** [Bittrex/bittrex.github.io#58]
Hi, I'm trying the new V3 API. So far so good, I'm able to authenticate requests fine, but when I try to place an order for testing it returns invalid Api-Content-Hash. To my understanding it is just the SHA512 hash of the json content of the request right? Do the parameters need specific ordering?

Code (C#):
````C#
var encryptor = SHA512.Create();
var jsonContent = JsonConvert.SerializeObject(parameters);
var hash = ByteToString(encryptor.ComputeHash(Encoding.UTF8.GetBytes(jsonContent)));
````
(ByteToString simply converts the byte[] result to a hex encoded string)

jsonContent = `{"marketSymbol":"ONT-BTC","direction":"SELL","type":"LIMIT","quantity":"5","timeInForce":"GOOD_TILL_CANCELLED","limit":"0.1"}`

EDIT: I have the same problem with posting a withdrawal, so I'm probably messing something up

**Comment by JKorf** [comment]
Never mind, issue on my end. (ordered the parameters by key when writing the request body, but didnt do this when creating the hash)

**Comment by cyrus19909** [comment]
Glad you were able to figure that out. Let us know if you run into any more hurdles.

**Comment by CalvinThong** [comment]
> Never mind, issue on my end. (ordered the parameters by key when writing the request body, but didnt do this when creating the hash)

I have the same problem when sending new order in V3. Do you mind to share how you solved it?
