### ISSUE TITLE
V1.1 API Not Working

### ISSUE THREAD

**Issue by matthewdowney** [Bittrex/bittrex.github.io#59]
When I query [https://api.bittrex.com/api/v1.1/public/getmarkets](https://api.bittrex.com/api/v1.1/public/getmarkets) I get 

```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

Does this mean the V1 API is no longer supported? Didn't see anything on the website / API docs. The V3 API is still in beta. Is there a V2 I can switch my code to work with in the meantime?

**Comment by pwnzya** [comment]
It seems it started to work a few minutes ago.

**Comment by matthewdowney** [comment]
Great! I'll close this then.
