### ISSUE TITLE
Request: Successful Authentication should result in immediate transmission of active orders and balances

### ISSUE THREAD

**Issue by technicalviking** [Bittrex/bittrex.github.io#6]
Currently when loading my application, if I want to get a local rendition of the current state of my account, I have to make a v1.1 rest request to get the list of active orders and balances to set a baseline before any updates from placing orders, depositing funds, etc happen.  While this is... okay... it would be better if the socket API could be improved to provide this data, either automatically on authentication, or via a query similar to queryExchangeState.

**Comment by cyrus19909** [comment]
Thank you for your suggestion, we will happily pass that to our developers for consideration . Closing the issue for now but feel free to open it again if you'd like.
