### ISSUE TITLE
Feature Request: Trade Side & Ids in V3

### ISSUE THREAD

**Issue by matthewdowney** [Bittrex/bittrex.github.io#60]
Looking at the V3 api, I'm noticing that neither trade ids nor trade sides are being reported. This is incredibly useful information to have!

**Comment by cyrus19909** [comment]
Thanks for reaching out to us. Can you please elaborate your use case regarding trade Ids and trade sides

**Comment by matthewdowney** [comment]
Trade sides are required for high frequency analysis of tick data. One can draw all sorts of conclusions by analyzing what liquidity takers are doing. The most fundamental data point is, given a trade, did someone make a decision to buy or sell as a taker? 

Trade ids are useful for all sorts of auditability, both of the exchange and its participants.

**Comment by cyrus19909** [comment]
Thanks for explaining your use case. Currently we don't provide such depth of information via api's but thanks for the suggestion. We will bring this to the attention of our developers.

**Comment by matthewdowney** [comment]
You did in the previous version of your API.

**Comment by cyrus19909** [comment]
If you can tell me which endpoint in the previous version you are referring to, that would be helpful .

**Comment by matthewdowney** [comment]
It was the `getmarkethistory` endpoint. 
Example query: https://bittrex.com/api/v1.1/public/getmarkethistory?market=usd-bat

Example response
```
{"success":true,"message":"","result":[{"Id":15544828,"TimeStamp":"2019-05-06T23:08:41.76","Quantity":160.01334601,"Price":0.34500000,"Total":55.2046043734500000,"FillType":"FILL","OrderType":"BUY","Uuid":"eb905caf-537e-484f-94b0-f14c46a4ac6c"},{"Id":15542369,"TimeStamp":"2019-05-06T22:31:35.09","Quantity":160.01334601,"Price":0.34200000,"Total":54.7245643354200000,"FillType":"FILL","OrderType":"BUY","Uuid":"3bc5ebb9-2dda-405a-8797-6a77930708a1"}]}
```
