### ISSUE TITLE
Conditional order support

### ISSUE THREAD

**Issue by JKorf** [Bittrex/bittrex.github.io#61]
Hi, earlier there was (unofficial) support for conditional orders via the V2 API. This endpoint was later disabled while work was being done on the V3 API and I was told the feature would come back in the V3 API. 
Now looking at the V3 API I don't see support for conditional orders, is this something that is still planned?

**Comment by cyrus19909** [comment]
Thanks for reaching out to us. We have been actively working on conditional orders and they should be available on our website sometime this week. For more information please follow our twitter page. 
Thank you for your patience

**Comment by JKorf** [comment]
So I see conditional orders have been enabled on the website again, however there is no plan to also support making conditional orders in the API? Also, when placing a conditional order which hasn't been triggered yet there is no way to see that using the API? And when it has been triggered there is no way to tell that it was a conditional order when receiving it in the open orders list?

**Comment by cyrus19909** [comment]
Yes that is correct, we currently dont have support of conditional orders using API. However you can add stop loss and take profit logic while placing orders using the API. Currently, the API will not return open conditional orders but once the order is triggered it will show up in orders/closed endpoint. 
Let us know if you have any more doubts on that.
