### ISSUE TITLE
v3: Deposit paging only going back to January 2019

### ISSUE THREAD

**Issue by mrasband** [Bittrex/bittrex.github.io#62]
It seems that deposit history is only available back to January 2019, if I simply `GET /v3/deposits/closed?pageSize=200` I get fewer deposits (57 in my case) with the oldest being Jan2. However there are deposits going back to 2017 that should be visible.

I've also tried to manually page with `nextPageToken` also stops at the same while orders and withdrawals works just fine.

**Comment by cyrus19909** [comment]
That is a know issue with your api `Deposits from before 1/1/2019 are not returned by GET /deposits/closed.` 
https://bittrex.github.io/api/v3#topic-Known-Issues

**Comment by mrasband** [comment]
:man_facepalming: I completely overlooked that segment. Thanks!

**Comment by npomfret** [comment]
Will this be fixed?

**Comment by cyrus19909** [comment]
yeah we are working on a fix for the deposits.
-Thank you.

**Comment by npomfret** [comment]
@cyrus19909 any news on a fix yet?
