### ISSUE TITLE
v3 api request(s)

### ISSUE THREAD

**Issue by npomfret** [Bittrex/bittrex.github.io#64]
Please add...

 * the trades to the orders return in `GET /orders/closed`
 * ... and for each trade include: 
    * a taker/maker flag
    * the fee and fee currency
 * the fee to `GET /withdrawals/closed`
 * add the fee currency of `/orders/open` and `/orders/closed` etc
 * add all data to deposts and withdrawals (seems to be limited to 2019)... and the old API isn't returning much at all.

**Comment by cyrus19909** [comment]
The above points are on our to do list and we are currently working on the same to bring in executions which will have makers/takers , commissions and proceeds soon. 
Regarding the deposits , which are currently after 1/1/2019 for now will be fixed in the near future as well. 
Thanks for your patience. Let us know if we can help you with anything more.

**Comment by npomfret** [comment]
@cyrus19909 Great thanks!

Where can I hear about API changes?

**Comment by cyrus19909** [comment]
Great thanks! Currently we announce our updated on social media (twitter https://twitter.com/BittrexExchange) and on our zendesk
https://bittrex.zendesk.com/hc/en-us/categories/200236600-News-and-Announcements

Please let is know if we can help in anyway

**Comment by npomfret** [comment]
@cyrus19909 do you know when the deposit history will be added to the v3 api?

**Comment by npomfret** [comment]
@cyrus19909 do you know when the deposit history will be added to the v3 api?

**Comment by cyrus19909** [comment]
We currently don’t have a tentative date for it but we are working down our pipeline to get them back soon. Thanks for your patience .

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by npomfret** [comment]
@cyrus19909 do you know when the deposit history will be added to the v3 api?

**Comment by cyrus19909** [comment]
We have added the deposit history to the v3 api. Please let us know if you are still facing issue with it.

**Comment by npomfret** [comment]
Please can you officially deprecate the old API and promote the new one to production?

**Comment by cyrus19909** [comment]
We are working on our release process for v3 api by finalizing all the features. We will keep you posted when the official date is out. Thanks for your patience
