### ISSUE TITLE
Error responses need to consistently be in JSON format, even if they're from Cloudflare.

### ISSUE THREAD

**Issue by technicalviking** [Bittrex/bittrex.github.io#65]
When I wrote my lib in go to access the bittrex api, it was under the assumption (once the captcha issues were dealt with) that the responses for all API calls would all be in json format.

Imagine my surprise when I start getting html, seemingly at random!  (Spoiler warning, it wasn't random).  I had to modify my api library to dump the content of the html to a log file to figure out what was going on... 

Oh hey!  When cloudflare detects that I'm violating the (unpublished) rate limits, it spits an html page out, instead of JSON.  

Expected behavior:
IF your API documentation doesn't explicitly state that error responses will be HTML instead of JSON, then they shouldn't be HTML.

Current Behavior:
No documentation indicates that the response format can switch from JSON to HTML.

I have since fixed the underlying issue causing me to hit the rate limit, but at this point I have to wonder how stable my API library can truly be if undocumented crap like this can potentially screw me over.

**Comment by cyrus19909** [comment]
Hi i am sorry you ran in to that issue but we have that rate limiting handled via cloud flare for Beta version.
What we recommend is to validate the response based on error codes found at https://bittrex.github.io/api/v3#topic-Error-Codes. We return 429 if too many requests are made and the calls get throttled. Sorry for the inconvenience on that but hopefully having checks on status codes will help with the performance on that. Let us know if we can assist you in any other way.
