### ISSUE TITLE
Intermittent connectivity issue:

### ISSUE THREAD

**Issue by technicalviking** [Bittrex/bittrex.github.io#7]
Intermittently seeing this message trying to connect to the signal client, no clear repro steps.  Sorry.

Timestamp: 2018/04/30 22:47:47 PT
Message: "Unable to create bittrex signal client at url https://beta.bittrex.com:  Get https://beta.bittrex.com/signalr/negotiate: No matching javascript found"

**Comment by laserlance** [comment]
I postulate that connection is lost when Bittrex makes an update on their side. For example, when a new coin is listed, there will be a connection lost event. In past months, these events used to occur every few hours, but now I can go a day or a few before such occurs.
