### ISSUE TITLE
[bittrex] v3 fetch deposits and withdrawals signature error

### ISSUE THREAD

**Issue by npomfret** [Bittrex/bittrex.github.io#72]
Trying to get more of the v3 api in bittrex working. So far I've only managed to get close orders to work.  Fetch deposits and withdrawals both fail with a signature error...

```
fetch:
 bittrex GET https://api.bittrex.com/v3/withdrawals/closed?pageSize=200&startDate=2015-01-01T00%3A00%3A00Z 
Request:
 { 'Api-Key': 'xxx',
  'Api-Timestamp': '1559567691620',
  'Api-Content-Hash':
   'cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e',
  'Api-Signature':
   'd406473c14691c1523927aa28ea9545d6b09242286f8fff45b014da32fadfa767a055b1b66bc6c189cd0570cc1d2f9af15ed07846d59da20a380f4fa106c27ad' } 
 undefined 

handleRestResponse:
 bittrex GET https://api.bittrex.com/v3/withdrawals/closed?pageSize=200&startDate=2015-01-01T00%3A00%3A00Z 401 Unauthorized 
Response:
 { Date: 'Mon, 03 Jun 2019 13:14:52 GMT',
  'Content-Type': 'application/json; charset=utf-8',
  'Content-Length': '28',
  Connection: 'close',
  'Set-Cookie':
   '__cfduid=d88cd147a71096506cf165021592566c61559567691; expires=Tue, 02-Jun-20 13:14:51 GMT; path=/; domain=.bittrex.com; HttpOnly',
  'Request-Id': '766958ac-a0ff-4b8f-b022-b6f56d1e0546',
  'Strict-Transport-Security': 'max-age=15768000',
  'X-Xss-Protection': '1; mode=block',
  'X-Content-Type-Options': 'nosniff',
  'X-Download-Options': 'noopen',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '4e11eeb95d21bb8e-LHR' } 
 {"code":"INVALID_SIGNATURE"} 
```

**Comment by npomfret** [comment]
2a706e801daa4254b8de0ea79baa0d32

**Comment by npomfret** [comment]
Ignore - recreated my API keys and it started working.

**Comment by npomfret** [comment]
After recreating my API keys I can get with withdrawals API call to work, but not the deposits.

**Comment by npomfret** [comment]
Removing the startDate filter results in success for withdrawals.  Similarly, adding a 'status' filter also causes errors.

**Comment by npomfret** [comment]
But I cannot get any data from the deposits API call:
```

fetch:
 bittrex GET https://api.bittrex.com/v3/deposits/closed?pageSize=200 
Request:
 { 'Api-Key': 'xxxx',
  'Api-Timestamp': '1559571905538',
  'Api-Content-Hash':
   'cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e',
  'Api-Signature':
   '9e32fec688493b07571e830423bedce37afd3a38ca1f21b2fd2bafe74b077a7c40d5be9486753ff2fd12d8f281fa8c0fe6c46dc5c98ad4a418aba815716d976e' }  

handleRestResponse:
 bittrex GET https://api.bittrex.com/v3/deposits/closed?pageSize=200 200 OK 
Response:
 { Date: 'Mon, 03 Jun 2019 14:25:06 GMT',
  'Content-Type': 'application/json; charset=utf-8',
  'Content-Length': '2',
  Connection: 'close',
  'Set-Cookie':
   '__cfduid=da22f3cf56f3ab815d887317b14cf47311559571905; expires=Tue, 02-Jun-20 14:25:05 GMT; path=/; domain=.bittrex.com; HttpOnly',
  'Request-Id': 'c2db1134-f362-42a7-8761-33bf6831e936',
  'Strict-Transport-Security': 'max-age=15768000',
  'X-Xss-Protection': '1; mode=block',
  'X-Content-Type-Options': 'nosniff',
  'X-Download-Options': 'noopen',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '4e12559a0a3bbbb8-LHR' } 
 []  

```

This returns an empty array, but I have hundreds of deposits.

**Comment by npomfret** [comment]
Ah, I just saw this note about deposits in the known issues section. When will this be fixed?

**Comment by cyrus19909** [comment]
I am glad you got everything resolved on your end. One thing i see from the request params is that you are providing date as `startDate=2015-01-01T00%3A00%3A00Z `. Can you please give the format as `startDate=2019-05-30T22:24:47`. That should help. Regarding the deposits , we are currently working on getting that back soon . Please let us know if you run into any more hurdles with the v3 api.

**Comment by npomfret** [comment]
Thanks for the reply.  If that's the case with the date format your docs are wrong as they say to include the 'Z'.

I've also tried querying with a status field set to 'COMPLETED', but that also results in an error.

**Comment by cyrus19909** [comment]
Its not wrong as even if you get a timestamp value with 'Z' eg (2019-01-02T16:23:45Z). It will still work fine. What i was trying to convey in my previous response was that from the looks of it , encoding of the query parameter for date is not being parsed right(has 2015-01-01T00%3A00%3A00Z) where it should be (2015-01-01T00:00:00Z) . Also 'COMPLETED' seems to be working on our front. Can you please send us the query and the error and we can look into this further.Hope that helps

**Comment by npomfret** [comment]
You don't want the parameters to be encoded?  Isn't that unconventional?

**Comment by 444913387** [comment]
curl -X 'GET' -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Api-Content-Hash: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e' -H 'Api-Key: 8e83b117b91a482a9deeb4cb9e4ff6df' -H 'Api-Signature: a710e934ea783648c71aeb645178627339e0fc58542ab56b5e43ddf3206069b7c273f25058979e0576d87fe24db1ff4d7040294548d9c42c36bf985791d7002f' -H 'Api-Timestamp: 1564459077057' -H 'Connection: keep-alive' -H 'Cookie: __cfduid=d31bcc99d13012f1b03beeba2c7737aaf1564458849; __cfruid=5359a023b03dc635e7758036f1c1a749a774208d-1564458849' -H 'User-Agent: python-requests/2.21.0' -H 'content-type: application/json' 'https://api.bittrex.com/v3/orders/closed?marketSymbol=BCH-BTC&startDate=2019-07-29T03%3A57%3A55Z&endDate=2019-07-30T03%3A57%3A48Z' -v

{"code":"INVALID_SIGNATURE"}



I really don't know what's wrong.

**Comment by CherryDT** [comment]
Hi, I'm having the same issue. It indeed seems to work if the colon is not encoded at least in the signature (even though it may be encoded in the actually sent URL!)

This is very weird and unexpected, especially since it _should_ normally be encoded (if you set it using `URLSearchParams` it is as well), and because it means that the signature uses a different URL than actually sent...

Can you explain the rules there? Which characters should be encoded and which should not?

(Why can't we just encode it whatever way and as long as it's the exact same URL that we send over the wire, it should work?)

**Comment by LefterisJP** [comment]
This is a serious issue and should be added to the bittrex v3 docs ... or preferrably fixed @cyrus19909 

I wasted quite a bit of time trying to figure out why I was getting invalid signature.

**Comment by npomfret** [comment]
@cyrus19909 can you please fix the issue? encoding the parameters like this isn't the right thing to do.
