### ISSUE TITLE
Will there be separate API endpoints for Bittrex International?

### ISSUE THREAD

**Issue by ctapang** [Bittrex/bittrex.github.io#73]
In the documentation, there is a separate terms of service for Bittrex International (see https://bittrex.github.io/api/v1-1), so I am assuming the endpoint will be separate. Am I correct?

**Comment by cyrus19909** [comment]
Hi @ctapang we do have a separate set of terms and services for Bittrex international which is applied to your account level and is associated with your API key. The endpoint for making any V1 or V3 calls will be the same https://api.bittrex.com/ for v1 and v3. Please let us know if you have any other questions.
