### ISSUE TITLE
SELL with CEILING_LIMIT 

### ISSUE THREAD

**Issue by Krisa** [Bittrex/bittrex.github.io#74]
There seems to be an issue, or I'm missing something on how to place a ceiling limit sell order. Every time, I'm getting an error `INVALID_ORDER_TYPE`. 

Also, I suspect there is something wrong with the `timeInForce`. I cannot see an available option for it in the documentation:
![image](https://user-images.githubusercontent.com/1253866/59058684-7672f880-889d-11e9-90ca-7ad122a2c082.png)

I've nonetheless tried all possible timeInForce value, no success.

If I remove the parameter, or set it to null, it throws also an error that the parameter is required.

**Comment by cyrus19909** [comment]
Hi Krisa,

Thanks for reaching out to us regarding it. Currently we are only supporting order combinations shown in the table `https://bittrex.github.io/api/v3#topic-Placing-Orders`. We are working on bringing SELL to CEILING_LIMIT soon along with other variations . Thank you for your patience on that.
