### ISSUE TITLE
GTO/BCPT/ATOM withdrawals no memo?

### ISSUE THREAD

**Issue by Chappolini** [Bittrex/bittrex.github.io#75]
when I try to withdraw all of these currencies it's impossible for me to add a MEMO and thus I cant send them to where I need to send them. Thus I cannot buy these currencies on Bittrex :(

**Comment by cyrus19909** [comment]
Hi  @Chappolini , sorry you were facing the above issue. Are you calling  v3 POST /withdrawals as mentioned  here (https://bittrex.github.io/api/v3#operation--withdrawals-post). If so what is the error you are facing ?

**Comment by bezratigreeninvestment** [comment]
GTO is ERC20 on BTRX but on Binance it's Binance net, you can't move the
token between the two anymore
