### ISSUE TITLE
SignalR call limits

### ISSUE THREAD

**Issue by vJoeyz** [Bittrex/bittrex.github.io#77]
Are SignalR call limits equal to the limits of the Web API? 

Also, it isn't mentioned in the docs that the `MarketSummary` endpoint serves 5-second cached data. Is there perhaps another way to poll all symbols every second?

Thank you in advance!

**Comment by cyrus19909** [comment]
Hi @vJoeyz , thanks for reaching out to us on that. Yes currently the endpoint essentially serves cached data every 5 seconds . Even the socket **subscribetosummarydeltas** also is cached around the same time so you currently cannot poll data every second.
