### ISSUE TITLE
Find which markets are currently marked international

### ISSUE THREAD

**Issue by ByronAP** [Bittrex/bittrex.github.io#78]
We need a way to determine which markets are international only or maybe a field that designates supported regions. Does this exist/will exist soon or anyone have a way to do it?

**Comment by cyrus19909** [comment]
Hi @ByronAP ,

Thanks for reaching out to us. Currently we have v1 endpoint https://bittrex.com/api/v1.1/public/getmarkets which has attributes  IsRestricted which is True/False. True meaning its international and False meaning, its not international. We will be adding the same on v3 soon. Hope that helps.
