### ISSUE TITLE
GET /market/cancel returns NULL instead of result array

### ISSUE THREAD

**Issue by erik404** [Bittrex/bittrex.github.io#80]
When canceling an order using the v1.1 API the API returns null instead of the defined array in the documentation. The order does get canceled on the exchange.

I am using the guzzlehttp library to make the API request.

`Message: "Return value of App\Util\Api\Bittrex::request() must be of the type array, null returned" {"exception":"[object] (TypeError(code: 0): Return value of App\\Util\\Api\\Bittrex::request() must be of the type array, null returned`

**Comment by cyrus19909** [comment]
Hi @erik404 , sorry that you are facing that issue on your end. On v1 , the response should be json object something like
 {
    "success": true,
    "message": "",
    "result": null
} . From the looks of it, the `null` value is not being parsed correctly in your PHP response handler. If you can send me the code you are using to parse the response, i can help you out better on that. Thanks for your patience.
