### ISSUE TITLE
I need a java sample for v3

### ISSUE THREAD

**Issue by KingCH75** [Bittrex/bittrex.github.io#81]
I am going to update the existing v1.1 trading program to v3.
But, I do not know how to update, Because there are too many changes in v3 compared to v1.1.
If you share a simple example, please.
I would appreciate it.

thank you.

**Comment by cyrus19909** [comment]
If you can provide us with more details on your requirement as in if you are looking for authentication code  or the public/private api calls ? Also what library are you currently using in Java to make those rest calls. Looking forward for your reply

**Comment by KingCH75** [comment]
yes, that's right.
i needs sample code about authentication and private api call.

thank you.

**Comment by cyrus19909** [comment]
Okay sure we will try providing you the source code for authentication in java as soon as possible . Thanks for your patience.

**Comment by cyrus19909** [comment]
Hi Please find attached code snippet for v3 in java. The following is just an EXAMPLE on which you can build up your own client . Please let us know if the following helps.
`	
	private static HttpURLConnection getHeaders(HttpURLConnection con) throws InvalidKeyException, SignatureException, NoSuchAlgorithmException {
		  String timestamp =getTimestamp();
		String contentHash = getContentHash("");
		String uri ="https://api.bittrex.com/v3/balances";
		String method ="GET";
		String apiSecret = apiSecret;
		String preSignature = getPresignature(timestamp, uri, method, contentHash);
		String signature = getSignature(preSignature,apiSecret);
		con.setRequestProperty("Api-Key", apiKey);
		con.setRequestProperty("Api-Timestamp", timestamp);
		con.setRequestProperty("Api-Content-Hash", contentHash);
		con.setRequestProperty("Api-Signature", signature);
		return con;
	}

	private static String getSignature(String preSignature, String apiSecret) throws SignatureException, NoSuchAlgorithmException, InvalidKeyException{
		SecretKeySpec secretKeySpec = new SecretKeySpec(apiSecret.getBytes(), HMAC_SHA512);
	    Mac mac = Mac.getInstance(HMAC_SHA512);
	    mac.init(secretKeySpec);
	    return toHexString(mac.doFinal(preSignature.getBytes()));
	}

	private static String toHexString(byte[] bytes) {
		Formatter formatter = new Formatter();
	    for (byte b : bytes) {
	        formatter.format("%02x", b);
	    }
	    return formatter.toString();
	}

	private static String getPresignature(String timestamp, String uri, String method, String contentHash) {
		String preSig = String.join("", timestamp, uri, method, contentHash); 
		return preSig;
	}
	private static String getTimestamp() {
		Date date= new Date();
		String time = Long.toString(date.getTime());
		return time;
	}
	
	private static String getContentHash(String input) 
	{ 
		try { 
			// getInstance() method is called with algorithm SHA-512 
			MessageDigest md = MessageDigest.getInstance("SHA-512"); 

			// digest() method is called 
			// to calculate message digest of the input string 
			// returned as array of byte 
			byte[] messageDigest = md.digest(input.getBytes()); 

			// Convert byte array into signum representation 
			BigInteger no = new BigInteger(1, messageDigest); 

			// Convert message digest into hex value 
			String hashtext = no.toString(16); 

			// Add preceding 0s to make it 32 bit 
			while (hashtext.length() < 32) { 
				hashtext = "0" + hashtext; 
			} 

			// return the HashText 
			return hashtext; 
		} 

		// For specifying wrong message digest algorithms 
		catch (NoSuchAlgorithmException e) { 
			throw new RuntimeException(e); 
		} 
	} 

}
`
