### ISSUE TITLE
Delisted Markets in GET /orders/closed

### ISSUE THREAD

**Issue by pcartwright81** [Bittrex/bittrex.github.io#83]
I do not think that de-listed markets are coming back in the orders.  For tax purposes this would make the data incomplete and inconsistent.

**Comment by cyrus19909** [comment]
What dates are you trying to get the data for in closed orders ? You should get all the data after our v2 upgrad even for delisted markets.

**Comment by pcartwright81** [comment]
Attached is a spreadsheet with all of the orders that are filled and missing.  Additionally attached is the list of markets distinct.
When trying to pull just a market "BTC-XMG" the following error is returned.

Server returned an error: {"code":"MARKET_DOES_NOT_EXIST"}

[Missing Markets.xlsx](https://github.com/Bittrex/bittrex.github.io/files/3413115/Missing.Markets.xlsx)

[Missing Orders.xlsx](https://github.com/Bittrex/bittrex.github.io/files/3413114/Missing.Orders.xlsx)

**Comment by mchalise** [comment]
@pcartwright81 how did you fix this issue? I am having similar issue. All Order data are coming except MAID-BTC ones. Weird thing is MAID is coming from Deposit/Closed and Withdawal/Closed but not from Order/Closed.  and that Trade pair is Active in Market List. CC: @cyrus19909

**Comment by pcartwright81** [comment]
I used the csv files by year, loaded them, and merged in the data.  I am pretty sure that this was not fixed in the new API.

**Comment by mchalise** [comment]
Yeah. I Found Out that, lots of Trade pairs are marked as Prohibited now which were not prev. whose order records are not returned via API atm. eg. 
```{
"symbol": "4ART-BTC",
"baseCurrencySymbol": "4ART",
"quoteCurrencySymbol": "BTC",
"minTradeSize": "10.00000000",
"precision": 8,
"status": "ONLINE",
"createdAt": "2020-06-10T15:05:29.833Z",
"prohibitedIn": [
"US"
],
"associatedTermsOfService": [],
"tags": []
}
