### ISSUE TITLE
api

### ISSUE THREAD

**Issue by 13266583211** [Bittrex/bittrex.github.io#84]
Hello, can you use your V3 API now?

**Comment by cyrus19909** [comment]
Hi ,

We are in beta version for v3 and you can start using the same.
You can find more details about it here at
https://bittrex.github.io/api/v3

Let us know if you need any more help on that.

Thanks,
Raj

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 13266583211** [comment]
你好，你们的v3 api看不懂，我可以使用v1吗


发自我的iPhone

------------------ Original ------------------

**Comment by cyrus19909** [comment]
Can you please be more clear what you dont understand from the document so that we can help you better.

**Comment by 13266583211** [comment]
调用接口返回NOT FOUND是什么原因


发自我的iPhone

------------------ Original ------------------

**Comment by cyrus19909** [comment]
If you can tell which endpoint you are calling and how , it would be more helpful.

**Comment by 13266583211** [comment]
v3/balances这个接口


发自我的iPhone

------------------ Original ------------------

**Comment by cyrus19909** [comment]
https://api.bittrex.com/v3/balances (private call) 
with the correct authentication and headers will give you the proper response.

More details on the authentication can be found at  http://v3docsinternal.westus2.cloudapp.azure.com/api/v3/#authentication

**Comment by 13266583211** [comment]
你好，你们的ktn_usdt还没有上线吗
发自我的iPhone

------------------ Original ------------------

**Comment by 13266583211** [comment]
The ktn_usdt trade-to-balance interface can be successful.


Then


Https://api.bittrex.com/v3/orders


Https://api.bittrex.com/v3/markets/{marketSymbol}/ticker


Https://api.bittrex.com/v3/markets/{marketSymbol}/candles


The interface returns when these three interfaces are invoked


What is the {"code": "MARKET_DOES_NOT_EXIST"}?



发自我的iPhone

------------------ Original ------------------

**Comment by 13266583211** [comment]
The ktn_usdt trade-to-balance interface can be successful.Then
Https://api.bittrex.com/v3/orders
Https://api.bittrex.com/v3/markets/{marketSymbol}/ticker
Https://api.bittrex.com/v3/markets/{marketSymbol}/candles
The interface returns when these three interfaces are invoked
What is the {"code": "MARKET_DOES_NOT_EXIST"}?






------------------ 原始邮件 ------------------
发件人: "Raj"<notifications@github.com>;
发送时间: 2019年7月20日(星期六) 凌晨2:40
收件人: "Bittrex/bittrex.github.io"<bittrex.github.io@noreply.github.com>;
抄送: "oヤ偽妳變乖"<441661757@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Bittrex/bittrex.github.io] api (#84)




https://api.bittrex.com/v3/balances (private call)
 with the correct authentication and headers will give you the proper response.
 
More details on the authentication can be found at  http://v3docsinternal.westus2.cloudapp.azure.com/api/v3/#authentication

**Comment by cyrus19909** [comment]
Hey,
We don't support KTN on our markets which is why when you hit the following endpoints , you get market not found. 
Https://api.bittrex.com/v3/markets/{marketSymbol}/ticker
Https://api.bittrex.com/v3/markets/{marketSymbol}/candles

Please let us know if you need any more information on that front from us.

**Comment by cyrus19909** [comment]
Are you looking for the same market on Bittrex or Bitsdaq ?

**Comment by Vitalicus** [comment]
Why this don't work?
[https://api.bittrex.com/v3/markets/PPC/ticker](https://api.bittrex.com/v3/markets/PPC/ticker)
