### ISSUE TITLE
All tickers at once in v3

### ISSUE THREAD

**Issue by personalityson** [Bittrex/bittrex.github.io#86]
Hi,
In v1.1 it is possible to get bid and ask prices for all markets in one go via getmarketsummaries.
In the new v3 markets/summaries, bid and ask prices have been removed.
(public/getticker and /markets/{marketSymbol}/ticker only work for one market at a time. I do algo trading on some rare patterns, and so I monitor as many markets as possible, and getting tickers for all markets one by one is too cumbersome)
Should I stick to v1.1?

(Ideally I would like to see something like this:
https://www.binance.com/api/v3/ticker/bookTicker
https://api-pub.bitfinex.com/v2/tickers?symbols=ALL
)

MK

**Comment by cyrus19909** [comment]
Hi @personalityson ,

We are planning on adding a way to get all the tickers in one go with v3. Please stay tuned and thanks for your feedback.
