### ISSUE TITLE
"I really don't know what's wrong." /v3/orders/closed?marketSymbol=eth-btc&startDate=2019-07-29T03:58:55Z&endDate=2019-07-30T03:57:48Z {"code":"INVALID_SIGNATURE"}

### ISSUE THREAD

**Issue by 444913387** [Bittrex/bittrex.github.io#88]
curl -X 'GET' -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Api-Content-Hash: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e' -H 'Api-Key: xxxxxxxxxxxxxx' -H 'Api-Signature: 0e20ee75b946c103b9170856f4da3b31318b82cceed8e2ddcaa3f136f182b9e37c2895f6c5b80fdd94f78ae247a19ccb50eb47b12909565c2582d8756afc551c' -H 'Api-Timestamp: 1564557743733' -H 'Connection: keep-alive' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36' -H 'content-type: application/json' 'https://api.bittrex.com/v3/orders/closed?marketSymbol=eth-btc&startDate=2019-07-29T03%3A58%3A55Z&endDate=2019-07-30T03%3A57%3A48Z' -v

{
    "code": "INVALID_SIGNATURE"
}

**Comment by 444913387** [comment]
status_code is  401

**Comment by cyrus19909** [comment]
So i see the issue here. The query parameter (startDate and endDate) seems to be encoded (colon in the datetime - %3A). Can you please execute the request escaping the encoding of the datetime and provide a timestamp in ISO 8601 format (e.g., "2019-01-02T16:23:45Z") and see if that works .
