### ISSUE TITLE
GET /deposits/closed 

### ISSUE THREAD

**Issue by olegshmuelov** [Bittrex/bittrex.github.io#96]
I'm trying to use v3 API to get deposits closed history (GET /deposits/closed),
but the v3 returning only last transaction
![Screen Shot 2019-10-27 at 13 07 09](https://user-images.githubusercontent.com/45327364/67633663-313a7c00-f8bb-11e9-95dc-1e68d4d7820b.png)

while using v1.1 (GET /account/getdeposithistory) I can get all the history.
![Screen Shot 2019-10-27 at 13 09 24](https://user-images.githubusercontent.com/45327364/67633667-457e7900-f8bb-11e9-94b1-6f2a1177d7ae.png)

note: the withdraw history routes brings all the history, both on v1.1 & v3

**Comment by olegshmuelov** [comment]
I found in docs
![Screen Shot 2019-10-27 at 13 39 44](https://user-images.githubusercontent.com/45327364/67633967-5204d080-f8bf-11e9-80b0-2826a6d77070.png)

Any estimations when it's going to be fixed?
Thanks

**Comment by cyrus19909** [comment]
Glad you found the answer under known issues. This is currently being worked on and we hope to get that out there soon. Thanks for your patience

**Comment by olegshmuelov** [comment]
@cyrus19909 Any update?

**Comment by cyrus19909** [comment]
Hi @olegshmuelov , yes this issue has been resolved and your deposit history should go back before this 1/1/2019 now. You can apply pagination to sort the response as per needed . Thanks for the patience
