### ISSUE TITLE
cannot load such file -- bundler (LoadError)

### ISSUE THREAD

**Issue by romy2012** [Bittrex/bittrex.github.io#98]
>> File "api/v3/assets/index.html" prettified.
All tasks complete
PS E:\host\worksheet\bittrex> npm run serve

> bittrex-developers@0.1.0 serve E:\host\worksheet\bittrex
> jekyll serve

Traceback (most recent call last):
        5: from C:/Ruby25-x64/bin/jekyll:23:in `<main>'
        4: from C:/Ruby25-x64/bin/jekyll:23:in `load'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:11:in `<top (required)>'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bittrex-developers@0.1.0 serve: `jekyll serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bittrex-developers@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-11-18T03_31_38_554Z-debug.log
PS E:\host\worksheet\bittrex>

**Comment by cyrus19909** [comment]
Hi @romy2012 , 

Can you please be more specific on what you are trying to run. From the looks of it, you seem to be trying to run a local copy of our api documentation which is currently available on https://bittrex.github.io/

**Comment by cyrus19909** [comment]
Can we close this issue ?
